Repository oceanbase/odc, pull requests merged in 2023-09, with the labels that each got.

#88 feat(schema-plugin): schema-plugin access service layer
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTableStats.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/ODPOBMySQLSchemaAccessor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/JdbcOperationsUtil.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/config/EncryptableConfigurationsTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBTableController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBFunctionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPackageService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBProcedureService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBSchemaService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBSequenceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBSynonymService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTriggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTypeService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/plugin/OdcPluginManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingTask.java
  server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLDiagnoseExtensionPoint.java
  server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLInformationExtension.java
  server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLConnectionExtension.java
  server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLInformationExtension.java
  server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLSessionExtension.java
  server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleSessionExtension.java
  server/plugins/schema-plugin-mysql/pom.xml
  server/plugins/schema-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/schema/mysql/MySQLDatabaseExtension.java
  server/plugins/schema-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/schema/mysql/MySQLFunctionExtension.java
  server/plugins/schema-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/schema/mysql/MySQLProcedureExtension.java
  server/plugins/schema-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/schema/mysql/MySQLTableExtension.java
  server/plugins/schema-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/schema/mysql/MySQLViewExtension.java
  server/plugins/schema-plugin-ob-mysql/pom.xml
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLDatabaseExtension.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLFunctionExtension.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLProcedureExtension.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLTableExtension.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLViewExtension.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParser.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/utils/DBAccessorUtil.java
  server/plugins/schema-plugin-ob-oracle/pom.xml
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleFunctionExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOraclePackageExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleProcedureExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleSequenceExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleSynonymExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTableExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTriggerExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTypeExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleViewExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/utils/DBAccessorUtil.java
  server/plugins/schema-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParserTest.java
  server/plugins/schema-plugin-odp-sharding-ob-mysql/pom.xml
  server/plugins/schema-plugin-odp-sharding-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/odpsharding/obmysql/ODPShardingOBMySQLDatabaseExtension.java
  server/plugins/schema-plugin-odp-sharding-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/odpsharding/obmysql/ODPShardingOBMySQLTableExtension.java
Labels: type-feature, priority-high, module-Database object

#115 feat(mysql): sql execution adaption for mysql5.7
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/SqlExecuteStages.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/OdcStatementCallBack.java
Labels: type-feature, module-sql execution, priority-high

#113 fix(sql-check): fix can not detect table&column comment when execute a sqlscript
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/BaseSqlChecker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckContext.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckService.java
Labels: type-bug, module-sql execution

#118 fix(task):fix the issue of empty task list query results in personal mode.
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#128 fix(osc): fix wrap invalid ddl error message when sql parsed failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java
Labels: type-bug, priority-high, module-Online schema change

#130 fix(osc): fix sql of alter replace table name not correct
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OscFactoryWrapperGeneratorTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/BaseTableNameDescriptorFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/DdlConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBMySqlTableNameDescriptorFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBOracleTableNameDescriptorFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBOracleTableNameReplacer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeScheduleTaskParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/subtask/SubTaskParameterFactory.java
Labels: type-bug, priority-high, module-Online schema change, type-refactor

#139 refactor(unit-test): refact unit test cases
  .gitignore
  .secignore
  builds/unit-test.properties
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/env/BasePropertiesEnv.java
  server/integration-test/src/test/java/com/oceanbase/odc/ITConfigurations.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/AWSSecurityTokenServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/AlibabaCloudSecurityTokenServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/OSSObjcetStorageServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/OmsOpenApiServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/S3ObjcetStorageServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionBatchImportPreviewerTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/lab/ResourceServiceTest.java
  server/integration-test/src/test/resources/batchImport/connection/connection_template_simplified_chinese.xlsx
  server/integration-test/src/test/resources/batchImport/connection/connection_template_traditional_chinese.xlsx
  server/integration-test/src/test/resources/batchImport/connection/connection_template_us.xlsx
  server/integration-test/src/test/resources/batchImport/user/user_template_simplified_chinese.xlsx
  server/integration-test/src/test/resources/batchImport/user/user_template_traditional_chinese.xlsx
  server/integration-test/src/test/resources/batchImport/user/user_template_us.xlsx
  server/integration-test/src/test/resources/integration-test.properties
  server/integration-test/src/test/resources/lab-test.properties
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestProperties.java
Labels: type-bug

#140 fix(integration): external approval is always created when initiating a ticket
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowApprovalInstanceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowFactoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceUtilTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowResponseMapperFactoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowableAdaptorTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/integration/IntegrationTestUtil.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/flow/model/FlowableElement.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/UserTaskInstanceRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowApprovalInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowInstanceConfigurer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowNodeInstanceDetailResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/CreateExternalApprovalTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/RuntimeTaskConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/ApprovalSynchronizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/client/ApprovalClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/client/SqlInterceptorClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/TemplateVariables.java
Labels: type-bug, priority-high, module-External approval integartion

#137 feat(iam): add a built-in role 'individual_space'
  server/odc-migrate/src/main/resources/migrate/web/V_4_2_0_18__iam_permission.yaml
  server/odc-migrate/src/main/resources/migrate/web/V_4_2_0_19__add_iam_role_permission.yaml
  server/odc-migrate/src/main/resources/migrate/web/V_4_2_1_2__iam_role.yaml
  server/odc-migrate/src/main/resources/migrate/web/V_4_2_1_3__iam_role_permission.yaml
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/IndividualOrganizationMigrator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/TeamOrganizationMigrator.java
  server/starters/desktop-starter/src/main/java/com/oceanbase/odc/migrate/jdbc/desktop/V42034OrganizationMigrate.java
Labels: type-feature

#142 refactor(unit-test): refact unit test cases
  .gitignore
  .secignore
  builds/unit-test.properties
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/env/BasePropertiesEnv.java
  server/integration-test/src/test/java/com/oceanbase/odc/ITConfigurations.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/AWSSecurityTokenServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/AlibabaCloudSecurityTokenServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/OSSObjcetStorageServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/OmsOpenApiServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/S3ObjcetStorageServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionBatchImportPreviewerTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/lab/ResourceServiceTest.java
  server/integration-test/src/test/resources/batchImport/connection/connection_template_simplified_chinese.xlsx
  server/integration-test/src/test/resources/batchImport/connection/connection_template_traditional_chinese.xlsx
  server/integration-test/src/test/resources/batchImport/connection/connection_template_us.xlsx
  server/integration-test/src/test/resources/batchImport/user/user_template_simplified_chinese.xlsx
  server/integration-test/src/test/resources/batchImport/user/user_template_traditional_chinese.xlsx
  server/integration-test/src/test/resources/batchImport/user/user_template_us.xlsx
  server/integration-test/src/test/resources/integration-test.properties
  server/integration-test/src/test/resources/lab-test.properties
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestProperties.java
Labels: type-refactor

#141 refactor(unit-test): refact unit test cases
  .gitignore
  .secignore
  builds/unit-test.properties
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/env/BasePropertiesEnv.java
  server/integration-test/src/test/java/com/oceanbase/odc/ITConfigurations.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/AWSSecurityTokenServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/AlibabaCloudSecurityTokenServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/OSSObjcetStorageServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/OmsOpenApiServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/S3ObjcetStorageServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionBatchImportPreviewerTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/lab/ResourceServiceTest.java
  server/integration-test/src/test/resources/batchImport/connection/connection_template_simplified_chinese.xlsx
  server/integration-test/src/test/resources/batchImport/connection/connection_template_traditional_chinese.xlsx
  server/integration-test/src/test/resources/batchImport/connection/connection_template_us.xlsx
  server/integration-test/src/test/resources/batchImport/user/user_template_simplified_chinese.xlsx
  server/integration-test/src/test/resources/batchImport/user/user_template_traditional_chinese.xlsx
  server/integration-test/src/test/resources/batchImport/user/user_template_us.xlsx
  server/integration-test/src/test/resources/integration-test.properties
  server/integration-test/src/test/resources/lab-test.properties
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestProperties.java
Labels: type-refactor

#126 fix(syncDatabase): fix filter out the internal schema when synchronizing the database
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
Labels: type-bug, priority-high

#132 refactor(ob-sql-parser): add several new syntaxes which added in OceanBase 4.1.0
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBLexer.g4
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBParser.g4
  libs/ob-sql-parser/src/main/resources/oboracle/sql/OBLexer.g4
  libs/ob-sql-parser/src/main/resources/oboracle/sql/OBParser.g4
Labels: type-feature, priority-medium, type-refactor, module-sql parser

#133 fix(db-session): fix can not get latest query sql when list all sessions
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/model/OdcDBSession.java
Labels: type-bug, module-Data source management, priority-medium

#145 fix(rollbackPlan): fix desktop odc cannot generate rollback plan
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug, priority-medium, module-Online schema change

#135 fix(osc): fix duplicate foreign key constraint name when execute new table create ddl
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeValidatorTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/ddl/TableNameReplacerTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBMysqlTableNameReplacer.java
Labels: type-bug, priority-high, module-Online schema change

#156 fix(integration): uncatched exception when failed to get flow instance
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowInstanceConfigurer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/CreateExternalApprovalTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/RuntimeTaskConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java
Labels: type-bug, priority-high, module-External approval integartion

#165 fix(osc): fix create osc task ddl contains unique key but oms precheck table not found
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeValidatorOBOracleTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeValidatorTest.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/request/CommonTransferConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java
Labels: type-bug, priority-high, module-Online schema change

#168 fix(pl-debug): add exception prompt when debugging errors
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggerSession.java
Labels: type-bug, priority-medium, module-PL debugger

#171 security: broken access control in the partition plan
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/PartitionPlanController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java
Labels: security bug

#149 fix(syncDatabase): fix ob mysql before 4.x can see other tenant's schemas when syncDatabase
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLBetween2277And3XSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
Labels: type-bug, priority-high

#173 fix(osc): fix old running task throw npe when enable full verify
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/client/BaseOmsClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ProjectStepResultChecker.java
Labels: type-bug, priority-high, module-Online schema change

#134 fix(flow): flow's status is illegal when failed to submit a task
  .github/pull_request_template.md
  server/odc-service/src/main/java/com/oceanbase/odc/config/BaseFlowableConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/OdcAsyncJobExecutor.java
Labels: type-bug, priority-medium

#172 fix(security): http request during integration may receive SSRF attack
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/SSRFChecker.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/util/SSRFCheckerTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/PreConditions.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/HttpOperationService.java
Labels: security bug, module-External integration

#198 fix(pl-debug): Get connection failed when debug anonymous blocks in lowcase schema name
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggeeSession.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggerSession.java
Labels: type-bug, priority-high, module-PL debugger

#175 fix(data-security): create sensitive columns with case insensitive same column and table names
  server/integration-test/src/test/resources/datasecurity/test_scanning_sensitive_columns_ddl.yaml
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnScanningTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
Labels: type-bug, priority-medium, module-Data security

#232 fix(connection): check database type when test connection.
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTestService.java
  server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/InformationExtensionPoint.java
  server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/TestResult.java
  server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLInformationExtension.java
  server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLConnectionExtension.java
  server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLInformationExtension.java
  server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleConnectionExtension.java
Labels: type-bug

#243 refactor(migrate): speed up resource migration and add transaction control
  server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/ResourceMigrator.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/resource/ResourceSpecMigrator.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/resource/model/DataRecord.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/resource/model/DataSpec.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/resource/repository/DataRecordRepository.java
Labels: type-refactor

#254 fix(pldebug): fix debugger create new connection attach debuggee sessionId failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggeeSession.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggerSession.java
Labels: type-bug, priority-high, module-Online schema change

#275 refactor(migrates): add some abstract methods for migrates
  server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/DefaultSchemaHistoryRepository.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/MigrateConfiguration.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/Migrates.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/SchemaHistoryRepository.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/migrate/DefaultSchemaHistoryRepositoryTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/migrate/MigratesTest.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/AbstractMetaDBMigrate.java
Labels: type-refactor

#244 fix(dlm):upgrade dlm sdk version.
  pom.xml
Labels: type-bug

#287 fix(pldebug): fix debug obtain connection info from direct connection config
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java
Labels: type-bug, priority-high, module-PL debugger

#289 fix(audit): fix audit meta event for desktop
  server/starters/desktop-starter/src/main/java/com/oceanbase/odc/service/audit/DesktopAuditEventHandler.java
Labels: type-bug, priority-medium, module-Audit

#292 security: bad horizontal access control
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
Labels: security bug

#305 fix(data-transfer): failed to update data-transfer task status during running
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DataTransferRuntimeFlowableTask.java
Labels: module-Data generation and migration

#314 fix(schedule):wrong organization id in individual space.
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
Labels: type-bug

#285 feat(table-index): show index is available or unavailable
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTableIndex.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/OracleConstants.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoGreaterThan5740SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_3_x.yaml
  libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_0_x.yaml
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/MySQLNoGreaterThan5740SchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBOracleSchemaAccessorTest.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java
  server/plugins/schema-plugin-ob-oracle/src/main/resources/parser/getIndexInfo.sql
  server/plugins/schema-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParserTest.java
Labels: type-feature, priority-high, module-Database object

#327 fix: data masking failed with multiple join clause in SQL
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractor.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractorTest.java
  server/odc-service/src/test/resources/datasecurity/test_sensitive_column_extractor_sql.yaml
Labels: type-bug, priority-high, module-Data masking

#340 fix(connection):adapter result has been overwritten.
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionEnvironmentAdapter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
Labels: type-bug

#364 fix(osc): fix input sql check unsupported foreign key and different column
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java
Labels: type-bug, priority-high, module-Online schema change

#347 fix(osc): fix personal individual space obtain main account id error
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/RuntimeTaskConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
Labels: type-bug, priority-high, module-Online schema change

#345 fix(clientMode): odc fail to start on clientMode
  server/starters/desktop-starter/src/main/java/com/oceanbase/odc/service/collaboration/DesktopOrganizationResourceMigrator.java
Labels: type-bug

#369 fix(security): risky URLs discovered by security scans
  server/odc-common/src/test/java/com/oceanbase/odc/common/util/SSRFCheckerTest.java
Labels: security bug

#338 feat(integration): support retrieve xml format response
  pom.xml
  server/integration-test/src/test/java/com/oceanbase/odc/service/integration/model/ApprovalPropertiesTest.java
  server/integration-test/src/test/resources/integration/approval_integration_template.yaml
  server/integration-test/src/test/resources/integration/mocked_approval_server_config.json
  server/odc-common/pom.xml
  server/odc-common/src/main/java/com/oceanbase/odc/common/json/JsonUtils.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/json/JsonUtilsTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/HttpOperationService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/client/ApprovalClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/client/OdcIntegrationResponseHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/client/SqlInterceptorClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/IntegrationProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/OdcIntegrationResponse.java
Labels: type-feature, priority-exigency, module-External integration

#378 fix(task):add non-null validation.
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleDetailResp.java
Labels: type-bug

#377 fix(mvc): api response content type converts to xml
  server/odc-server/src/main/java/com/oceanbase/odc/server/config/MvcConfiguration.java
Labels: type-bug, priority-exigency

#365 [Enhancement]: get create database/schema sql by schema-plugin
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/plugins/schema-plugin-api/src/main/java/com/oceanbase/odc/plugin/schema/api/DatabaseExtensionPoint.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLDatabaseExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleDatabaseExtension.java
Labels: enhancement, priority-medium, type-refactor

#390 fix(osc): osc support ob ce add type ob mysql ce
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/enums/OmsOceanBaseType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/BaseCreateOmsProjectValve.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/WebCreateOmsProjectValve.java
Labels: type-bug, priority-high, module-Online schema change

#394 feat(json-datatype):Table creation and result set editing support json data type
  server/odc-migrate/src/main/resources/migrate/common/R_2_0_0__initialize_version_diff_config.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/dml/converter/DataConverters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dml/converter/MySQLJsonConverter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dml/converter/OracleJsonConverter.java
Labels: type-feature, priority-exigency

#398 fix(data-masking): add unit test case for select sql syntax
  server/odc-service/src/test/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractorTest.java
  server/odc-service/src/test/resources/datasecurity/test_sensitive_column_extractor_sql.yaml
Labels: type-refactor

#397 docs(changelog): add changelog for ODC 4.2.1
  .gitchangelog.rc
  CHANGELOG-zh-CN.md
  CHANGELOG.md
  CHANGELOG.rst
  docs/zh-CN/CHANGELOG.md.history
  docs/zh-CN/CHANGELOG.rst.history
Labels: type-docs

#402 feat(db-browser): upgrade db-browser's version to 1.0.2
  libs/db-browser/pom.xml
  pom.xml
Labels: enhancement

#406 refactor(DBTableEditor): DBTableEditor adapt for native mysql and ob mysql
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/DBTableEditor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/mysql/MySQLTableEditor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/mysql/OBMySQLTableEditor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/oracle/OracleTableEditor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/editor/DBTableEditorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/editor/MySQLTableEditorTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/browser/DBTableEditorFactory.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLTableExtension.java
Labels: priority-high, module-Database object, type-refactor

#411 feat(unit-test): use cloud database as test cluster and adapt for github action
  .github/workflows/build_daily.yaml
  .github/workflows/build_dev.yaml
  .github/workflows/build_release.yaml
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/env/AesBytesEncryptor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/env/BasePropertiesEnv.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/env/BaseTestEnv.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/MySQLNoGreaterThan5740SchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBOracleSchemaAccessorTest.java
  libs/db-browser/src/test/resources/table/mysql/testTableColumnDDL.sql
  libs/db-browser/src/test/resources/table/oracle/drop.sql
  server/integration-test/src/test/java/com/oceanbase/odc/service/automation/UserChangeAutomationEventHandlerTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionTestUtilTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionTestingTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/datatransfer/DataTransferServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/datatransfer/LoadParameterFactoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/db/DBPLServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/dml/DeleteGeneratorTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/dml/InsertGeneratorTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/dml/UpdateGeneratorTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OmsOpenApiServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeExpiredTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeMultiTaskTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeValidatorTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OscTestEnv.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/resultset/DumperResultSetExportTaskManagerTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/session/TestDataSourceFactory.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingServiceTest.java
  server/odc-common/src/main/java/com/oceanbase/odc/common/config/EncryptableConfigurations.java
  server/odc-common/src/test/resources/test-encrypt-configuration.properties
  server/odc-core/src/test/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSourceTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/cache/PageManagerTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/mapper/OracleGeneralDateMapperTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/mapper/OracleGeneralTimestampMapperTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/tool/TestDataSourceFactory.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/util/OBUtilsTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/util/OracleDateFormatTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/dml/DataConvertUtilTest.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/crypto/AesBytesEncryptor.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/crypto/BlowFishZeroPaddingBytesEncryptor.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/crypto/Encryptors.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestDBConfiguration.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestDBConfigurations.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestDBType.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestProperties.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/tool/EncryptableConfigurations.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/util/FileUtil.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/util/JdbcUtil.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/util/PropertiesUtil.java
  server/odc-test/src/test/java/com/oceanbase/odc/test/database/TestDBConfigurationsTest.java
  server/odc-test/src/test/java/com/oceanbase/odc/test/tool/EncryptableConfigurationsTest.java
  server/odc-test/src/test/resources/test-encrypt-configuration.properties
  server/plugins/connect-plugin-mysql/src/test/java/com/oceanbase/odc/plugin/connect/mysql/MySQLExtensionTest.java
  server/plugins/connect-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLExtensionTest.java
  server/plugins/connect-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleExtensionTest.java
  server/plugins/schema-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParserTest.java
Labels: priority-medium, module-Infrastructure
