Repository oceanbase/odc, pull requests merged in 2023-11, with the labels that each got.

#635 feat(dlm):support breakpoint recovery
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_2_4__add_dlm_task_meta.sql
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/TaskGeneratorEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/TaskGeneratorRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/TaskUnitEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/TaskUnitRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataArchiveJobStore.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/utils/TaskGeneratorMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/utils/TaskUnitMapper.java
Labels: type-feature

#668 fix(dlm): submit task got condition not supported error while condition contains subquery
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
Labels: type-bug

#579 docs: add changelogs
  CHANGELOG-zh-CN.md
  CHANGELOG.md
  CHANGELOG.rst
Labels: type-docs

#699 fix(sql-parser): failed to report syntax error if the input's any prefix is grammatical
  libs/db-browser/pom.xml
  libs/ob-sql-parser/pom.xml
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/OBMySQLParser.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/OBOracleSQLParser.java
  pom.xml
Labels: type-bug, module-sql parser

#707 fix(dlm):wrong order status when task is rollback
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
Labels: type-bug

#722 fix(web): response header content-type would be application/xml while using RestTemplate
  server/odc-server/src/main/java/com/oceanbase/odc/server/config/MvcConfiguration.java
Labels: type-bug

#726 feat(osc): reactor api get database about lock user required
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataBaseController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/OscController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OscLockDatabaseUserInfo.java
Labels: type-feature, type-refactor

#739 merge main into dev/4.2.2
  README-zh-CN.md
  README.md
Labels: type-build

#748 fix(sql-check): avoid reporting syntax error when sql is executed successfully
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/SqlExecuteResult.java
Labels: type-bug

#753 docs: update desktop version install package link
  README-zh-CN.md
  README.md
Labels: type-docs

#756 build: simplify arm docker build
  distribution/docker/build.sh
  distribution/docker/odc/Dockerfile
  script/build_rpm.sh
Labels: type-build

#757 fix(pl): fix column name is wrong when viewing cursor's content
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/util/OBOracleCallProcedureBlockCallBack.java
Labels: type-bug

#754 feat(ob-sql-parser): supports insert statement and add timeout settings
  libs/db-browser/pom.xml
  libs/ob-sql-parser/README.md
  libs/ob-sql-parser/pom.xml
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/BaseSQLParser.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLFromReferenceFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLInsertFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleFromReferenceFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleInsertFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleLogErrorsFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OraclePartitionUsageFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleReturningFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleUpdateFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/common/oracle/LogErrors.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/common/oracle/Returning.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/insert/ConditionalInsert.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/insert/Insert.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/insert/InsertCondition.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/insert/InsertTable.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/insert/MultiTableInsert.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/insert/mysql/SetColumn.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/util/TimeoutTokenStream.java
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBParser.g4
  libs/ob-sql-parser/src/main/resources/oboracle/sql/OBParser.g4
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/OBMySQLParserTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/OBOracleSQLParserTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLFromReferenceFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLInsertFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/OracleInsertFactoryTest.java
  pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NoSpecificColumnExists.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
Labels: type-feature, module-sql parser

#765 fix(pldebug): pldebug monitor does not exit block process exiting
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/PLDebugService.java
Labels: module-PL debugger

#764 fix(sql-execute): fix the issue where the number type is displayed using scientific notation when the value is 0.0000000
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/DefaultJdbcRowMapper.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/MySQLNumberMapper.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/mapper/MySQLNumberMapperTest.java
Labels: type-bug, module-sql execution

#760 fix(apply-project): Resource role name in DTO is modified but be trusted
  server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectParameter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectPreprocessor.java
Labels: type-bug, priority-medium

#780 feat(security-control): safety regulation adapt to ODP sharding MySQL
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
Labels: type-feature, priority-exigency, module-Security control

#766 fix(SSO): test login protocal not match
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V42013OAuth2ConfigMetaMigrate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/Oauth2Parameter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/SSOIntegrationConfig.java
Labels: type-bug, module-External integration

#814 fix(schema-plugin): cannot get table detail in odp sharding mysql mode when lower_case_table_names = 1 or 2
  server/plugins/schema-plugin-odp-sharding-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/odpsharding/obmysql/ODPShardingOBMySQLTableExtension.java
Labels: type-bug, priority-high, module-Database object

#834 enhancement(sql-check): add cache for sql-check
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/RuleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/NoColumnCommentExistsFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/NoTableCommentExistsFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleNoColumnCommentExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleNoTableCommentExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SqlCheckRules.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/SqlCheckRulesTest.java
Labels: enhancement

#837 fix(security): add white list for security scanning and modify mysql pl parser's g4
  .secignore
  libs/ob-sql-parser/src/main/resources/obmysql/pl/PLLexer.g4
Labels: type-bug

#835 enhancement(schema-plugin): speed up getting index and improve code robustness when getting table ddl
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTableExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java
Labels: enhancement, priority-high, module-Database object

#735 Fix(dlm): data deletion failed after archiving the data
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
Labels: type-bug

#845 fix(data-editing): optimize error message when the length of field exceeds the maximum limit
  server/odc-service/src/main/java/com/oceanbase/odc/service/dml/model/DataModifyUnit.java
Labels: type-bug, module-Data viewing and editing, priority-high

#846 fix(db-browser): add "SYS" prefix for oracle dictionary views
  libs/db-browser/pom.xml
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/util/ALLDataDictTableNames.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/util/AbstractOracleDataDictTableNames.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/util/DBADataDictTableNames.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/util/USERDataDictTableNames.java
  libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_3_x.yaml
  libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_0_x.yaml
  pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLService.java
Labels: type-bug, priority-high, module-Database object

#843 fix(data-security): regex column recognization rule may suffer ReDos
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/recognizer/RegexColumnRecognizer.java
Labels: type-bug, priority-high

#848 fix(data-security): regex column recognization rule may suffer ReDos 2
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/recognizer/RegexColumnRecognizer.java
Labels: type-bug

#840 fix(dlm):update limiter failed after data-delete job was created
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java
Labels: type-bug

#864 fix(database-change): OOM may occur when executing database change task with large SQL files
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/LocalFileTransferService.java
Labels: type-bug, priority-medium

#849 feat(taskframework): taskframework integration with k8s client
  pom.xml
  server/odc-service/pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobException.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/NativeK8sJobClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/PodParam.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/k8s/NativeK8sClientTest.java
Labels: type-feature, module-Task framework

#847 feat(bastion): adapt bastion integration and datasource bind project
  server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionConfigServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/DatabaseServiceTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/OdcConstants.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_4__alter_connect_connection.sql
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataSourceController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ProjectController.java
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/collaboration/ProjectRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionConfigRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/resourcerole/ResourceRoleRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionValidator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/lab/ResourceService.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/bastion/BastionUserDetailService.java
Labels: type-feature, priority-high, module-Bastion integration

#858 feat(sql-execution): let sql be only parsed once during execution
  libs/db-browser/pom.xml
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/PLParser.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/SqlParser.java
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBLexer.g4
  pom.xml
  server/integration-test/src/test/java/com/oceanbase/odc/service/session/NlsFormatInterceptorTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionConstants.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionUtil.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/DefaultConnectionSession.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/SqlExecuteStages.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/model/SqlTuple.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/AbstractSyntaxTree.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/AbstractSyntaxTreeFactories.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/AbstractSyntaxTreeFactory.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/BaseAst.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/BaseOBAstFactory.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/DropStatement.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/EmptyAstFactory.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBMySQLAst.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBMySQLAstFactory.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBMySQLDropStatementVisitor.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBMySQLPLParser.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBMySQLParser.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBOracleAst.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBOracleAstFactory.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBOracleDropStatementVisitor.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBOraclePLParser.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBOracleSQLParser.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OraclePLSQLParser.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/parser/AbstractSyntaxTreeFactoryTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/parser/AbstractSyntaxTreeTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/util/SqlUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/DataMaskingService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/ResultSetExportPreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/BaseTimeConsumingInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/DatabasePermissionInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/NlsFormatInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/SqlExecuteResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/SchemaExtractor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/SqlRewriteUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/BaseSqlChecker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/DefaultSqlChecker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NoSpecificColumnExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/RestrictDropObjectTypes.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/common/SqlUtilsTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/session/SqlRewriteUtilTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java
Labels: type-feature

#875 fix(config): modify bad system configuration
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_5__modify_upload_file_config.sql
  server/odc-server/src/main/resources/data.sql
Labels: type-bug

#857 fix(dlm):data delete failure in periodic task and remove sys tenant verification
  pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/DlmEnvironment.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java
  server/starters/desktop-starter/src/main/java/com/oceanbase/odc/service/schedule/DesktopDlmEnvironment.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/schedule/WebDlmEnvironment.java
Labels: type-bug

#885 security: MySQL JDBC arbitrary file reading vulnerability
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
  server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLConnectionExtension.java
  server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLConnectionExtension.java
Labels: priority-exigency, security bug

#911 fix(pl): failed to execute a pl that contains an out sys_refcursor parameter
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java
Labels: type-bug

#912 security: fix mysql jdbc deserialization security vulnerability
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
  server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLConnectionExtension.java
Labels: security bug

#915 merge dev/4.2.2 into main
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
  server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLConnectionExtension.java
Labels: type-build

#898 feat(datatype): support gis datatype for mysql and ob mysql
  pom.xml
  server/odc-core/pom.xml
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/DefaultJdbcRowMapper.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/MySQLGeometryMapper.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/mapper/MySQLGeometryMapperTest.java
  server/odc-migrate/src/main/resources/migrate/common/R_2_0_0__initialize_version_diff_config.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/dml/converter/DataConverters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dml/converter/MySQLGeometryConverter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/RollBackPlanJdbcRowMapper.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/dml/DataConvertUtilTest.java
Labels: type-feature, module-Data viewing and editing, priority-high

#926 feat(taskframework): refine task executor implementation
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/BaseTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/K8sJobContextProvider.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskApplication.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/sampletask/SampleTask.java
Labels: module-Task framework

#919 feat(result-set-export): use task-plugin.datatransfer to export result set
  server/integration-test/src/test/java/com/oceanbase/odc/service/resultset/DumperResultSetExportTaskManagerTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/DataMaskingFunction.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/DumperResultSetExportTaskManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTaskContext.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTaskManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTaskParameter.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/DumpParameterFactory.java
Labels: type-feature, module-Data viewing and editing

#928 feat(taskframework): add meta db env and rename method with JobIdentity
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/BaseJobTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/JobCallerTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/NativeK8sClientTest.java
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/DefaultJobContext.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobContext.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JvmJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobEnvConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/enums/TaskRunModeEnum.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/BaseTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/JobContextProviderFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskApplication.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/sampletask/SampleTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/JobCallerEvent.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/JobCallerListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/ScheduleSourceType.java
Labels: type-feature, module-Task framework

#942 fix(connection):add back connection cluster name
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionConstants.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionFactory.java
Labels: type-bug

#957 feat(taskframwork): add task result upload api
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/HttpResultClientTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/TaskController.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/CommonSecurityProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/DefaultTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskResult.java
Labels: type-feature, module-Task framework
