Repository oceanbase/odc, pull requests merged in 2023-12, with the labels that each got.

#987 fix(data-security): test masking algorithm may lead to security issue
  server/integration-test/src/test/java/com/oceanbase/odc/service/datasecurity/MaskingAlgorithmServiceTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/MaskingAlgorithmController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/MaskingAlgorithmService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/MaskingAlgorithm.java
Labels: type-bug, priority-medium, module-Data security

#871 feat(data-transfer): support transfer mysql data by DataX
  pom.xml
  server/integration-test/src/test/java/com/oceanbase/odc/service/datatransfer/MySQLTransferServiceTest.java
  server/integration-test/src/test/resources/datatransfer/export.zip
  server/integration-test/src/test/resources/log4j2-test.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DataTransferService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/task/DataTransferTask.java
  server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/dumper/DataFile.java
  server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/dumper/SchemaFile.java
  server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/model/ObjectResult.java
  server/plugins/task-plugin-mysql/pom.xml
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/MySQLDataTransferJob.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/common/Constants.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/AbstractJob.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/MySQLSchemaExportJob.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/MySQLSchemaExportJobImpl.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/SqlScriptImportJob.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/TransferJobFactory.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/ConfigurationResolver.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/DataXTransferJob.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/JobConfiguration.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/JobContent.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/JobSetting.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/parameter/MySQLReaderPluginParameter.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/parameter/MySQLWriterPluginParameter.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/parameter/PluginParameter.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/parameter/TxtPluginParameter.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/parameter/TxtReaderPluginParameter.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/parameter/TxtWriterPluginParameter.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/task/OceanBaseExportJob.java
Labels: module-Data generation and migration

#1008 fix(variables): variable updating may lead to sql injection
  server/integration-test/src/test/java/com/oceanbase/odc/service/db/DBVariableServiceTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/OracleNlsFormatDateMapper.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v1/DBVariablesController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBVariablesController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBRecyclebinSettingsService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBVariablesService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/model/OdcDBVariable.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/NlsFormatInterceptor.java
Labels: type-bug

#997 fix(bastion): inactive datasources are not cleared
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/connection/ConnectionConfigRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionConfigRecycleServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionHistoryDAOTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionHistoryRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionSessionHistoryServiceTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataSourceController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionConfigRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionHistoryDAO.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionHistoryEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionHistoryRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionConfigRecycleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionSessionHistoryService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/lab/LabSchedules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/lab/ResourceService.java
  server/odc-service/src/main/resources/mapper/ConnectionHistoryDAO.xml
Labels: type-bug, priority-medium, module-Bastion integration

#1001 fix(db-browser): DB session list show 0 in execute time for ob mysql and mysql mode
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/mysql/MySQLNoGreaterThan5740StatsAccessor.java
Labels: type-bug, module-Data source management, priority-high

#994 feat(sql-execute): unable to obtain locale info in subthread
  server/odc-service/src/main/java/com/oceanbase/odc/config/ServletConfiguration.java
Labels: type-bug

#1010 feat(taskframework): support set request cpu/mem/diskSize/mountPath param for pod
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/PodParam.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/JobCallerBuilder.java
Labels: type-feature, module-Task framework

#1000 fix(apply-project): project role names are not internationalized
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ResourceRoleBasedPermission.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ResourceRoleName.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectPreprocessor.java
Labels: type-bug, priority-medium

#1011 fix(ticket): horizontal unauthorized when query approver related role names
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/UserRoleRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
Labels: type-bug, priority-medium, module-Tickets

#1021 fix(data-security): create sensitive columns failed due to scanning duplicated columns
  server/integration-test/src/test/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnScanningTaskManagerTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnScanningTask.java
Labels: type-bug, priority-medium, module-Data security

#1019 fix(permission): user can create datasource without any project and role
  server/integration-test/src/test/java/com/oceanbase/odc/service/iam/UserPermissionServiceTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/IamController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserPermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectPreprocessor.java
Labels: type-bug, priority-medium, module-User permission

#1039 fix(integration): cannot deal with array when parsing json or xml response
  pom.xml
  server/integration-test/src/test/java/com/oceanbase/odc/service/integration/HttpOperationServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/integration/model/ApprovalPropertiesTest.java
  server/integration-test/src/test/resources/integration/approval_integration_template.yaml
  server/odc-common/pom.xml
  server/odc-common/src/main/java/com/oceanbase/odc/common/json/JsonUtils.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/json/JsonUtilsTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/HttpOperationService.java
Labels: type-bug, priority-medium, module-External approval integartion

#968 fix(database): block built-in databases when auto-sync databases to project
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DatabaseSyncSchedules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/DatabaseSyncProperties.java
Labels: type-bug, module-Data source management, priority-medium

#1053 fix(partition-plan): create partition plan task failed in obmysql 1479
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLNoGreaterThan1479SchemaAccessor.java
  libs/db-browser/src/main/resources/schema/sql/obmysql/obmysql_1_4_79.yaml
Labels: type-bug

#1052 fix(dlm):task cannot be executed due to insufficient connections
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/JobMetaFactory.java
Labels: type-bug

#1059 fix(datasource): built-in database still belong to previous project when datasource unbind project
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
Labels: type-bug, module-Data source management, priority-medium

#1078 fix(pl): no sys_refcursor shown in return type select panel when creating function
  server/odc-migrate/src/main/resources/migrate/common/R_2_0_0__initialize_version_diff_config.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/feature/VersionDiffConfigService.java
Labels: type-bug

#1098 fix(project): project participants can create database and add them into the project
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
Labels: type-bug

#1095 feat(data-masking): prohibit data-masking for native MySQL datasource
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
Labels: type-feature, priority-high, module-Data masking

#1114 fix(project): the project owner can remove all project dbas from the project
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
Labels: type-bug

#1089 fix(ticket): list all tickets returns empty in individual space
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/ApprovalPermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
Labels: type-bug

#1111 fix(ticket): tickets not filtered by projects
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceViewSpecs.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug

#1115 fix(connect-plugin): failed to connect to native percona mysql datasource when there is "-" in DBVersion String
  server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLInformationExtension.java
Labels: type-bug

#1141 docs: refine developer guide
  README-zh-CN.md
  README.md
  distribution/docker/odc-build/create_node_env.sh
  docs/en-US/DEVELOPER_GUIDE.md
  docs/en-US/images/idea-settings-build-process-heap-size.png
  docs/zh-CN/DEVELOPER_GUIDE.md
  script/functions.sh
Labels: documentation

#1143 fix(database-object) :Provide relevant prompts to users for high-risk operations when drop or create index
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/model/UpdateTableDdlCheck.java
Labels: type-bug

#1073 fix(dlm):displays incomplete information after editing
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DlmLimiterService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AbstractDlmJobPreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java
Labels: type-bug

#1165 fix(sql-rule): several sql interception bugs
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/ExternalSqlInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/SqlConsoleRuleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/model/Rule.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java
Labels: type-bug

#1088 enhance(monitor):add druid monitor
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/StringUtils.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/util/StringUtilsTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmService.java
  server/odc-server/src/main/resources/config/application.yml
  server/odc-server/src/main/resources/log4j2.xml
  server/odc-service/src/main/java/com/oceanbase/odc/config/MetaDBConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/druid/DruidMonitor.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/druid/DruidMonitorAspect.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/druid/JointPointMethodInvocationAdapter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/DruidMonitor.java
Labels: enhancement

#1147 fix(iam): users need re-login to access the individual space after they are granted for individual_space
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/DefaultOrganizationResourceMigrator.java
Labels: type-bug

#1110 fix(osc): osc log is not show totally and flow task is done unnormally
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/DBUserLogStatusMonitorTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/rest/OdcRestTemplate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeContextHolder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/DdlConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/monitor/DBUserLogStatusMonitor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/monitor/DBUserLogStatusMonitorFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/monitor/DBUserMonitorExecutor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/BaseCreateOmsProjectValve.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/SwapTableNameValve.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/OnlineSchemaChangeCompleteJob.java
Labels: type-bug, priority-exigency, module-Online schema change

#1136 feat(partition-plan):support setting scheduling strategy
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/DatabasePartitionPlan.java
Labels: type-feature

#1202 fix(database): optimize error message of synchronizing databases failure
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
Labels: type-bug

#1194 fix(sql-rule): disabling the rule 'allow-execute-sql-types' does not work
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/SqlConsoleRuleService.java
Labels: type-bug

#1213 fix(monitor):fix druid stats parser error
  server/odc-server/src/main/resources/config/application.yml
  server/odc-service/src/main/java/com/oceanbase/odc/config/MetaDBConfiguration.java
Labels: type-bug

#1228 fix(database-object):modify the prompt that prompts users about the risk of index changes
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
Labels: type-bug

#1222 fix(audit): several operating records issues after ODC V4.2.0
  server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/R4239AuditEventMetaMigrateTest.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/R4239AuditEventMetaMigrate.java
  server/odc-migrate/src/main/resources/init-config/default-audit-event-meta.yml
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_8__alter_audit_event.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/audit/AuditEventEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/audit/AuditEventMetaEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/AuditEventAspect.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/model/AuditEvent.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/model/AuditEventMeta.java
Labels: type-bug

#1225 feat(taskframework): retry when failed to report task results
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/sampletask/SampleTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/BaseTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DefaultTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/Task.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/TaskReporter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/TaskResult.java
Labels: type-feature, priority-medium, module-Task framework

#1072 fix(osc): lock ob mysql user failed when host with ip limited
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeExpiredTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataSourceController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/DBUser.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OscOBMySqlAccessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/monitor/DBUserLogStatusMonitor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ScheduleCheckOmsProjectValve.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/WebCreateOmsProjectValve.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockUserInterceptor.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestDBConfigurations.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestDBType.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestProperties.java
Labels: type-bug, module-Online schema change, type-refactor

#1212 feat(monitor):add api alarm
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/rest/OdcRestTemplate.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/GlobalExceptionHandler.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/RestExceptionHandler.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v1/HeartbeatController.java
Labels: type-feature

#1183 fix(flow): creating flow costs too much time
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/flow/GateWayInstanceRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/flow/NodeInstanceEntityRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/flow/SequenceInstanceRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/flow/ServiceTaskInstanceRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/flow/UserTaskInstanceRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowApprovalInstanceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowFactoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowGatewayInstanceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceUtilTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowResponseMapperFactoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowTaskInstanceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowableAdaptorTest.java
  server/odc-common/src/main/java/com/oceanbase/odc/common/jpa/InsertSqlTemplateBuilder.java
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/StringUtils.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/util/StringUtilsTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/jpa/EnhancedJpaRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/jpa/OdcJpaRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/GateWayInstanceRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/NodeInstanceEntityRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/SequenceInstanceRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/ServiceTaskInstanceRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/UserTaskInstanceCandidateRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/UserTaskInstanceRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/ApprovalPermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowableAdaptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowableAdaptorImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/BaseFlowNodeInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowApprovalInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowGatewayInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowInstanceConfigurer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowNodeInstanceKey.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowSequenceInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowTaskInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/OdcFlowInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/OdcFlowInstanceConfigurer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/ProcessNodeBuilderAccessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/NodeInstanceEntityKey.java
Labels: type-bug, priority-medium

#1237 fix(apply-project): failed to set mdc value
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowNodeInstanceDetailResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectFlowableTask.java
Labels: type-bug, priority-medium

#1233 fix(web-framework): invalid csrf token result into Invalid session error message
  server/odc-service/src/main/java/com/oceanbase/odc/config/CsrfConfigureHelper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/CustomInvalidSessionStrategy.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/config/PlaySiteSecurityConfiguration.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/config/WebSecurityConfiguration.java
Labels: type-bug

#1242 fix(rollback-plan): NPE when user input sql content is empty
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/RollbackPlanRuntimeFlowableTask.java
Labels: type-bug, priority-medium

#1243 fix(datasource): it occurs 'duplicate data source name' error when creating a data source in team space
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
Labels: type-bug

#1246 build
  .github/workflows/build_dev.yaml
Labels: module-Task framework

#1247 fix(partition plan):failed to disable table partition plan
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java
Labels: type-bug

#1249 fix(schema-plugin): show partition name with identifiers
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParser.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java
Labels: type-bug

#1260 fix(ticket): project "pending approval" tickets shows other project's "pending approval" tickets
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug

#1253 fix(datasource): convert the type of ob-mysql-sharding data source to ob-mysql
  server/odc-service/src/main/java/com/oceanbase/odc/config/BeanConfiguration.java
Labels: type-bug

#1227 fix(mock-data): upgrade mock-data module's version to fix several bugs
  pom.xml
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/TaskServiceTest.java
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/model/OdcDBTableColumn.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/CreateFlowInstanceReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowInstanceDetailResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/CustomMockScheduler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/MockDataRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MockDataTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MockProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/OdcMockTaskConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/util/MockDataTypeUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/info/InfoProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/info/OdcInfoService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
Labels: type-bug, module-Mock data

#1017 feat(dlm):support viewing task logs
  pom.xml
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/schedule/ScheduleTaskRepositoryTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
  server/odc-server/src/main/resources/data.sql
  server/odc-server/src/main/resources/log4j2.xml
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleTaskRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/JobMetaFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/utils/DataArchiveConditionUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/executor/AbstractQuartzJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AbstractDlmJobPreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/ScheduleTaskContextHolder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/OdcJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/OnlineSchemaChangeCompleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java
Labels: type-feature

#1272 fix(mock-data): failed to recognize the charset key of 'UTF8'
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java
Labels: type-bug, module-Mock data, priority-medium

#1273 fix(monitor): format alarm error stack to inline
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/DruidMonitor.java
Labels: enhancement

#1108 docs: add changelog for 4.2.3
  .gitattributes
  .gitchangelog.rc
  .github/workflows/build_artifact.yaml
  .github/workflows/build_daily.yaml
  .github/workflows/build_dev.yaml
  .github/workflows/build_release.yaml
  CHANGELOG-zh-CN.md
  CHANGELOG.md
  CHANGELOG.rst
  docs/zh-CN/CHANGELOG.md.history
  docs/zh-CN/CHANGELOG.rst.history
Labels: priority-medium, type-docs

#1280 fix(datasource): make ODP_SHARDING_OB_MYSQL not be converted to OB_MYSQL in some special cases
  server/odc-common/src/main/java/com/oceanbase/odc/common/json/NormalDialectTypeOutput.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/BeanConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/model/AuditEvent.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MockDataTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeScheduleTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/model/Rule.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/model/RuleMetadata.java
Labels: type-bug

#1299 feat(dlm): upgrade dlm's version to 1.0.8
  pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMConfiguration.java
Labels: type-bug

#1302 fix(sql-rule): the rule 'allow-sql-types' of dev environment is disabled by default
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_10__adjust_sql_console_rules.sql
Labels: type-bug

#1305 build: fix local rpm build failed due wrong copy obclient logic
  script/functions.sh
Labels: type-build

#1309 enhancement: add internal-endpoint for cloud storage configuration
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/config/ObjectStorageConfigurationTest.java
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudResourceConfigurations.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudResourceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/CloudObjectStorageProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/DefaultCloudEnvConfigurations.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/ObjectStorageConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/OssConfiguration.java
Labels: enhancement

#1311 refactor: delete unused configuration
  server/odc-migrate/src/main/resources/migrate/common/V_3_2_3_2__add_configuration.sql
Labels: type-refactor

#1316 fix(database-change): query task details throw file not found exception
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
Labels: type-bug, priority-medium

#1319 refactor(objectstorage): create publicEndpointCloudClient and internalEndpointCloudClient to distinguish uploading and generating presignedUrl circumstance
  server/integration-test/src/test/java/com/oceanbase/odc/service/cloud/CloudObjectStorageServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorageService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudResourceConfigurations.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudResourceService.java
Labels: type-refactor

#1325 fix(database-change): query task details throw flow instance not found exception
  server/integration-test/src/test/java/com/oceanbase/odc/service/iam/UserServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/UserTaskInstanceRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/RoleRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/ApprovalPermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
Labels: type-bug
