Repository oceanbase/odc, pull requests merged in 2023-10, with the labels that each got.

#440 fix(dlm): validate condition by sql explain.
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AbstractDlmJobPreprocessor.java
Labels: type-bug

#444 fix(data-security): use disabeld recognition rules when select all rules
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/datasecurity/SensitiveRuleRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveRuleService.java
Labels: type-bug, priority-medium, module-Data security

#443 refactor(unit-test): use blowfish encryption algorithm to replace aes
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/env/AesBytesEncryptor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/env/BasePropertiesEnv.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/crypto/AesBytesEncryptor.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/crypto/BlowFishZeroPaddingBytesEncryptor.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/crypto/Encryptors.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/tool/EncryptableConfigurations.java
  server/odc-test/src/test/resources/test-encrypt-configuration.properties
Labels: type-refactor

#455 fix(database-change): database change failed if executing a sql more than 8 hour
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java
Labels: type-bug, priority-medium, module-Tickets

#486 fix(osc): execute pre and post interceptor in retry rename table
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/BaseOscTestEnv.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OBMySqlOscTestEnv.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OBOracleOscTestEnv.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeExpiredTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeMultiTaskTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeOBMysqlSwapTableTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeOBOracleSwapTableTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/DefaultRenameTableInvoker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockRenameTableFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockUserInterceptor.java
Labels: priority-high, module-Online schema change, type-refactor

#485 fix(data-security): data masking failed when using uppercase column name
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractor.java
Labels: type-bug, priority-medium, module-Data security

#492 feat(mysql): native mysql adapt for safety regulations
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
Labels: type-feature, priority-exigency, module-Security control

#488 feat(connection): add initialization configuration capabilities for data sources
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/connection/ConnectionAttributeRepositoryTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_2_3__add_connect_connection_attribute.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionAttributeEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionAttributeRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionTestResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/TestConnectionReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/util/ConnectTypeUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/initializer/SessionCreatedInitializer.java
Labels: type-feature, module-Data source management

#507 fix(view): fix get view failed without show view permission
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoGreaterThan5740SchemaAccessor.java
Labels: type-bug, priority-high, module-Database object

#498 fix(unit-test): unit test logs expose sensitive information
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestDBConfigurations.java
Labels: priority-exigency

#509 fix(data-security): exist sensitive is not filtered and view desensitization data failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/extractor/model/DBColumn.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/SensitiveColumnMeta.java
Labels: type-bug, priority-medium, module-Data security

#537 feat(sql-parser): upgrade ob-sql-parser to 1.1.2
  pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractor.java
Labels: type-feature, priority-medium, module-sql parser

#530 fix(osc): fix get cloud main account id throw exception when environment is not cloud
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java
Labels: type-bug, priority-medium, module-Online schema change

#529 fix(osc): fix get cloud main account id throw exception when environment is not cloud
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java
Labels: type-bug, priority-medium, module-Online schema change

#546 fix(ob-sql-parser): fix failed to parse member proc without parameters
  libs/ob-sql-parser/src/main/resources/oracle/PlSqlParser.g4
Labels: type-bug, module-sql parser

#551 fix(databasechange): fix task costs too much time to start up
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
Labels: type-bug, priority-medium

#557 docs: update README, add diagrams
  README-zh-CN.md
  README.md
Labels: type-docs

#566 fix(pl-debug): fix failed to step in a subprocedure or subfunction defined in package
  libs/ob-sql-parser/src/main/resources/oracle/PlSqlParser.g4
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggerSession.java
Labels: type-bug, module-PL debugger

#533 fix(schema-plugin): cannot display constraint name for ob oralce 4.2.1
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBViewService.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParser.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTableExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleViewExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java
  server/plugins/schema-plugin-ob-oracle/src/main/resources/parser/getIndexInfo.sql
  server/plugins/schema-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParserTest.java
  server/plugins/schema-plugin-ob-oracle/src/test/resources/parser/testGetTableByParser.sql
Labels: type-bug, priority-exigency, module-Database object, feat-adapt to ob4.2

#592 fix(db-browser): cannot get table charset in native mysql mode
  .gitignore
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoGreaterThan5740SchemaAccessor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/MySQLNoGreaterThan5740SchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBOracleSchemaAccessorTest.java
Labels: type-bug, priority-high, module-Database object

#608 fix: fix failed to query data and sql rules changing is not recorded by audit event
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessors.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventAction.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventType.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/OBUtils.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/util/OBUtilsTest.java
  server/odc-migrate/src/main/resources/init-config/default-audit-event-meta.yml
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
  server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/InformationExtensionPoint.java
  server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLInformationExtension.java
  server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLInformationExtension.java
Labels: type-bug, enhancement

#599 fix(datasource): the data source list refreshes very slowly and cannot obtain the connect status while there are a huge amount of data sources
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionConfigServiceTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataSourceController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/environment/EnvironmentService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
Labels: type-bug

#616 enhancement: add log printing and avoid creating connect session when syncing datasource
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionSessionHistoryService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DatabaseSyncSchedules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBSchemaService.java
  server/plugins/schema-plugin-api/src/main/java/com/oceanbase/odc/plugin/schema/api/DatabaseExtensionPoint.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLDatabaseExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleDatabaseExtension.java
Labels: enhancement

#515 feat(permission): support apply for project permission
  server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventAction.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventType.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/TaskType.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_1__alter_list_flow_instance_view.sql
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ProjectController.java
  server/odc-server/src/main/resources/log4j2.xml
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceViewSpecs.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/ServiceTaskInstanceRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/TaskEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/AuditEventMetaService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/util/AuditUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/CreateFlowInstanceReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowInstanceDetailResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/processor/CreateFlowInstanceProcessAspect.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/mapper/OdcRuntimeDelegateMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectParameter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectPreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permissionapply/project/ApplyProjectResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTaskParameter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/TaskService.java
Labels: type-feature, priority-medium, module-User permission

#629 feat(data-security): add data type unit into response
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/DatabaseWithAllColumns.java
Labels: type-feature, priority-medium, module-Data security

#626 feat(dlm):support configuring limiter
  server/integration-test/src/test/java/com/oceanbase/odc/service/dlm/RateLimitConfigurationServiceTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ResourceType.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataArchiveJobStore.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DlmLimiterConfigMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DlmLimiterService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/RateLimitConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/utils/ScheduleTaskUtil.java
Labels: type-feature

#660 fix(sql-diagnose): fix failed to get execute plan
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
  server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/diagnose/DiagnoseUtil.java
Labels: type-bug

#652 fix(sql-check): fix syntax error check rule can not be disabled
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/BaseSqlChecker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/SyntaxErrorExistsFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/parser/SyntaxErrorStatement.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SqlCheckRules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SyntaxErrorExists.java
Labels: type-bug

#658 fix(sql-execute): fix failed to get time consuming
  server/integration-test/src/test/java/com/oceanbase/odc/service/session/NlsFormatInterceptorTest.java
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/TraceWatch.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/SqlExecuteStages.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/DataMaskingInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/ExternalSqlInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/BaseTimeConsumingInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/DatabasePermissionInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/NlsFormatInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java
Labels: type-bug, enhancement

#663 fix(data-security): meta data of built-in masking algorithm sgement is wrong
  server/odc-migrate/src/main/resources/runtime/V_4_2_0_28__add_masking_algorithm_segment.yaml
Labels: type-bug, priority-medium, module-Data security

#677 fix(pl-debug): fix the problem of hang when debugging on arm architecture ob
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggeeSession.java
Labels: type-bug, module-PL debugger

#669 fix(database-change): failed to view a scheduled database change task with rollback plan in personal space
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug, module-Control of change, priority-exigency
