Repository oceanbase/odc, pull requests merged in 2024-03, with the labels that each got.

#1682 feat(snippet): more builtin snippets
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigFacadeImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/snippet/BuiltinSnippet.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/snippet/BuiltinSnippetService.java
  server/odc-service/src/main/resources/builtin-snippet/ob-mysql-3.x-snippet.yml
  server/odc-service/src/main/resources/builtin-snippet/ob-mysql-4.x-snippet.yml
  server/odc-service/src/main/resources/builtin-snippet/ob-mysql-snippet.yml
  server/odc-service/src/main/resources/builtin-snippet/ob-sys-snippet.yml
Labels: type-feature

#1690 fix(dlm):job scheduler not found
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
Labels: type-bug

#1649 enhancement(db-browser): optimize the generated sql that modifies the visibility of the index
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/DBTableIndexEditor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTableIndex.java
  libs/db-browser/src/test/resources/table/operator/ob/mysql/index/update_single_index_test_cases.json
Labels: enhancement

#1637 fix(database-change): show wrong executing result status
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/task/JobRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/JobSchedulerTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/ProcessModeTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/TaskApplicationTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/NativeK8sJobClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/DatabaseChangeTask.java
Labels: type-bug, priority-medium

#1702 fix(database-change): create database change task failed in private sapce
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug, priority-medium

#1735 build: add code owner configuration
  .github/CODEOWNERS
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/processor/CreateFlowInstanceProcessAspect.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java
Labels: priority-medium, type-build

#1748 fix(partition-plan): npe will be thrown when input is invalid
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/mapper/CellDataProcessors.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/mapper/OBMySQLTimeDataTypeProcessor.java
  server/plugins/task-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/mapper/OBOracleDateTypeProcessor.java
  server/plugins/task-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/mapper/OBOracleTimestampTypeProcessor.java
Labels: type-feature

#1750 feat(partition-plan): disable the previous flow instance when a partition plan is related to an exists flow
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleService.java
Labels: type-feature

#1726 fix(notification): failed to send notification for partition plan
  server/integration-test/src/test/java/com/oceanbase/odc/service/notification/NotificationServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/PolicyMetadataEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PartitionPlanRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java
Labels: module-Notification

#1721 fix(dlm):database not found
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleDetailResp.java
Labels: type-bug

#1720 fix(database-change): failed to check if time-consuming sql exists in personal space
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/RollbackPlanRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeInputStream.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeSqlContent.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/SqlCheckTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/util/DatabaseChangeFileReader.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/SqlCheckRuleType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/IndexChangeTimeConsumingExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/PreCheckTask.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java
Labels: type-bug

#1759 fix(sql-execute): anonymous block execution module adapted to oracle11g
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/OdcStatementCallBack.java
  server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleConnectionExtension.java
  server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/initializer/OracleDBMSOutputInitializer.java
  server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleConnectionExtension.java
Labels: type-bug, priority-high

#1770 fix(flow): create flow instance failed when environment absent
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug, priority-medium

#1743 fix(encryption): sensitive property handler suffers from concurrcy flaw
  server/odc-common/src/main/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptor.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptorTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/encryption/SensitivePropertyHandlerImpl.java
Labels: type-bug, priority-medium

#1778 fix(dlm): interrupt job failed.
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#1766 feat(sql-check): add offline ddl detecting, key words detecting and truncate statement detecting rules
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLCreateTableFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLTruncateTableFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleTruncateTableFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/alter/table/AlterTableAction.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/createtable/CreateTable.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/truncate/TruncateTable.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLCreateTableFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLTruncateTableFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/OracleTruncateTableFactoryTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/CreateStatement.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBMySQLCreateStatementVisitor.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBMySQLPLCreateStatementVisitor.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBMySQLPLParser.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBMySQLParser.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBOracleCreateStatementVisitor.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBOraclePLCreateStatementVisitor.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBOraclePLParser.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/parser/OBOracleSQLParser.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/parser/AbstractSyntaxTreeTest.java
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/ObjectNameUsingReservedWordsFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/OfflineDdlExistsFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/TruncateTableExistsFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/SqlCheckRuleType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/BaseObjectNameUsingReservedWords.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLObjectNameUsingReservedWords.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLOfflineDdlExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleObjectNameUsingReservedWords.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleOfflineDdlExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SqlCheckRules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TruncateTableExists.java
  server/odc-service/src/main/resources/sql-check/obmysql-reserved-words.yml
  server/odc-service/src/main/resources/sql-check/oboracle-reserved-words.yml
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java
Labels: type-feature

#1706 feat(task): task executing strip from flowable
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceUtilTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/flow/ExecutionConfigurer.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/flow/builder/ServiceTaskBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/BeanInjectedClassDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowInstanceConfigurer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/ExecutionEntityFacade.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskCallBack.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskCallBackApprovalService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskSubmitter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PartitionPlanRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/RollbackPlanRuntimeFlowableTask.java
Labels: type-feature, module-Task framework

#1783 feat(partition-plan): returns partition table configs when list candidate tables
  server/integration-test/src/test/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/partitionplan/PartitionPlanServiceV2Test.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanServiceV2.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/PartitionPlanDBTable.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java
Labels: type-feature

#1786 fix(data-transfer): export Oracle object ddl without line breaks
  server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/datatransfer/model/DataTransferConfig.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/common/Constants.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/DataXTransferJob.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/factory/BaseTransferJobFactory.java
  server/plugins/task-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/task/oracle/datatransfer/job/OracleSchemaExportJob.java
Labels: module-Data generation and migration

#1772 fix(audit): add audit keys and i18n messages for some module
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventAction.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventType.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/init-config/default-audit-event-meta.yml
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/AuditEventAspect.java
Labels: type-bug

#1795 fix(taskframework): deserialize log occur error from remote
  server/odc-service/src/main/java/com/oceanbase/odc/service/logger/LoggerService.java
Labels: type-bug, module-Task framework

#1799 fix(dlm): check database permission failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug

#1800 fix(environment): flow instance selects wrong approval flow config after updating risk detect rules
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/model/RiskDetectRuleCondition.java
Labels: type-bug

#1809 fix(connect): sometimes open sql console result in 404 error
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionIdGenerator.java
Labels: type-bug

#1807 fix(database-change): read sql file failed causing sql not executed
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/SizeAwareInputStream.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/util/DatabaseChangeFileReader.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/util/ObjectStorageUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/DatabaseChangeTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/PreCheckTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/RollbackPlanTask.java
Labels: type-bug, priority-medium

#1847 fix(schedule): no permission to edit
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#1838 fix(multi-cloud): failed to create new connection with read only account
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBDatabaseUserType.java
Labels: type-bug

#1843 fix(database-permission): return authorized permission types for detail database interface
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
Labels: priority-medium, module-Database Permission

#1808 fix(taskframework): fix invalid CSRF token when task process report heart to sever
  server/odc-service/src/main/java/com/oceanbase/odc/config/CommonSecurityProperties.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/local/LocalRequestFilter.java
Labels: type-bug, module-Task framework

#1877 feat(monitor): add api rt alarm
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/trace/TraceHandlerInterceptor.java
Labels: type-feature

#1890 fix(database-management): unable to create a connection using database details
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
Labels: type-bug

#1851 enhancement(notification): support using variables in http header and body
  server/integration-test/src/test/java/com/oceanbase/odc/service/notification/BrokerTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/notification/JdbcNotificationQueueTest.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_12__update_system_config.sql
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_12__update_task_framework_enabled.sql
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_2__alter_notification_schema.sql
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/MessageEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/Broker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/Converter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/HttpSender.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationDispatcher.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationScheduleConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/ChannelConfigValidator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/model/Message.java
Labels: module-Notification

#1863 feat(database-change): support retry execute in database change task
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/DatabaseChangeTask.java
Labels: module-Security control

#1856 docs: correct developer guide
  docs/zh-CN/DEVELOPER_GUIDE.md
Labels: type-docs

#1919 fix(stateful): max pool size may less than core pool size and cause error
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StateRouteAspect.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulRouteConfiguration.java
Labels: type-bug

#1914 fix(connection): SingleConnectionDataSource concurrent getConnection may have problems
  server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSource.java
Labels: type-bug

#1904 fix(taskframework): fix retry log attribute
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobAttributeEntityColumn.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/BaseTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug, module-Task framework

#1928 fix(partition-plan): fix wrong api's path variable
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBTableController.java
Labels: type-bug

#1883 fix(taskframework): add free memory check before start new process avoid start process failed
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/SystemUtils.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_12__update_system_config.sql
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/BaseFlowUserTaskInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskCallBackApprovalService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobEnvironmentFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultTaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/MonitorExecutorStatusRateLimiter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java
Labels: type-bug, module-Task framework

#1923 fix(stateful): stateful interceptor will be npe when clientMode
  server/odc-migrate/src/main/resources/migrate/oceanbase/V_4_2_4_18__add_stateful_route.sql
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StateRouteAspect.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulRouteInterceptor.java
Labels: type-bug

#1879 fix(sql-check): failed to detect pk dropping when drop it as constraint
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/BaseObjectNameUsingReservedWords.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLOfflineDdlExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleOfflineDdlExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/PreferLocalOutOfLineIndex.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooManyColumnDefinition.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooManyColumnRefInIndex.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooManyColumnRefInPrimaryKey.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooManyOutOfLineIndex.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java
Labels: type-bug

#1896 fix(database-permission): unable apply for database permission
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/UnauthorizedDatabase.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/PreCheckTask.java
Labels: type-bug, priority-medium, module-Database Permission

#1939 fix(builtin-snippet): refine prefix for sys tenant, avoid duplicated name with mysql mode
  server/odc-service/src/main/resources/builtin-snippet/ob-sys-snippet.yml
Labels: type-bug

#1941 fix(i18n): default task description use Chinese character when locale language is English
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java
Labels: type-bug, priority-low

#1804 fix(partition-plan): the first partition value is incorrect when creating partitions sequentially based on the current time
  server/integration-test/src/test/java/com/oceanbase/odc/service/partitionplan/PartitionPlanServiceTest.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/invoker/create/OBMySQLTimeIncreasePartitionExprGenerator.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/invoker/partitionname/OBMySQLDateBasedPartitionNameGenerator.java
  server/plugins/task-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPointTest.java
  server/plugins/task-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLDateBasedPartitionNameGeneratorTest.java
  server/plugins/task-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLTimeIncreasePartitionExprGeneratorTest.java
  server/plugins/task-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/OBOracleAutoPartitionExtensionPointTest.java
  server/plugins/task-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/OBOracleTimeIncreasePartitionExprGeneratorTest.java
Labels: type-bug

#1947 fix(flow): wrong total elements and total pages of flow instances while querying in page
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/jpa/EnhancedJpaRepository.java
Labels: type-bug

#1951 fix(data-transfer): after data transfer is completed, the directory is not cleared
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/BaseSchemaExportJob.java
  server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/DataXTransferJob.java
  server/plugins/task-plugin-ob-mysql/pom.xml
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java
Labels: type-bug

#1948 fix(db-browser): the order of column names in Index and constraint are inconsistent
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_3_x.yaml
  libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_0_x.yaml
  server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/oboracle/DefaultDBStructureComparatorTest.java
Labels: type-bug

#1952 fix(taskframework): fix retry job reset destroy and heart time
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskCallBackApprovalService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug, module-Task framework

#1516 docs: updated error i18n messages
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/test/java/com/oceanbase/odc/core/shared/I18nTest.java
Labels: type-docs

#1969 fix(builtin-snippets): fix wrong description for builtin snippets
  server/odc-service/src/main/resources/builtin-snippet/mysql-snippet.yml
  server/odc-service/src/main/resources/builtin-snippet/ob-mysql-3.x-snippet.yml
  server/odc-service/src/main/resources/builtin-snippet/ob-mysql-4.x-snippet.yml
  server/odc-service/src/main/resources/builtin-snippet/ob-oracle-4.x-snippet.yml
  server/odc-service/src/main/resources/builtin-snippet/ob-sys-snippet.yml
Labels: type-bug

#1968 fix(parser): failed to parse insert statement with a table named 'json_table'
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBParser.g4
Labels: type-bug

#1959 fix(environment): modify the error message while disabling environments
  server/odc-service/src/main/java/com/oceanbase/odc/config/HookConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/environment/EnvironmentService.java
Labels: type-bug

#1961 fix(taskframework): fix cancel job and update executionTimes failed
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/BaseJobTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/JobRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/RequestHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/HttpUtil.java
Labels: type-bug, module-Task framework

#1975 builds: merge from dev/4.2.3 into main
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/jpa/EnhancedJpaRepository.java
Labels: type-build

#1613 fix(osc): osc will be failed if check oms step accumulate failed time bigger than threshold
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/configuration/OnlineSchemaChangeProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeScheduleTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/enums/OmsProjectStatusEnum.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ProjectStepResultChecker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ScheduleCheckOmsProjectValve.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/subtask/OmsResourceCleanHandler.java
Labels: type-bug, module-Online schema change

#1973 fix(taskframework): update schedule task status when cancel completed or heart check timeout
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleTaskRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/TaskRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/TaskService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/JobSchedulerFactoryBean.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateEvent.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DestroyExecutorListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/JobTerminateNotifyListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/MonitorExecutorStatusRateLimiter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/StdJobScheduler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/ResultHandleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/ScheduleTaskResultHandleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskTaskResultHandleService.java
Labels: type-bug, type-refactor, module-Task framework

#1985 fix(flowTask): fix failed to get flow task results
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DBStructureComparisonFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MockDataTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
  server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleTraceExtension.java
Labels: type-bug

#1990 fix(connect): can not access Doris datasource
  server/plugins/schema-plugin-doris/pom.xml
  server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/DorisDatabaseExtension.java
  server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/DorisFunctionExtension.java
  server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/DorisProcedureExtension.java
  server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/DorisTableExtension.java
  server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/DorisViewExtension.java
  server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/utils/DBAccessorUtil.java
Labels: type-bug

#1960 fix(shadowtable): NPE occurs when project admins detail the shadowtable and structure comparing task
  server/integration-test/src/test/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/StructureComparisonService.java
Labels: type-bug

#1994 fix(encryption): add log output when failed to decrypt
  server/odc-service/src/main/java/com/oceanbase/odc/service/encryption/SensitivePropertyHandlerImpl.java
Labels: type-bug

#1992 fix(partition-plan): failed to generate partition correctly when partition upper bound is not increased by 1 year/month/day
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/partitionplan/PartitionPlanServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/datatype/BasePartitionKeyDataTypeFactory.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/invoker/create/OBMySQLHistoricalPartitionPlanCreateGenerator.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/invoker/create/OBMySQLTimeIncreasePartitionExprGenerator.java
  server/plugins/task-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPointTest.java
  server/plugins/task-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLHistoricalPartitionPlanCreateGeneratorTest.java
  server/plugins/task-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLTimeIncreasePartitionExprGeneratorTest.java
  server/plugins/task-plugin-ob-mysql/src/test/resources/partitionplan/unix_ts_partition_generator_create_table_partition.sql
  server/plugins/task-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/invoker/create/OBOracleTimeIncreasePartitionExprGenerator.java
  server/plugins/task-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/OBOracleAutoPartitionExtensionPointTest.java
  server/plugins/task-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/OBOracleTimeIncreasePartitionExprGeneratorTest.java
Labels: type-bug

#1996 fix(sql): precision is lost when displaying timestamps
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/MySQLTimestampMapper.java
Labels: type-bug

#2006 fix(structure-compare): failed to run structure compare task without update connection permission
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DBStructureComparisonFlowableTask.java
Labels: type-bug, priority-high

#2002 fix(taskframework): fix cancel result when status is done
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/ThreadPoolTaskExecutor.java
Labels: type-bug, module-Task framework

#1932 fix(taskframework): limit running job count by calculate free memory when StartJobRateLimiter starting
  script/start-odc.sh
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/ProcessModeTest.java
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/SystemUtils.java
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ExecutorProcessBuilderFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCallerBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultTaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/MonitorExecutorStatusRateLimiter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskFrameworkService.java
Labels: type-bug, enhancement, module-Task framework

#2001 fix(notification): fix some security vulnerabilities
  server/integration-test/src/test/java/com/oceanbase/odc/service/notification/helper/MessageTemplateProcessorTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/OdcConstants.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/NotificationController.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/BeanConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/ChannelPropertyRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/ChannelRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationScheduleConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/constant/EventLabelKeys.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/MessageTemplateProcessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/model/WebhookChannelConfig.java
Labels: module-Notification

#2007 fix(resultset-edit): bad performance when modifing query result set
  server/integration-test/src/test/java/com/oceanbase/odc/service/dml/UpdateGeneratorTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dml/TableDataService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dml/UpdateGenerator.java
Labels: type-bug, priority-high

#2020 fix(sql-execute): add an user config and add concurrent control for session creating
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/BaseConnectionSessionManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dispatch/RequestDispatcher.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/SessionLockRemoveListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/SessionProperties.java
  server/odc-service/src/main/resources/config-meta/user-config-meta.yml
Labels: type-bug, enhancement

#2031 fix(sql-check): avoid npe when virtual column exists
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/BaseRestrictIndexDataTypes.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/BaseRestrictPKDataTypes.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLRestrictAutoIncrementDataTypes.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NoDefaultValueExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/ProhibitedDatatypeExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/RestrictColumnNotNull.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java
Labels: type-bug

#2024 fix(taskframework): cannot preview latest log for dlm
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/TestLogUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/logger/LoggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogBizImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogUtils.java
Labels: type-bug, module-Task framework

#2021 refactor(notification): extract siteUrl cacluation logic into util
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/config/SystemConfigDAOTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigDAO.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/SiteUrlResolver.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java
  server/odc-service/src/main/resources/mapper/SystemConfigDAO.xml
Labels: module-Notification

#2043 fix(schema-plugin): failed to view table's detail on sofa odp
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/ODPOBMySQLSchemaAccessor.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParser.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/utils/DBAccessorUtil.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTableExtension.java
  server/plugins/schema-plugin-odp-sharding-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/odpsharding/obmysql/ODPShardingOBMySQLTableExtension.java
Labels: type-bug

#2011 fix(connection):modify DruidDataSource MaxWait timeout
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java
Labels: type-bug

#2050 fix(db-browser): remove spaces before and after ddl in oracle mode
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
Labels: type-bug, module-Database object

#2051 fix(task): try to upload log file even through the task has no log file
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
Labels: type-bug

#2057 fix(sql-check): fix npe caused by offline statement detection
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLOfflineDdlExists.java
Labels: type-bug

#2063 fix(db-browser): create table statement containing index is not recognized as a create type
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/MysqlModeSqlParserListener.java
Labels: module-sql parser

#2068 fix(partition-plan): wrap the partition identifier when drop ddl generated
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/DBTablePartitionEditor.java
  libs/db-browser/src/test/resources/table/operator/ob/oracle/partition/delete_multi_partition_test_cases.json
  server/integration-test/src/test/java/com/oceanbase/odc/service/partitionplan/PartitionPlanServiceTest.java
  server/plugins/task-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPointTest.java
  server/plugins/task-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/OBOracleAutoPartitionExtensionPointTest.java
Labels: type-bug

#2076 fix(database): failed to create doris database when input charset and collation
  server/plugins/schema-plugin-doris/src/main/java/com/oceanbase/odc/plugin/schema/doris/DorisDatabaseExtension.java
Labels: type-bug

#2077 fix(builtin-snippets): duplicated prefix and wrong column for ob 3.x
  server/odc-service/src/main/resources/builtin-snippet/mysql-snippet.yml
Labels: type-bug

#2080 feat(taskframework): support external log4j configuration file
  script/build_jar.sh
  script/start-job.sh
  script/start-odc.sh
  server/odc-server/pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskApplication.java
Labels: type-bug

#2085 fix(sql-execute): cannot execute SQLs with single-line comments
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/split/SqlCommentProcessor.java
  server/odc-core/src/test/resources/sql/split/comment-processor-mysql-test.sql
  server/odc-core/src/test/resources/sql/split/comment-processor-mysql-verify.yml
Labels: type-bug

#2064 fix(security): add horizontal authentication for service
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/environment/EnvironmentService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigFacadeImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigMetaService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/TestLoginManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/RiskLevelService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/RulesetService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/snippet/BuiltinSnippetService.java
Labels: type-bug

#2052 fix(flow): flow task service node complete time is not correct
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/listener/ServiceTaskExecutingCompleteListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DBStructureComparisonFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DataTransferRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskCallBackApprovalService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/MockDataRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PartitionPlanRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/ShadowtableSyncRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/ApplyDatabaseFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/project/ApplyProjectFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AlterScheduleTask.java
Labels: type-bug

#2099 fix(partition-plan): failed to view partition plan tables when partition is not active
  server/integration-test/src/test/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleService.java
Labels: type-bug

#2088 fix(partition-plan): failed to execute partition ddl when schema or table name is in lower case
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/DBTablePartitionEditor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/mysql/MySQLDBTablePartitionEditor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/oracle/OracleDBTablePartitionEditor.java
  libs/db-browser/src/test/resources/table/operator/ob/mysql/partition/update_multi_partition_test_cases.json
  libs/db-browser/src/test/resources/table/operator/ob/oracle/partition/delete_multi_partition_test_cases.json
  libs/db-browser/src/test/resources/table/operator/ob/oracle/partition/update_multi_partition_test_cases.json
  server/integration-test/src/test/java/com/oceanbase/odc/service/partitionplan/PartitionPlanServiceTest.java
  server/plugins/task-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPointTest.java
  server/plugins/task-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/OBOracleAutoPartitionExtensionPointTest.java
Labels: type-bug

#2078 enhancement: filter out data directory schema while checking the database permission
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/DatabasePermissionInterceptor.java
Labels: enhancement

#2087 fix(shadowtable): it occurs NPE while creating shadow table comparing tasks
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/structurecompare/StructureComparisonTaskEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingService.java
Labels: type-bug

#2107 fix(connect): failed to sync standby cluster's databases
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
Labels: type-bug

#2095 docs: update roadmap of 2024
  README-zh-CN.md
  README.md
Labels: type-docs

#2113 fix(sso): userAccountName allow non String
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/MappingRuleConvert.java
Labels: type-bug

#2114 fix(data-masking): cannot masking result set when using Oracle
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/extractor/OBColumnExtractor.java
Labels: type-bug

#2059 feat(dlm): adapts to the task framework and supports OceanBase Oracle mode
  pom.xml
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/TaskStatus.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/CloudDLMJobStore.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataArchiveJobFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/JobMetaFactoryCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AbstractDlmJobPreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DLMJobParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/JobType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleStatus.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
Labels: type-feature

#2030 fix(taskframework): ip change with docker restart cause jobs process interrupted and status cannot be terminated
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/SilentExecutor.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_12__update_system_config.sql
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/logger/LoggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultTaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/HttpUtil.java
Labels: type-bug, module-Task framework

#2116 fix(structure-comapre): failed to update task status when task fails
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DBStructureComparisonFlowableTask.java
Labels: type-bug

#2117 fix(audit): add audit type and event for structure comparing task
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventAction.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventType.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/AuditEventMetaService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/util/AuditUtils.java
  server/starters/desktop-starter/src/main/java/com/oceanbase/odc/service/audit/DesktopAuditEventHandler.java
Labels: type-bug

#2098 fix(taskframework): add alarm in taskframework
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyExecutorJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: enhancement, module-Task framework

#2121 fix(i18n): missing SIMPLIFIED_CHINESE and TRADITIONAL_CHINESE i18n
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
Labels: type-bug

#2112 refactor(taskframework): refactor job rate limiter for extension
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/PodConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/K8sProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/BaseStartJobRateLimiter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/MonitorExecutorStatusRateLimiter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/MonitorProcessRateLimiter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/ResourceDetectUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/StartJobRateLimiterSupport.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java
Labels: type-refactor, module-Task framework
