Repository oceanbase/odc, pull requests merged in 2024-11, with the labels that each got.

#3780 fix(osc): mdc context may not correct
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/ActionScheduler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/OscActionFsmBase.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/YieldContextAction.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTaskTest.java
Labels: type-bug

#3787 fix(session): use sys datasource may database not exits
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBSysUserDataSourceFactory.java
Labels: type-bug

#3767 feat(schedule): check the validity of the task each time it is scheduled
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-feature

#3788 fix(osc): correct osc session get key to CONSOLE_DATASOURCE
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OscDBAccessorFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/foreignkey/BaseForeignKeyHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/OscActionFsmBase.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/CreateGhostTableAction.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsCreateDataTaskAction.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/ForeignKeyInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockTableInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockUserInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/RenameTableHandlers.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
Labels: type-bug

#3741 security: follow a authenticated schedule id allows you to perform operations on any other schedule tasks
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudResourceConfigurations.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduledTaskLoggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/CloudObjectStorageServiceBuilder.java
Labels: security bug

#3792 fix(monitor): meterKey construct use interface
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MeterKey.java
Labels: type-bug

#3795 fix(alarm): delete duplicate alarm
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
Labels: type-bug

#3791 enhancement: add data source sync history for skipping to sync data sources that were already invalid
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_20__add_connect_connection_sync_history.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionConfigRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionSyncHistoryEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionSyncHistoryRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionSyncHistoryService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DatabaseSyncSchedules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseSyncManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionSyncErrorReason.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionSyncResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncScheduler.java
Labels: enhancement

#3793 fix(external table):get table and external table together without exception
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/TableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/DBSchemaSyncer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/column/AbstractDBColumnSyncer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/object/AbstractDBObjectSyncer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/object/DBExternalTableSyncer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/feature/VersionDiffConfigService.java
Labels: type-bug

#3739 feat(ticket): allow project members to view and owners to update all tickets in the project
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowResponseMapperFactoryTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleControllerHist.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/HookConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceSpecs.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/resourcerole/UserResourceRoleRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowPermissionHelper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceLoggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowInstanceDetailResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/QueryFlowInstanceParams.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleOverviewHist.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/StructureComparisonService.java
Labels: type-feature

#3798 feat(web): session cookie secure default false
  server/odc-server/src/main/resources/data.sql
Labels: type-feature

#3803 fix(scheudle):can't map schedule task parameter
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleTaskMapper.java
Labels: type-bug

#3814 fix(datasource): data source sync failed
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionConfigRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
Labels: type-bug

#3816 fix(datasource): add unit tests for sync data source
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/connection/ConnectionConfigRepositoryTest.java
Labels: type-bug

#3808 feat(dashboard): support dashboard
  server/integration-test/src/test/java/com/oceanbase/odc/service/resourcehistory/ResourceLastAccessServiceTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ResourceType.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/resourcehistory/ResourceLastAccessRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resourcehistory/ResourceLastAccessService.java
Labels: type-feature

#3823 fix(schedule): correct the status when scheduling tasks
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#3822 fix(session): disable kill session/query for logical database session
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
Labels: type-bug

#3815 fix(schedule): customize description generator according to different environments
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/util/DefaultScheduleDescriptionGenerator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/util/ScheduleDescriptionGenerator.java
Labels: type-bug

#3824 fix(session): put killCurrentQuerySupported into session
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/DBSessionResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
Labels: type-bug

#3817 fix(dlm): opt error message when editing the limit configuration
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/LimitMetric.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DlmLimiterService.java
Labels: type-bug

#3807 feat(task): refactor task interface, introduce task runtime component
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/TaskApplicationTest.java
  server/odc-server/pom.xml
  server/odc-server/src/main/java/com/oceanbase/odc/agent/OdcAgent.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/DefaultTaskResultBuilder.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/EmbedServer.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/ExecutorRequestHandler.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/ExitHelper.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskApplication.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskContainer.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskExecutor.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskFactory.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskMonitor.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskReporter.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskRuntimeInfo.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/ThreadPoolTaskExecutor.java
  server/odc-server/src/test/java/com/oceanbase/odc/agent/runtime/EmbedServerTest.java
  server/odc-server/src/test/java/com/oceanbase/odc/agent/runtime/SimpleTask.java
  server/odc-server/src/test/java/com/oceanbase/odc/agent/runtime/TaskApplicationTest.java
  server/odc-server/src/test/java/com/oceanbase/odc/agent/runtime/TaskContainerTest.java
  server/odc-server/src/test/java/com/oceanbase/odc/agent/runtime/TaskMonitorTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/Task.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/TaskContext.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/TaskBase.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/dataarchive/DataArchiveTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/databasechange/DatabaseChangeTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/logicdatabasechange/LogicalDatabaseChangeTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/precheck/PreCheckTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/rollback/RollbackPlanTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/sqlplan/SqlPlanTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/dummy/DummyTask.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/task/executor/task/BaseTaskTest.java
Labels: type-feature

#3831 optimization(datasource): optimize data source sync thread pool config
  server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java
Labels: enhancement

#3829 fix(datasource): datasource sync failed
  server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DatabaseSyncSchedules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionSyncErrorReason.java
Labels: type-bug

#3827 feat(task): remove DefaultTaskResult
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/MapUtils.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/util/MapUtilsTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/DefaultTaskResultBuilder.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/ExecutorRequestHandler.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskMonitor.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/TaskController.java
  server/odc-server/src/test/java/com/oceanbase/odc/agent/runtime/TaskContainerTest.java
  server/odc-server/src/test/java/com/oceanbase/odc/agent/runtime/TaskMonitorTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/RollbackPlanRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/DefaultTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/TaskExecutorClient.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/task/executor/TaskResultTest.java
Labels: type-feature

#3802 feat(external tables): supports syncing external table files
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleBetween410And432SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/postgre/PostgresSchemaAccessor.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBTableController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
  server/plugins/schema-plugin-api/src/main/java/com/oceanbase/odc/plugin/schema/api/TableExtensionPoint.java
  server/plugins/schema-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/schema/mysql/MySQLTableExtension.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLTableExtension.java
  server/plugins/schema-plugin-odp-sharding-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/odpsharding/obmysql/ODPShardingOBMySQLTableExtension.java
  server/plugins/schema-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oracle/OracleTableExtension.java
  server/plugins/schema-plugin-postgres/src/main/java/com/oceanbase/odc/plugin/schema/postgres/PostgresTableExtension.java
Labels: type-feature

#3830 fix(task): add task framework error message
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/ExceptionUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DefaultTaskResultBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/JobTerminateEvent.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/task/executor/task/BaseTaskTest.java
Labels: type-bug

#3833 enhancement(schedule): alarm based on specific error messages
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: enhancement

#3764 feat(sql console rule): sql console adapt sql type of call ,comment on and set session
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/ParserUtil.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/constant/SqlType.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/MysqlModePLParserListener.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/MysqlModeSqlParserListener.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModePLParserListener.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModeParserListener.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModeSqlParserListener.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/PLParserTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/ParserUtilTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/SqlParserTest.java
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/SqlExecuteResult.java
Labels: type-feature

#3834 feat(ErrorCodes): add EditVersionConflict in ResourceType
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
Labels: type-feature

#3835 feat(LimitMetric): add DASHBOARD_COUNT_IN_WORKSPACE/CHART_COUNT_IN_DASHBOARD in LimitMetric
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/LimitMetric.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
Labels: type-feature

#3821 feat(external table): external table support sensitive column
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessorSqlMappers.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/constant/Statements.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/constant/StatementsFiles.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLBetween400And432SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleBetween410And432SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/postgre/PostgresSchemaAccessor.java
  libs/db-browser/src/main/resources/schema/sql/obmysql/obmysql_4_3_2_x.yaml
  libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_3_2_x.yaml
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/DatabaseWithAllColumns.java
Labels: type-feature

#3862 fix(schedule): list datasources with attributes
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
Labels: type-bug

#3863 fix(logicaldatabase): add system config to enabled/disable the logical database feature
  server/odc-server/src/main/resources/data.sql
Labels: type-bug

#3882 feat(logicaldatabase): add missed code for data.sql when merge main to dev/4.3.x
  server/odc-server/src/main/resources/data.sql
Labels: type-build

#3881 feat(sql-execution-plan): add errorCode for intelligent analysis of sql execution plan
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
Labels: type-feature

#3884 builds: merge from main into dev/4.3.x
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/DefaultTaskResultBuilder.java
  server/odc-server/src/test/java/com/oceanbase/odc/agent/runtime/TaskContainerTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/sqlplan/SqlPlanTask.java
Labels: type-build

#3877 feat(regulation): sql check and sql console rules support for Oracle
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/BaseSqlChecker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/RestrictColumnNameCaseFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/RestrictTableNameCaseFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/ColumnCharsetExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/ColumnCollationExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/ColumnNameInBlackList.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/ForeignConstraintExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NoDefaultValueExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NoIndexNameExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NoPrimaryKeyExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NoPrimaryKeyNameExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NoSpecificColumnExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NoValidWhereClause.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NoWhereClauseExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/NotNullColumnWithoutDefaultValue.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleColumnCalculation.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleLeftFuzzyMatch.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleMissingRequiredColumns.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleNoColumnCommentExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleNoNotNullAtInExpression.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleNoTableCommentExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleOfflineDdlExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleRestrictColumnNameCase.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleRestrictIndexDataTypes.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleRestrictPKDataTypes.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleRestrictTableNameCase.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleTooManyAlterStatement.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/PreferLocalOutOfLineIndex.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/ProhibitedDatatypeExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/RestrictColumnNotNull.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/RestrictDropObjectTypes.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/RestrictIndexNaming.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/RestrictPKNaming.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/RestrictUniqueIndexNaming.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SelectStarExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SyntaxErrorExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TableNameInBlackList.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooLongCharLength.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooManyColumnDefinition.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooManyColumnRefInIndex.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooManyColumnRefInPrimaryKey.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooManyInExpression.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooManyOutOfLineIndex.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooManyTableJoin.java
Labels: type-feature

#3891 fix(schedule): schedule can be edited while subtasks are still in progress
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#3892 fix(sql-check): cannot get oracle affect sql rows
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/BaseAffectedRowsExceedLimit.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleAffectedRowsExceedLimit.java
Labels: type-bug

#3901 security: exclude sshd-common from spring-cloud-context
  pom.xml
Labels: security bug

#3898 feat(session): support Oracle kill session
  server/integration-test/src/test/java/com/oceanbase/odc/service/session/ConnectConsoleServiceTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/SessionOperations.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/TestSessionOperations.java
  server/odc-migrate/src/main/resources/migrate/common/R_2_0_0__initialize_version_diff_config.sql
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ConnectSessionController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DBSessionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/KillResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/DBSessionManageFacade.java
  server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLSessionExtension.java
  server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleSessionExtension.java
  server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleSessionExtension.java
Labels: type-feature

#3894 fix(pl-edit): procedure name in drop procedure statements are recognized as the table name in DBSchemaExtractor
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
  server/odc-service/src/test/resources/session/test_db_schema_extractor.yaml
Labels: type-bug

#3905 feat(subpartition): finish sub partitions
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParser.java
  server/plugins/schema-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParserTest.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java
  server/plugins/schema-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParserTest.java
  server/plugins/schema-plugin-ob-oracle/src/test/resources/parser/drop.sql
  server/plugins/schema-plugin-ob-oracle/src/test/resources/parser/testGetTableByParser.sql
Labels: module-Database object

#3909 fix(taskframework): cherry-pick the bug fix from obcloud_202409bp
  pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/result/DLMResultProcessor.java
Labels: type-bug
