Repository oceanbase/odc, pull requests merged in 2024-08, with the labels that each got.

#3088 fix(task): show history log when odc upgrade use same mount path but with a new meta db
  server/odc-server/src/main/resources/log4j2-task.xml
Labels: type-bug

#3098 fix(schema): show constraint's on delete rule correctly by parser
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java
  server/plugins/schema-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParserTest.java
Labels: type-bug

#3101 fix(permission): 1) users could export the whole database even if they don't have database export permissions 2) SQL contains function call will be wrongly intercepted
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
  server/odc-service/src/test/resources/session/test_db_schema_extractor.yaml
Labels: type-bug

#3100 fix(dlm): sync table structure failed
  server/integration-test/src/test/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizerTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleTaskRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
Labels: type-bug

#3109 fix(permission): users cannot call function in oracle mode
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
  server/odc-service/src/test/resources/session/test_db_schema_extractor.yaml
Labels: type-bug

#3089 feat(worksheet): add controller define for project files
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/WorksheetController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacade.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/BatchOperateWorksheetsResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/BatchUploadWorksheetsReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/GenerateWorksheetUploadUrlReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/GenerateWorksheetUploadUrlResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/ListWorksheetsReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/UpdateWorksheetReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/WorksheetLocation.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/WorksheetMetaResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/WorksheetResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/WorksheetType.java
Labels: type-feature

#3123 feat(osc):enhance osc, let swap table reentrant
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/BaseOscTestEnv.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeOBMysqlSwapTableTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableAction.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/ProjectStepResultChecker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/DefaultRenameTableInvoker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/SwapTableUtil.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/oscfms/OscTestUtil.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableActionTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/SwapTableUtilTest.java
Labels: type-feature

#3130 refactor(web): remove unnecessary bean
  server/odc-service/src/main/java/com/oceanbase/odc/config/RestTemplateConfig.java
Labels: type-refactor

#3119 feat(objectstorage): add pure object storage without the operating of object storage metadata and predefined objectName
  .gitignore
  server/integration-test/pom.xml
  server/integration-test/src/test/java/com/oceanbase/odc/ITConfigurations.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/BucketOperatorTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/LocalFileOperatorTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/ObjectBlockOperatorTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/client/OSSCloudObjectStorageClientTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/AWSSecurityTokenServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/AbstractCloudObjectStorageServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/AlibabaCloudSecurityTokenServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/COSObjectStorageServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorageClientTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorageUtilTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/OBSObjectStorageServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/OSSObjectStorageServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/S3ObjectStorageServiceIT.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/config/ObjectStorageConfigurationTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/resource/aliyun/AlibabaCloudClientTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/cloud/resource/aws/AmazonCloudClientTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/CloudObjectStorageClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/LocalObjectStorageClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/ObjectStorageClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/ObjectStorageClientConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorageService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AlibabaCloudClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AmazonCloudClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/ObjectMetadata.java
Labels: type-feature

#3160 fix(logicaldatabase): index out of bound when there only exists one table in the database
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableService.java
Labels: type-bug

#3186 builds: install pty4j manually
  .github/workflows/build_artifact.yaml
  .github/workflows/build_daily.yaml
  .github/workflows/build_dev.yaml
  .github/workflows/build_release.yaml
  script/functions.sh
  server/odc-service/pom.xml
Labels: type-build

#3176 feat(logicaldatabase): rewriting the logical sql into the physical sql
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLAlterTableFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLCreateTableFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLDropIndexFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLDropTableFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLFromReferenceFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLTableListFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleAlterTableFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleCreateTableFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleDropIndexFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleDropTableFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/alter/table/AlterTable.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/createtable/CreateTable.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/dropindex/DropIndex.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/droptable/DropTable.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/droptable/TableList.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/OBMySQLParserTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/OBOracleSQLParserTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLAlterTableFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLCreateTableFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLDropIndexFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLDropTableFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLTableListFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/OracleAlterTableFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/OracleCreateTableFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/OracleDropIndexFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/OracleDropTableFactoryTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/parser/AbstractSyntaxTreeTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/rewrite/RelationFactorRewriter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/rewrite/RewriteContext.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/rewrite/RewriteResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/rewrite/SqlRewriter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLOfflineDdlExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleOfflineDdlExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/RestrictDropObjectTypes.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/connection/logicaldatabase/core/rewrite/RelationFactorRewriterTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java
Labels: type-feature

#3196 build: upgrade ob-sql-parser to 1.3.1
  libs/db-browser/pom.xml
  libs/ob-sql-parser/pom.xml
  pom.xml
Labels: type-build

#3201 fix(web): fix tomcat threads config
  server/odc-server/src/main/resources/config/application.yml
Labels: type-bug

#3203 fix(connect): make odc connect to the obcloud instance
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/model/ConnectionConfigTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
Labels: type-bug

#3202 fix(osc): compatible with cloud odc code, fix ScheduleTaskParameter deserialize…
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/OscActionFsm.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/OscActionFsmBase.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsCreateDataTaskAction.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleTaskMapper.java
Labels: type-bug

#3205 merge from dev/4.3.1 into main
  server/odc-server/src/main/resources/config/application.yml
Labels: type-build

#3209 refactor(migrate): supports load sql script from custom jar file
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/ResourceUtils.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/resource/ResourceManager.java
Labels: type-refactor
