Repository oceanbase/odc, pull requests merged in 2024-12, with the labels that each got.

#3934 fix(clinetmode): can't start MAC client mode
  server/odc-server/src/main/resources/config/application-clientMode.yml
Labels: type-bug

#3947 fix(osc):add version whitelist to enable lock table feature
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/configuration/OnlineSchemaChangeProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableAction.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/DefaultRenameTableInvoker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockRenameTableFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockTableSupportDecider.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/OscDBUserUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableActionTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/LockTableSupportDeciderTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/OscDBUserUtilTest.java
Labels: type-bug

#3897 feat(ConnectSession): add param createConnectionSessionSupplier in nullSafeGet, add param maxConcurrentTaskCount in createPhysicalConnectionSession
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
Labels: type-feature

#3952 fix(task): rollback DestroyExecutorJob to do destroy job action
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/StdJobScheduler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyExecutorJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#3937 refactor(schedule): fill attribute at scheduleMapper
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
Labels: type-refactor

#3955 fix(task): add index to resource_resource table
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_1__alter_resource_resource_add_index.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/resource/ResourceEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#3961 fix(session): add svrIp in session list
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBSession.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/mysql/OBMySQLNoLessThan400StatsAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/oracle/OBOracleNoLessThan400StatsAccessor.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/model/OdcDBSession.java
Labels: type-bug

#3783 feat(sso): support saml integration
  pom.xml
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_1__alter_integration.sql
  server/odc-server/pom.xml
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/SSOController.java
  server/odc-service/pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/util/UrlUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/IntegrationConfigurationProcessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/IntegrationConfigurationProcessorDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/IntegrationService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/SSOCredential.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/Encryption.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/Oauth2Parameter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/SSOIntegrationConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/SSOEventHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/SSOStateManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/TestLoginManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/saml/AddableRelyingPartyRegistrationRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/saml/SamlCredentialManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/saml/SamlParameter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/saml/SamlRegistrationConfigHelper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/util/EncryptionUtil.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/config/WebSecurityConfiguration.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/MappingRuleConvert.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/oauth2/CustomOAuth2AuthorizationRequestResolver.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/oauth2/OAuth2SecurityConfigureHelper.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/oauth2/OAuth2TestLoginAuthenticationFilter.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/oauth2/OAuth2UserServiceImpl.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/oauth2/OidcUserServiceImpl.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/saml/CustomSamlProvider.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/saml/DefaultSamlUserService.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/saml/SamlSecurityConfigureHelper.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/saml/SamlTestLoginAuthenticationFilter.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/info/WebInfoAdapter.java
Labels: type-feature

#3966 fix(DefaultSqlExecuteTaskManager): npe in DefaultSqlExecuteTaskManager
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/task/DefaultSqlExecuteTaskManager.java
Labels: type-bug

#3974 fix(migration script): fix migration script version number duplicate
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_2__alter_resource_resource_add_index.sql
Labels: type-bug

#3946 feat(permission): add view permission control
  server/integration-test/src/test/java/com/oceanbase/odc/service/db/TableServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dbobject/DBObjectRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/TableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/ApplyTablePermissionPreprocessor.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestDBConfigurations.java
Labels: type-feature

#3980 feat(ObjectStorage): add copyObject in ObjectStorageClient
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/client/OSSCloudObjectStorageClientTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/CloudObjectStorageClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/LocalObjectStorageClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/ObjectStorageClient.java
Labels: type-feature

#3979 fix(session): add non support kill version
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/VersionUtils.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/util/VersionUtilsTest.java
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/feature/VersionDiffConfigService.java
Labels: type-bug

#3991 fix(actuator): diasble actuator by default
  server/odc-server/src/main/resources/config/application.yml
Labels: type-bug

#4003 fix(data-archive): table not exist
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
Labels: type-bug

#4001 feat(common): reduce log of JsonUtils
  server/odc-common/src/main/java/com/oceanbase/odc/common/json/JsonUtils.java
Labels: type-feature

#3993 feat(session): SQL console connection keep alive
  server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSource.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSourceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/OscActionFsmBase.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/precheck/PreCheckTask.java
Labels: type-feature

#3938 feat(pl debug): pl debugging adapt odp directional routing
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionConstants.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionUtil.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/OBUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/util/ConnectionInfoUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/model/PLDebugODPSpecifiedRoute.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/operator/DBPLOperators.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/operator/GetPLErrorCallBack.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/operator/OraclePLOperator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggeeSession.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggerSession.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/PLDebugSession.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/util/CallProcedureCallBack.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/util/OBOracleCallFunctionCallBack.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/util/PLDebugTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/util/PLUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionFactory.java
Labels: type-feature

#3820 feat(permission): support for global project roles
  server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/iam/ResourceRoleServiceTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/DefaultLoginSecurityManager.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/interceptor/MethodAuthorizedInterceptor.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ComposedPermission.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/PermissionProvider.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/PrivateConnectionPermission.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ProjectPermission.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/authority/ComposedPermissionTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/authority/tool/TestPermissionProvider.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_1__iam_permission.yaml
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_2__iam_role.yaml
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_3__iam_role_permission.yaml
  server/odc-service/src/main/java/com/oceanbase/odc/config/DefaultAuthConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/collaboration/ProjectRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/PermissionRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/RoleEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/UserRoleRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveRuleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/GlobalResourceRoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/PermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ProjectPermissionValidator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleBasedPermissionExtractor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserPermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/BaseAuthorizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/ComposedAuthorizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/DefaultAuthorizationFacade.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/DefaultAuthorizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/DefaultPermissionProvider.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/ResourceRoleAuthorizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/UserGlobalResourceRole.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/UserResourceRole.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/util/GlobalResourceRoleUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/DatabasePermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/TablePermissionService.java
Labels: type-feature

#4041 fix(migrate): startup failed due to the duplicate version number of migrate scripts
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_3__iam_permission.yaml
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_4__iam_role.yaml
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_5__iam_role_permission.yaml
Labels: type-bug

#4046 fix(permission):time is missing when initiating apply database task again
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/ApplyDatabaseParameter.java
Labels: type-bug, module-Database Permission

#4056 merge dev/4.3.2 into main
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBSession.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/mysql/OBMySQLNoLessThan400StatsAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/oracle/OBOracleNoLessThan400StatsAccessor.java
  pom.xml
  server/odc-common/src/main/java/com/oceanbase/odc/common/json/JsonUtils.java
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/VersionUtils.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/util/VersionUtilsTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/model/OdcDBSession.java
  server/odc-server/src/main/resources/config/application-clientMode.yml
  server/odc-server/src/main/resources/config/application.yml
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/feature/VersionDiffConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/configuration/OnlineSchemaChangeProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableAction.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/DefaultRenameTableInvoker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockRenameTableFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/LockTableSupportDecider.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/OscDBUserUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/result/DLMResultProcessor.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableActionTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/LockTableSupportDeciderTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/rename/OscDBUserUtilTest.java
Labels: type-build

#4073 fix(osc): remove distinct from osc query user sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OscOBMySqlAccessor.java
Labels: type-bug

#4075 feat(schedule): opt offset calculator
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/utils/DataArchiveConditionUtil.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/dlm/utils/DataArchiveConditionUtilTest.java
Labels: type-feature

#4070 fix(changelog): incorrect detail in the change log
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#4090 fix(flow):view export function can be initiated without permission
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug

#4089 fix(project): archiving projects will fail because of wrong check of tickets references
  server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleStatus.java
Labels: type-bug

#4067 fix(approval): approval is not needed in individual organizations
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#4094 fix(saml): saml may blocked tomcat thread
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/saml/SamlRegistrationConfigHelper.java
Labels: type-bug

#4095 fix(task): correct region key name for resourceID
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ResourceIDUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/dummy/LocalMockK8sJobClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobPropertiesUtils.java
Labels: type-bug

#4088 fix(db): cannot replace original pl name where editing pl
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/StringUtils.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/util/StringUtilsTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLModifyHelper.java
Labels: type-bug

#4084 fix(dbbrowser): cant get correct ddl of procedure
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/PLParserTest.java
Labels: type-bug

#4096 fix(flow): add currentUserResourceRole in flow APIs
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowInstanceDetailResp.java
Labels: type-bug

#4087 fix(execution-plan): avoid invalid number
  server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/diagnose/PlanGraphBuilder.java
Labels: type-bug

#4091 fix(notification): fail to enqueue schedule event
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java
Labels: type-bug

#4105 fix(migrate): newly added sql check rules in 4.3.2 will not be migrated successfully
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/R4237DefaultRuleApplyingMigrate.java
Labels: type-bug

#4104 fix(dlm): upgrade dlm sdk version to 1.1.6.bp3
  pom.xml
Labels: type-bug

#4106 fix(integration): external approval integration will cause NPE if hyperlinkExpression is null
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
Labels: type-bug

#4109 fix(integration): it doesn't sync internal schemas in the project in the bastion mode
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncTaskManager.java
Labels: type-bug

#4112 fix(session):drop pl require database change permission
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
  server/odc-service/src/test/resources/session/test_db_schema_extractor.yaml
Labels: type-bug

#4108 fix(db): The method of determining whether opening the global client session is incorrect
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
Labels: type-bug
