Repository oceanbase/odc, pull requests merged in 2024-01, with the labels that each got.

#1327 feat(dlm):supports sharding using unique indexes
  pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AbstractDlmJobPreprocessor.java
Labels: type-feature

#1362 docs: update ob-sql-parser's document
  libs/ob-sql-parser/README.md
Labels: type-docs

#1364 feat(structure-comapre): implement database object structure comparison
  libs/db-browser/pom.xml
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/DBTableEditor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/DBTablePartitionEditor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/mysql/MySQLTableEditor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/oracle/OracleTableEditor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTableColumn.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTableConstraint.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTableIndex.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoGreaterThan5740SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLBetween2277And3XSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLNoGreaterThan1479SchemaAccessor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/editor/MySQLTableEditorTest.java
  pom.xml
  server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/DefaultDBStructureComparatorTest.java
  server/integration-test/src/test/resources/structurecompare/source_drop.sql
  server/integration-test/src/test/resources/structurecompare/source_schema_ddl.sql
  server/integration-test/src/test/resources/structurecompare/target_drop.sql
  server/integration-test/src/test/resources/structurecompare/target_schema_ddl.sql
  server/odc-service/pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/browser/DBSchemaAccessors.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/DBStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/DefaultDBStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/AbstractDBObjectStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBObjectStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableColumnStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableConstraintStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableIndexStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTablePartitionStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/model/ComparisonResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/model/DBObjectComparisonResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/model/DBStructureComparisonConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/util/StructureCompareUtil.java
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestDBConfiguration.java
Labels: type-feature

#1366 feat(database-permission): adapt permission framework
  server/integration-test/src/test/java/com/oceanbase/odc/AuthorityTestEnv.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/iam/PermissionRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/iam/UserPermissionRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/iam/PermissionServiceTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/DatabasePermission.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/authority/DatabasePermissionTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/authority/tool/TestPermissionProvider.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_1__alter_iam_permission.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/PermissionEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/PermissionRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/PermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/RoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserPermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/DefaultAuthorizationFacade.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/DefaultPermissionProvider.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/lab/ResourceService.java
Labels: type-feature, priority-medium, module-Database Permission

#1342 feat(structure-compare): structural comparison task interface layer code implementation
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowResponseMapperFactoryTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/TaskType.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/SchemaSyncController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/CreateFlowInstanceReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowInstanceDetailResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DBStructureComparisonFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/mapper/OdcRuntimeDelegateMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DBObjectStructureComparisonResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DBStructureComparisonParameter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DBStructureComparisonResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DBStructureComparisonTaskResult.java
Labels: type-feature

#1357 fix(osc): osc task don't show manual swap table name when full migrate is completed
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ScheduleCheckOmsProjectValve.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/rename/SwapTableUtil.java
Labels: type-bug, priority-high, module-Online schema change

#1376 fix(dlm): the task log file does not exist
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
Labels: type-bug

#1374 feat(partition-plan): add api and storage layer
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/partitionplan/PartitionPlanRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/partitionplan/PartitionPlanTablePartitionKeyRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/partitionplan/PartitionPlanTableRepositoryTest.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_4__alter_partitionplan.sql
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ConnectSessionController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBTableController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/PartitionPlanController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/partitionplan/PartitionPlanEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/partitionplan/PartitionPlanRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/partitionplan/PartitionPlanTableEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/partitionplan/PartitionPlanTablePartitionKeyEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/partitionplan/PartitionPlanTablePartitionKeyRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/partitionplan/PartitionPlanTableRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/PartitionPlanConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/PartitionPlanDBTable.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/PartitionPlanDBTablePartition.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/PartitionPlanKeyConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/PartitionPlanPreViewResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/PartitionPlanStrategy.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/PartitionPlanTableConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/PartitionPlanVariable.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/model/PartitionPlanVariableKey.java
  server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/partitionplan/datatype/PartitionPlanCharType.java
  server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/partitionplan/datatype/PartitionPlanCustomType.java
  server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/partitionplan/datatype/PartitionPlanDataType.java
  server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/partitionplan/datatype/PartitionPlanNumberType.java
  server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/partitionplan/datatype/PartitionPlanTimeType.java
Labels: type-feature

#1396 feat(dlm):upgrade SDK to 1.0.10
  pom.xml
Labels: enhancement

#1383 fix(flow):improve list API rt
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_5__add_flow_instance_index.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
Labels: type-bug

#1345 fix(mock-data): failed to upload file to oss
  pom.xml
Labels: type-bug, module-Mock data

#1401 fix(db-browser): fix the visualization of mysql table structure design and supports strings enclosed in single quotes
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/mysql/MySQLColumnEditor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/editor/MySQLTableEditorTest.java
  libs/db-browser/src/test/resources/table/operator/mysql/column/create_column_definition_test_cases.json
Labels: type-bug

#1411 fix(sql-execution): precision loss when displaying datetime type
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/MySQLDatetimeMapper.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/tool/TimestampCellData.java
Labels: type-bug, module-sql execution

#1405 fix(osc): exists horizontal overstep access data permission when swap table manual
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeParameters.java
Labels: type-bug, module-Online schema change

#1406 fix(sso): frontend-backend integration testing fix
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/CustomAuthenticationFailureHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/info/InfoAdapter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/info/OdcInfo.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/info/OdcInfoService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/LdapContextHolder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/SSOTestInfo.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/TestLoginManager.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/ldap/LdapAbstractTestLoginAuthenticationFilter.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/ldap/LdapSecurityConfigureHelper.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/info/WebInfoAdapter.java
Labels: type-bug

#1420 feat(deployment): add datetime output for ob-odc-web.std.log
  script/functions.sh
  script/start-odc.sh
  server/odc-common/src/main/java/com/oceanbase/odc/common/security/SensitiveDataUtils.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/security/SensitiveDataUtilsTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java
Labels: type-feature

#1438 fix(dlm): the data cleaning task scheduling failed after editing the rate limit configuration
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/dlm/DlmLimiterConfigRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/dlm/RateLimitConfigurationServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/DlmLimiterConfigRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DlmLimiterService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/RateLimitConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AbstractDlmJobPreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleDetailResp.java
Labels: type-bug

#1459 feat(data-transfer): not compress export output in client mode
  server/integration-test/src/test/java/com/oceanbase/odc/service/datatransfer/DataTransferServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DefaultDataTransferAdapter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/task/DataTransferTask.java
Labels: type-feature

#1458 fix(database-permission): failed to verify database permission in personal space
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/DatabasePermissionHelper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
Labels: type-bug, priority-medium, module-Database Permission

#1427 feat(data-transfer): upgrade ob-loader-dumper to 4.2.8-RELEASE
  pom.xml
  server/integration-test/src/test/java/com/oceanbase/odc/service/regulation/ruleset/RuleServiceTest.java
  server/odc-server/src/main/resources/config/application-clientMode.yml
  server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/DataTransferService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/OBMySQLDataTransferExtension.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/DumpParameterFactory.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/LoadParameterFactory.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/task/BaseOceanBaseTransferJob.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/task/OceanBaseExportJob.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/task/OceanBaseImportJob.java
  server/plugins/task-plugin-ob-mysql/src/main/resources/session.config.json
Labels: type-feature, module-Data generation and migration

#1467 fix(database-permission): User holds no db permission in personal space
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/DatabasePermissionHelper.java
Labels: type-bug, priority-medium, module-Database Permission

#1474 fix(sql-execute): executing anonymous block causes NPE in the team space
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModePLParserListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java
Labels: type-bug

#1437 feat(database-change): database change task adapt streaming read sql file
  .github/workflows/build_image_for_test.yaml
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/BaseJobTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/TaskApplicationTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DatabaseChangeTask.java
Labels: type-feature, priority-medium, module-Task framework

#1470 fix(pre-check): load uploaded files failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
Labels: type-bug, priority-medium

#1479 fix(flow): NPE when creating a ticket without connection information
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug, priority-high

#1478 fix(db-browser): failed to list tables when ob's version is no greater than 2.2.30
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleLessThan400SchemaAccessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/browser/DBSchemaAccessors.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/browser/DBSchemaAccessors.java
Labels: type-bug, priority-high

#1488 fix(table): query table data with no column comments
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
Labels: type-bug
