Repository oceanbase/odc, pull requests merged in 2024-10, with the labels that each got.

#3618 feat(i18n): change message of workspace and worksheet
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
Labels: type-feature

#3617 fix(sql-check): a specific sql will lead to npe (#3611)
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLOfflineDdlExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleOfflineDdlExists.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
Labels: type-bug

#3623 feat(workspace): move WorkspaceDataSourceAdapter from odc-workspace to odc-service
  server/odc-service/src/main/java/com/oceanbase/odc/service/workspace/adapter/WorkspaceDataSourceAdapter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/workspace/model/CreateWorkspaceReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/workspace/model/UpdateWorkspaceInstanceAccountReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/workspace/model/UpdateWorkspaceReq.java
Labels: type-feature

#3624 doc: update 4.3.2 release date in changelog
  CHANGELOG-zh-CN.md
  CHANGELOG.md
Labels: type-docs

#3633 feat(objectstorage): add generatePresignedUrlWithCustomFileName
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/client/OSSCloudObjectStorageClientTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/CloudObjectStorageClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/LocalObjectStorageClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/client/ObjectStorageClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorage.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorageService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AlibabaCloudClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AmazonCloudClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/NullCloudClient.java
Labels: type-feature

#3635 feat(resourcehistory): add batchAdd in ResourceLastAccessService
  server/integration-test/src/test/java/com/oceanbase/odc/service/resourcehistory/ResourceLastAccessServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/resourcehistory/ResourceLastAccessRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resourcehistory/ResourceLastAccessService.java
Labels: type-feature

#3650 refator(schedule): add schedule task full log download url to OrganizationAuthenticationInterceptor whiteList
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/OrganizationAuthenticationInterceptor.java
Labels: type-refactor

#3643 feat(authentication): add currentProjectId in AuthenticationFacade
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/AuthenticationFacade.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/DefaultAuthenticationFacade.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/WebAuthenticationFacade.java
Labels: type-feature

#3666 fix(approval): default no approval in obcloud
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DefaultApprovalFlowClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/NoApprovalFlowClient.java
Labels: type-bug

#3322 feat(monitor): add prometheus actuator
  pom.xml
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/SingleConnectionDataSource.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/event/ConnectionResetEvent.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/datasource/event/GetConnectionFailedEvent.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/flow/util/FlowConstants.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/DefaultConnectionSessionManager.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/LogicalConnectionSession.java
  server/odc-server/pom.xml
  server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v1/HeartbeatController.java
  server/odc-server/src/main/resources/META-INF/spring.factories
  server/odc-server/src/main/resources/config/application.yml
  server/odc-service/pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseRuntimeFlowableDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskSubmitter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/InMemoryMeterManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/ManagementConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MeterKey.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MeterManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MeterName.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MonitorAutoConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MonitorConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MonitorProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/datasource/GetConnectionFailedEventListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/service/MemUnitType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/service/MetaInfo.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/service/MetaMemory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/service/MonitorService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/session/ConnectionSessionMonitorListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/session/SessionMetrics.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/task/job/JobMonitorListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/task/schdule/ScheduleMetrics.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/executor/AbstractQuartzJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DefaultConnectSessionFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StateRouteAspect.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/StdJobScheduler.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/config/WebSecurityConfiguration.java
Labels: type-feature

#3669 fix(taskframework): cannot release pod if OSS initialization fails
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogBizImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java
Labels: type-bug

#3667 fix(sync-database): modify syncDatabaseTaskExecutor QueueCapacity to Integer.MAX_VALUE
  server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java
Labels: type-bug

#3664 fix(datasource): missing tenantName and instanceName in data source details
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
Labels: type-bug

#3671 fix(dlm): the status is incorrect if creating the pod timeout
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
Labels: type-bug

#3680 fix(errorcodes): add ErrorCodes: WorkspaceDatabaseUserTypeMustBeAdmin
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
Labels: type-feature

#3677 fix(dlm): custom sharding strategy being ineffective
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/DataArchivePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/DataDeletePreprocessor.java
Labels: type-bug

#3687 fix(pl): PL debug will fail when there are databases with the same name under the data source (one exists and one does not)
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLService.java
Labels: type-bug

#3695 fix(collaboration): databases' environment have not been updated after the datasource's environment changed
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
Labels: type-bug

#3694 fix(rule): Executing SQLs occurs NPE when the database belongs to a customized environment after upgrading to 4.3.2
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/R4237DefaultRuleApplyingMigrate.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V43213CustomizedRuleMigrate.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/regulation/ruleset/RulesetRepository.java
Labels: type-bug

#3689 fix(scheduleTask): correct status on task restart
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
Labels: type-bug

#3702 fix(dlm): cherry pick bug fix from 4.3.2bp to 24v4
  pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
Labels: type-bug

#3712 fix(datasource): no return DSS datasource id
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
Labels: type-bug

#3714 fix(errorCode): add error code for cloud service error
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
Labels: type-bug

#3686 feat(ob-sql-parser): adapt for OceanBase 4.3.3
  libs/db-browser/pom.xml
  libs/ob-sql-parser/pom.xml
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLCreateIndexFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLDataTypeFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLExpressionFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLTableElementFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleExpressionFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/common/mysql/ArrayType.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/common/mysql/VectorType.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/createindex/CreateIndex.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/createtable/OutOfLineIndex.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/expression/ArrayExpression.java
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBLexer.g4
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBParser.g4
  libs/ob-sql-parser/src/main/resources/oboracle/sql/OBLexer.g4
  libs/ob-sql-parser/src/main/resources/oboracle/sql/OBParser.g4
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLCreateIndexFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLCreateTableFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLDataTypeFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLExpressionFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLInsertFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLSelectFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLTableElementFactoryTest.java
  pom.xml
Labels: type-feature

#3716 fix(task-framework): starting the job twice
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#3709 fix(schedule): fail to filter by tenantId and clusterId
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/ExecutorRequestHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java
Labels: type-bug

#3721 fix(task-framework): check job status before cancel
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java
Labels: type-bug, security bug

#3731 fix(global-search): failed to sync database which get 'PENDING' status and 'object_last_sync_time' is null
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/connection/DatabaseRepositoryTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/TableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/GlobalSearchProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/column/AbstractDBColumnSyncer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/object/AbstractDBObjectSyncer.java
Labels: type-bug

#3734 fix(taskframework): abnormal status caused by concurrent updates
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/DLMResultProcessor.java
Labels: type-bug

#3740 refactor(alarm): adjust the structure of alarm message
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmUtils.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/StdJobScheduler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyExecutorJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-refactor

#3727 refactor(monitor): refactor MeterName to interface and exclude repository metrics
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskSubmitter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/DefaultMeterName.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/InMemoryMeterManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MeterKey.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MeterName.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/MonitorConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/datasource/GetConnectionFailedEventListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/session/ConnectionSessionMonitorListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/session/SessionMetrics.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/task/job/JobMonitorListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/monitor/task/schdule/ScheduleMetrics.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/executor/AbstractQuartzJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StateRouteAspect.java
Labels: type-refactor

#3751 fix(session): session status typo
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/DBSessionResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
Labels: type-bug

#3755 feat(workflow): add a new resource type for workflow cluster
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ResourceType.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sConfigMapStatusDfa.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sDeploymentStatusDfa.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sPodStatusDfa.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sServiceStatusDfa.java
Labels: type-feature

#3661 feat(pl): support editing pl sql for ob mysql
  server/integration-test/src/test/java/com/oceanbase/odc/service/db/DBPLModifyHelperTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBPLController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLModifyHelper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/model/EditPLReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/model/EditPLResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/SqlAsyncExecuteResp.java
Labels: module-Database object
