Repository oceanbase/odc, pull requests merged in 2024-07, with the labels that each got.

#2858 enhancement(migrate): delete uesless yaml/sql file
  server/odc-migrate/src/main/resources/migrate/common/V_3_4_0_12__add_data_masking.sql
  server/odc-migrate/src/main/resources/migrate/common/V_3_4_0_13__data_masking_rule.yaml
  server/odc-migrate/src/main/resources/migrate/common/V_3_4_0_14__data_masking_rule_segment.yaml
  server/odc-migrate/src/main/resources/migrate/common/V_3_4_0_2__iam_permission.yaml
  server/odc-migrate/src/main/resources/migrate/rbac/V_3_4_0_3__iam_role_permission.yaml
Labels: enhancement

#2862 fix(auth): access denied for current project interface
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/OrganizationAuthenticationInterceptor.java
Labels: type-bug, priority-high

#2848 fix(data viewing): get result-set timeout
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
Labels: type-bug, module-Data viewing and editing

#2873 fix(ob-sql-parser): failed to recognize interval expression in ob-oracle mode
  libs/ob-sql-parser/src/main/resources/oboracle/sql/OBLexer.g4
Labels: type-bug

#2863 fix(audit): client ip length more langer then audit column client_ip_address
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/NotificationChannelRelationEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/AuditEventAspect.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/util/AuditUtils.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/audit/util/AuditUtilsTest.java
Labels: type-bug

#2874 fix(i18n): fix i18n docs encoding error
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
Labels: type-bug, type-docs

#2798 fix(flow): failed to startup a ticket
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/MockDataRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
Labels: type-bug

#2878 feat(util): enhance duplicated migrator validation, output detail scripts info
  server/odc-core/src/main/java/com/oceanbase/odc/core/migrate/Migrates.java
Labels: enhancement

#2883 fix(migrate): fix login process resource load faild
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/IndividualOrganizationMigrator.java
Labels: type-bug

#2872 fix(sql): the sql of modifying session parameter in oracle is error
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBVariablesService.java
  server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/SessionExtensionPoint.java
  server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLSessionExtension.java
  server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleSessionExtension.java
  server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleSessionExtension.java
Labels: type-bug

#2850 fix(mock data): failed to cancel the mock data task
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/MockDataRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MockDataTaskResult.java
Labels: type-bug, module-Mock data

#2927 fix(alarm): condition not found
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/alarm/DefaultScheduleAlarmClient.java
Labels: type-bug

#2931 refactor: change the CODEOWNERS
  .github/CODEOWNERS
Labels: type-refactor

#2937 fix(dlm): start job failed
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/schedule/LatestTaskMappingRepositoryTest.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_0_8__add_schedule_change_log.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/DlmTableUnitRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/LatestTaskMappingEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/LatestTaskMappingRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/DLMResultProcessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobPropertiesUtils.java
Labels: type-bug

#2930 fix(pl-debug): avoid npe during the pl debugging
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/PLDebugSession.java
Labels: type-bug

#2936 fix(import): add template api and supports mysql, oracle and doris datasource importing
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/FieldName.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataSourceController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/IamController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionBatchImportPreviewer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/OrganizationAuthenticationInterceptor.java
  server/odc-service/src/main/resources/template/en-us/datasource_template.xlsx
  server/odc-service/src/main/resources/template/en-us/user_template.xlsx
  server/odc-service/src/main/resources/template/zh-cn/datasource_template.xlsx
  server/odc-service/src/main/resources/template/zh-cn/user_template.xlsx
  server/odc-service/src/main/resources/template/zh-tw/datasource_template.xlsx
  server/odc-service/src/main/resources/template/zh-tw/user_template.xlsx
Labels: type-bug

#2895 feat(project): add built-in project for user
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/IndividualOrganizationMigrator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserPermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/CustomAuthenticationSuccessHandler.java
Labels: type-feature

#2953 fix(statefulRoute): fix list column can't reach
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v1/DBTableColumnController.java
Labels: type-bug

#2954 fix(cloud): validate several parameters
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/CreateScheduleReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleTaskDetailResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java
Labels: type-bug

#2935 fix(statefulRoute): failed to list built-in snippets
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/BuiltinSnippetController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/RouteHealthManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StateRouteAspect.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/model/RouteInfo.java
Labels: type-bug

#2961 fix(task-framework): ignore location validation and update task status after refresh
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DlmLimiterService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorageService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/DLMResultProcessor.java
Labels: type-bug

#2960 refactor(statefulRoute): generalization plDebugsession to UUID stateId
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/PLDebugController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/PLDebugService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/model/PLDebugSessionId.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulUuidStateIdGenerator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulUuidStateIdManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/model/StateName.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/model/StatefulUuidStateId.java
Labels: type-refactor

#2964 fix(web): modify tomcat keepAliveTimeout to 70 seconds
  server/odc-server/src/main/resources/config/application.yml
Labels: type-bug

#2967 fix(connect): failed to connect to AP instance
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstanceType.java
Labels: type-bug

#2908 fix(osc): the online schema change blocked when rate limiter modified before swap table action
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ScheduleCheckOmsProjectValve.java
Labels: type-bug

#2966 refactor(statefulRoute): pick 43x stateful route bugfix
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v1/DBTableColumnController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/BuiltinSnippetController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/PLDebugController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/PLDebugService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/model/PLDebugSessionId.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/RouteHealthManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StateRouteAspect.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulUuidStateIdGenerator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulUuidStateIdManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/model/RouteInfo.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/model/StateName.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/model/StatefulUuidStateId.java
Labels: type-bug

#2975 fix(stateful): remove wrong condition
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulUuidStateIdGenerator.java
Labels: type-bug

#2976 fix(stateful): remove wrong generator conditional load
  server/odc-service/src/main/java/com/oceanbase/odc/service/state/StatefulUuidStateIdGenerator.java
Labels: type-bug

#2977 fix(schedule): parameters missing in changelog
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/QuartzJobService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleChangeLog.java
Labels: type-bug

#2981 fix(security): update oauth2 client version
  pom.xml
Labels: security bug

#2982 fix(task-framework): throw NPE when uploading log to object storage fails
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java
Labels: type-bug

#2943 fix(pre-check): failed to get sql check result when the check result file is not on this machine
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
Labels: type-bug

#2986 fix(dlm): sync limit configuration when updating the schedule
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#2987 fix(schedule): fail to update trigger config
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#2928 fix(global-search): unable to stop data object synchronization
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/connection/DatabaseRepositoryTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseSyncManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncScheduler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncTaskManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/GlobalSearchProperties.java
Labels: type-bug

#2985 fix(db-browser): failed to recognize the commit and rollback statement
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/CacheElement.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/MysqlModeSqlParserListener.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModeParserListener.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModeSqlParserListener.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/PLParserTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/SqlParserTest.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLTableExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTableExtension.java
Labels: type-bug

#2992 fix(alarm): publish alarm when skip execution
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
Labels: type-bug

#3004 fix(alarm): task alarm add exception message
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyExecutorJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#3007 fix(organization): failed to list individual organization
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/OrganizationService.java
Labels: type-bug

#3003 fix(login): set max_login_record_time_minutes default value to 0 in web mode
  server/odc-migrate/src/main/resources/migrate/web/V_4_3_1_6__init_max_login_record_time.sql
Labels: type-bug

#3012 fix(schedule): validate trigger interval when create scheduler
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/processor/CreateFlowInstanceProcessAspect.java
Labels: type-bug

#2978 feat(kill session): adapt global client session and using block in oracle model in kill session
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ConnectSessionController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
Labels: type-feature

#3037 fix(database): creating databases under the data source failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
Labels: type-bug

#3035 fix(table-permission): not select the specific database/table by default when create the permission application ticket
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/UnauthorizedDBResource.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java
Labels: type-bug

#3033 fix(dlm): several bug related to editing data cleaning
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/processor/CreateFlowInstanceProcessAspect.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java
Labels: type-bug

#3039 fix(partition-plan): can not recognize the partition key's data type on mysql mode
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPoint.java
Labels: type-bug

#3046 fix(table-permission): could create tickets when users have no permission to the database
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java
Labels: type-bug

#3050 fix(dlm): create the target table if the sync table structure is off in MySQL mode
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
Labels: type-bug

#3067 fix(database-permission): wrongly recognize packages as schemas
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/DBResourcePermissionInterceptor.java
Labels: type-bug

#3072 fix(flow): wrong approval flow for database/table permission apply ticket
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
Labels: type-bug
