Repository oceanbase/odc, pull requests merged in 2024-06, with the labels that each got.

#2601 feat(dlm):upgrade dlm sdk version to 1.1.3
  pom.xml
Labels: type-feature

#2589 fix(flow): the disabled user can still approving or rejecting a flow
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/model/Project.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/ApprovalPermissionService.java
Labels: type-bug

#2565 fix(ticket): failed to approve ticket when input over-sized comment
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug

#2564 fix(dlm): data delete retry failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
Labels: type-bug

#2562 fix(schedule): schedule cannot be disabled if project is archived
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#2625 fix(flow): cannot find approvers for multiple database change task when using database owner
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceApprovalViewRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowApprovalInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/listener/ApprovalStatusNotifyListener.java
Labels: type-bug

#2624 fix(flow-task): optimize error message of flow task cancelation
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug

#2628 refactor: pick changes from 43x
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/config/SystemConfigRepositoryTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/ConfigEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/response/PaginatedData.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/response/PaginatedResponse.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/systemconfig/DbConfigChangeMatcher.java
Labels: type-refactor

#2626 fix(schema): loading table detail costs too much time
  libs/db-browser/pom.xml
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/CacheElement.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/PLParser.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/SqlParser.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParser.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTableExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java
Labels: type-bug

#2538 refactor(flow): add skip auth to flow mapper
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/JobAttributeRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowInstanceDetailResp.java
Labels: type-refactor

#2637 fix(dlm): table not found in task framework mode
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
Labels: type-bug

#2636 fix(schema): function and procedure list is not ordered by their name in ob-mysql
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
Labels: type-bug

#2639 fix(multiple database): error occurs when viewing the list without templates
  server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/DatabaseChangeChangingOrderTemplateService.java
Labels: type-bug

#2648 fix(connect): failed to connect to a standby cluster and view table structure
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/connection/ConnectionAttributeRepositoryTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionAttributeRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/TestConnectionReq.java
Labels: type-bug

#2642 fix(collaboration): can not modify the description of project
  server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
Labels: type-bug

#2649 fix(schema): failed to query variables on native oracle
  server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleSessionExtension.java
  server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleTraceExtension.java
Labels: type-bug

#2640 fix(dml): failed to modify data which is geometry type
  server/odc-service/src/main/java/com/oceanbase/odc/service/dml/converter/OBOracleGeometryConverter.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/dml/DataConvertUtilTest.java
Labels: type-bug

#2592 fix(multiple database): pre sql check node failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/RuntimeTaskConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java
Labels: type-bug

#2651 fix(dlm): task timeout was not effective
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
Labels: type-bug

#2661 fix(db-object): exception occurred when open oracle table in GBK encoding
  pom.xml
  server/odc-service/pom.xml
  server/plugins/connect-plugin-oracle/pom.xml
Labels: module-Database object

#2664 fix(parser): failed to parse json_function for native oracle
  libs/ob-sql-parser/src/main/resources/oracle/PlSqlLexer.g4
  libs/ob-sql-parser/src/main/resources/oracle/PlSqlParser.g4
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DBStructureComparisonFlowableTask.java
  server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/model/JdbcUrlProperty.java
Labels: type-bug

#2402 feat(osc): add rate limiter for osc
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/OscController.java
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeScheduleTaskParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/RateLimiterConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/UpdateRateLimiterConfigRequest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/openapi/OmsProjectOpenApiService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/openapi/OmsProjectOpenApiServiceImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/request/FullTransferConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/request/IncrTransferConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/request/ThrottleConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/request/UpdateProjectConfigRequest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/BaseCreateOmsProjectValve.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/pipeline/ScheduleCheckOmsProjectValve.java
Labels: type-feature, module-Online schema change

#2677 fix(multiple database): the method isIntercepted in multiple database pre check node is error
  server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/DatabaseChangeChangingOrderTemplateSchedules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
Labels: type-bug

#2676 fix(dlm): target database id is null in task framework mode
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
Labels: type-bug

#2684 fix(apply database): failing to apply database permission deliver
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug

#2690 security: upgrade spring-security from 5.1.10 to 5.7.12
  pom.xml
Labels: security bug

#2682 fix(dlm): table structure synchronization failed
  server/odc-server/src/main/resources/log4j2.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveTableConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataDeletePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
Labels: type-bug

#2699 fix(desktop): failed to bootstrap odc when upgrading from the version 3.2.0
  server/starters/desktop-starter/src/main/java/com/oceanbase/odc/migrate/DesktopResourceHandle.java
Labels: type-bug

#2702 fix(multiple database): the return of method intercepted in multiple database pre check node is incorrect
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
Labels: type-bug

#2706 fix(dlm): alter execute task job type for data cleaning
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
Labels: type-bug

#2704 fix(security): add skip auth annotation
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/LogicalTableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
Labels: security bug

#2708 fix(db-browser): failed to open SYS console when user without query sys permissions
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleSessionExtension.java
Labels: type-bug

#2709 fix(ticket): project owners failed to abort a ticket
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowResponseMapperFactoryTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowInstanceDetailResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/FlowNodeInstanceDetailResp.java
Labels: type-bug

#2712 fix(dlm): the task status does not update properly when structural synchronization fails
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
Labels: type-bug

#2675 docs: change log for v4.3.0
  CHANGELOG-zh-CN.md
  CHANGELOG.md
  CHANGELOG.rst
Labels: type-docs

#2714 refactor(security): add configurable security whitelists
  server/odc-service/src/main/java/com/oceanbase/odc/config/CommonSecurityProperties.java
Labels: type-refactor

#2697 fix(dlm): upgrade dlm sdk to 1.1.4
  pom.xml
Labels: type-bug

#2716 fix(ticket): failed to view all tickets
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/FlowInstanceViewSpecs.java
Labels: type-bug

#2670 refactor(schedule): add without permission method
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
Labels: type-refactor

#2719 fix(multiple database): change the method when initiating child tickets
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/MultipleDatabaseChangeRuntimeFlowableTask.java
Labels: type-bug

#2720 fix(structure-comparison): get a wrong result when comparing two same tables
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableConstraintStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableIndexStructureComparator.java
Labels: type-bug

#2725 fix(schedule): terminate if schedule is invalid
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#2755 fix(taskframework): cannot rollback stop when destroy executor failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/JobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/DefaultTaskFrameworkDisabledHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
Labels: type-bug

#2772 fix(schedule): creator is not allowed to alter schedule
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#2763 fix(taskframework): running task be canceled incorrect due to heartbeat timeout
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/TaskMonitor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/BaseTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/Task.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#2776 fix(table-object): there would be an NPE if fail to parse index ddl
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java
Labels: type-bug

#2785 builds: update code owner configuration
  .github/CODEOWNERS
Labels: type-build

#2786 fix(database-permission): mistake caused by code merge
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportFlowableTask.java
Labels: type-bug

#2757 feat(server): allows some beans to be loaded only in server mode
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/ConditionOnServer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/ExcludeProfileCondition.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionSchedules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DatabaseSyncSchedules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/DatabaseChangeChangingOrderTemplateSchedules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncScheduler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DlmLimiterService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowSchedules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/lab/LabSchedules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationScheduleConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/QuartzJobService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/config/QuartzConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateListener.java
Labels: type-feature
