Repository oceanbase/odc, pull requests merged in 2024-02, with the labels that each got.

#1495 fix(partition-plan):delete job failed if the associated trigger does not exist
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#1489 feat(pre-check): adapt to task framework
  server/integration-test/src/test/java/com/oceanbase/odc/service/objectstorage/LocalFileOperatorTest.java
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/mapper/OdcRuntimeDelegateMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/PreCheckTaskProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/operator/LocalFileOperator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobParametersKeyConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/ObjectStorageHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DatabaseChangeTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/PreCheckTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/PreCheckTaskParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobUtils.java
Labels: type-feature, priority-medium, module-Task framework

#1530 reactor(taskframework): reactor pod config about region and image name
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/NativeK8sClientTest.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_16__update_task_framework_system_config.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCallerBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/NativeK8sJobClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/PodConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/PodParam.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultTaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobEnvKeyConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/provider/DefaultJobImageNameProvider.java
Labels: type-refactor, module-Task framework

#1534 refactor(taskframework): add LoggerService for DLM query log
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/logger/LoggerService.java
Labels: type-refactor, module-Task framework

#1541 fix(taskframework): k8s system config from data.sql is empty string
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java
Labels: type-bug, module-Task framework

#1538 feat(dlm):adapt to log service
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-feature

#1473 feat(structure-comparison): integrate structural comparison into the service layer
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/DBTablePartitionEditor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTableIndex.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoGreaterThan5740SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLBetween2277And3XSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleLessThan400SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/MySQLNoGreaterThan5740SchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBOracleSchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OracleSchemaAccessorTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/structurecompare/StructureComparisonTaskRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/structurecompare/StructureComparisonTaskResultRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/obmysql/DefaultDBStructureComparatorTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/oboracle/DefaultDBStructureComparatorTest.java
  server/integration-test/src/test/resources/structurecompare/obmysql/source_drop.sql
  server/integration-test/src/test/resources/structurecompare/obmysql/source_schema_ddl.sql
  server/integration-test/src/test/resources/structurecompare/obmysql/target_drop.sql
  server/integration-test/src/test/resources/structurecompare/obmysql/target_schema_ddl.sql
  server/integration-test/src/test/resources/structurecompare/oboracle/source_schema_ddl.sql
  server/integration-test/src/test/resources/structurecompare/oboracle/target_schema_ddl.sql
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ResourceType.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_10__structure_comparison_task.sql
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/SchemaSyncController.java
  server/odc-server/src/main/resources/log4j2.xml
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/structurecompare/StructureComparisonEntitySpecs.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/structurecompare/StructureComparisonTaskEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/structurecompare/StructureComparisonTaskRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/structurecompare/StructureComparisonTaskResultEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/structurecompare/StructureComparisonTaskResultRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/processor/CreateFlowInstanceProcessAspect.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DBStructureComparisonFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DBObjectStructureComparisonResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DBStructureComparisonParameter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DBStructureComparisonResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DBStructureComparisonTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/DBStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/DefaultDBStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/StructureComparisonService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/StructureComparisonTraceContextHolder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableConstraintStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableIndexStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/model/DBObjectComparisonResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/model/DBStructureComparisonConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/TaskService.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/structurecompare/DBObjectComparisonResultTest.java
Labels: type-feature

#1560 fix(osc): support create index sql in ob oracle
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/ddl/TableNameReplacerTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBMysqlTableNameReplacer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OBOracleTableNameReplacer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OscFactoryWrapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/OscFactoryWrapperGenerator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/ddl/TableNameReplacer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/subtask/SubTaskParameterFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java
Labels: type-bug, module-Online schema change

#1580 fix(osc): fix i18n hint when user started swap table
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
Labels: type-bug, module-Online schema change

#1592 fix(database-permission): DB permission interceptor invalid when executing PL in the SQL console
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/SchemaExtractor.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/session/SchemaExtractorTest.java
Labels: type-bug, priority-medium, module-Database Permission

#1569 feat(rollback-plan): adapt to task framework
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/model/FileBucket.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/OdcFlowInstanceConfigurer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/RollbackPlanRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/RollbackPlanRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/mapper/OdcRuntimeDelegateMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/FlowTaskProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/RollbackPlanTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/OrganizationAuthenticationInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/model/RollbackProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/RollbackPlanTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/RollbackPlanTaskParameters.java
Labels: type-feature, module-Task framework

#1602 fix(cloud): tenant/serverless instance test connection failed in some specific scenery
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionEnvironmentAdapter.java
Labels: type-bug

#1599 enhancement(unit-test): on-demand loading of unit test dependent data sources
  server/odc-test/src/main/java/com/oceanbase/odc/test/database/TestDBConfigurations.java
  server/plugins/connect-plugin-doris/src/test/java/com/oceanbase/odc/plugin/connect/doris/BaseExtensionPointTest.java
  server/plugins/connect-plugin-doris/src/test/java/com/oceanbase/odc/plugin/connect/doris/DorisExtensionTest.java
Labels: enhancement, priority-medium

#1597 fix(osc): validate input ddl throw syntax exception when contain comment
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/util/SqlUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/validator/OnlineSchemaChangeValidator.java
Labels: type-bug, module-Online schema change

#1520 feat(datasource): session management adapt for oracle11g
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionUtil.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/model/OdcDBSession.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/DefaultJdbcRowMapper.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/OBOracleNlsFormatTimestampLTZMapper.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/OBOracleNlsFormatTimestampTZMapper.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/OracleNlsFormatTimestampLTZMapper.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/OracleNlsFormatTimestampTZMapper.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/OdcDBSessionRowMapper.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/mapper/OBOracleNlsFormatTimestampLTZMapperTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/mapper/OBOracleNlsFormatTimestampTZMapperTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/sql/execute/mapper/OracleTimeStampMapperTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DBSessionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/KillSessionOrQueryReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/KillSessionResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectSessionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/DefaultDBStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DatabaseChangeTask.java
  server/plugins/schema-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oracle/OracleTableExtension.java
Labels: module-Data source management, module-sql execution

#1604 feat(notification): support custom http request for wehbook channel
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/DingTalkSender.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/FeishuSender.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/HttpSender.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/WeComSender.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/MessageResponseValidator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/model/WebhookChannelConfig.java
Labels: type-feature, notification

#1578 feat(databaseChange): Automatically adjust the timeout if the database change task involves time-consuming index change operations
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowInstanceServiceTest.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/ServiceTaskInstanceRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/FlowTaskProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/SqlCheckTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/SqlCheckRuleType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/IndexChangeTimeConsumingExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DatabaseChangeTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/DatabaseChangeTaskParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/runtime/PreCheckTask.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java
Labels: type-feature, module-Security control

#1610 fix(cloud): add a CacheManager bean which allows null values
  server/odc-service/src/main/java/com/oceanbase/odc/config/CacheConfiguration.java
Labels: type-bug

#1614 fix(dlm):create target table failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
Labels: type-bug

#1623 fix(structure-comparison):failed to create structure-comparison task in personal space
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug

#1606 feat(dlm): supports review sql
  server/integration-test/src/test/java/com/oceanbase/odc/service/dlm/DLMServiceTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DLMController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/PreviewSqlStatementsReq.java
Labels: type-feature

#1630 enhancement(db-browser): return all SchemaIdentities even the schema has no tables or views
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoGreaterThan5740SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBIdentitiesService.java
Labels: type-bug, enhancement

#1632 fix(db-browser): listTables correctly returns the table under the specified schema
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
Labels: type-bug

#1643 feat(dlm): data clean adapt to task framework
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/CloudDLMJobStore.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataArchiveJobFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/JobMetaFactoryCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DLMJobParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJobCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/StdJobScheduler.java
Labels: type-feature

#1641 fix(security): share public and private key when ODC is deployed on multiple nodes
  server/integration-test/src/test/java/com/oceanbase/odc/service/encryption/SensitivePropertyHandlerImplTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigDAO.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/encryption/SensitivePropertyHandlerImpl.java
  server/odc-service/src/main/resources/mapper/SystemConfigDAO.xml
  server/odc-service/src/test/java/com/oceanbase/odc/service/encryption/SensitivePropertyHandlerImplTest.java
Labels: type-bug

#1647 feat(notification): support scheduling failed and task terminated
  server/odc-migrate/src/main/resources/init-config/init/notification-policy-metadata.yaml
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/config/QuartzConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/JobSchedulerFactoryBean.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/JobTerminateNotifyListener.java
Labels: module-Notification

#1644 fix(config): wrong reason while full link trace not enabled
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/OdcStatementCallBack.java
  server/odc-service/src/main/resources/config-meta/user-config-meta.yml
Labels: type-bug

#1611 feat(osc): support add column in new ddl
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/DefaultOnlineSchemaChangeTaskHandler.java
Labels: type-feature, module-Online schema change

#1601 fix(taskframework): use default entry point to replace init cmd
  script/start-odc.sh
  server/odc-server/src/main/resources/log4j2-task.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/logger/LoggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskFrameworkService.java
Labels: type-bug, module-Task framework

#1617 feat(database-change): adaption for oracle11g
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/util/SqlUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/AbstractRollbackGenerator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/RollBackPlanJdbcRowMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/RollbackGeneratorFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/oracle/OracleDeleteRollbackGenerator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/oracle/OracleUpdateRollbackGenerator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/initializer/ConsoleTimeoutInitializer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/BaseSqlChecker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DatabaseChangeTask.java
Labels: type-feature

#1660 feat: make odc adapt to OceanBase 4.2.2
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  libs/ob-sql-parser/pom.xml
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLExpressionFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLInsertFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLPartitionFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLTableOptionsFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleDataTypeFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleExpressionFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleFromReferenceFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/createtable/TableOptions.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/expression/FunctionCall.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/expression/IntervalExpression.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/insert/InsertTable.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/select/oracle/XmlNamespaces.java
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBLexer.g4
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBParser.g4
  libs/ob-sql-parser/src/main/resources/oboracle/sql/OBLexer.g4
  libs/ob-sql-parser/src/main/resources/oboracle/sql/OBParser.g4
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLCreateTableFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLExpressionFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLInsertFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/OracleDataTypeFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/OracleExpressionFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/OracleFromReferenceFactoryTest.java
  pom.xml
Labels: type-feature

#1674 fix(structure-compare): alter table remove partitioning sql is not put in comment
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLAlterTableActionFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/alter/table/AlterTableAction.java
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBParser.g4
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLAlterTableActionFactoryTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/model/DBObjectComparisonResult.java
Labels: type-bug
