Repository oceanbase/odc, pull requests merged in 2024-05, with the labels that each got.

#2313 fix(dlm): the target table does not exist
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
Labels: type-bug

#2319 fix(alarm): alarm msg add request
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/trace/TraceHandlerInterceptor.java
Labels: type-bug

#2314 fix(notification): lost sign when updating channel
  server/integration-test/src/test/java/com/oceanbase/odc/service/notification/NotificationServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/notification/ChannelRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/ChannelMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/model/WebhookChannelConfig.java
Labels: module-Notification

#2320 fix(osc): osc job is terminated when database id is not exist
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
Labels: type-bug

#2328 fix(db-browser): partition definitions is not ordered
  libs/db-browser/src/main/resources/schema/sql/mysql/mysql_5_6_x.yaml
  libs/db-browser/src/main/resources/schema/sql/mysql/mysql_5_7_x.yaml
  libs/db-browser/src/main/resources/schema/sql/obmysql/obmysql_4_0_x.yaml
Labels: type-bug

#2330 fix(dlm): correct the task status when the task exits abnormally
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/JobType.java
Labels: type-bug

#2331 fix(taskframework): always print warn log about "Task-framework isEnabled"
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java
Labels: type-bug

#2327 fix(partition-plan): generated partition expression is not contiguous
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPoint.java
Labels: type-bug

#2065 fix(connection): add serialVersionUID for ConnectionConfig
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/TemplateVariables.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/model/ExecutorInfo.java
Labels: type-bug

#2340 fix(dlm): the task status was set to completed when the task was canceled
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
Labels: type-bug

#2333 fix(schedule): status not found
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleStatus.java
Labels: type-bug

#2338 build: upgrade workflow action version to v4
  .github/workflows/build_artifact.yaml
  .github/workflows/build_daily.yaml
  .github/workflows/build_dev.yaml
  .github/workflows/build_release.yaml
Labels: type-build

#2341 fix(taskframework): oss log info is ignored when cancel job
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#2342 fix(flow): task will be failed when its execution undergoes a version upgrade
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
Labels: type-bug

#2344 reactor(taskframework): reactor save log meta data
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-refactor

#2351 enhancement(partition-plan): add a prompt when no preview sql generated
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/Symbols.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java
Labels: type-bug

#2277 fix(web-framework): csrfToken API does not return token
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/exception/AccessDeniedException.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/CommonSecurityProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/util/WebResponseUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/OrganizationAuthenticationInterceptor.java
Labels: type-bug

#2355 fix(data-masking): unavailable when existing invalid database with duplicated name
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
Labels: type-bug, priority-medium, module-Data masking

#2371 fix(encryption): exception occurs when invoking RSA decryption concurrently
  server/odc-common/src/main/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptor.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptorTest.java
Labels: type-bug, priority-high

#2336 fix(account-integration): failed to login after updating user extra properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
Labels: type-bug, priority-high

#2372 feat(migrate):add unique identifier in collaboration project
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_0_4__add_unique_identifier.sql
Labels: type-feature

#2359 fix(iam): failed to delete a user who is an archived project's Owner or DBA
  server/odc-service/src/main/java/com/oceanbase/odc/config/HookConfiguration.java
Labels: type-bug, priority-high

#2374 fix(encryption): exception occurs when invoking RSA decryption concurrently
  server/odc-common/src/main/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptor.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptorTest.java
Labels: type-bug

#2377 feat(migrate):migrate history uniqueIdentifier in collaboration_project
  server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_0_4__add_unique_identifier.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/collaboration/ProjectEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/model/Project.java
Labels: type-feature

#2380 builds: supports build web in arm64
  .github/workflows/build_artifact.yaml
  .github/workflows/build_daily.yaml
  .github/workflows/build_release.yaml
Labels: type-build

#2385 bugfix(data-masking): unavailable when existing invalid database with duplicated name
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
Labels: type-bug

#2388 fix(shadowtable): bad sql grammer when table column's default value is a string type in MySQL
  server/odc-common/pom.xml
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/StringUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/shadowtable/ShadowTableComparingTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/DefaultDBStructureComparator.java
Labels: type-bug

#2389 fix(encryption): RSA decrypting failed if already decrypted a invalid input string
  server/odc-common/src/main/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptor.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/crypto/RsaBytesEncryptorTest.java
Labels: type-bug

#2189 feat(dlm): incremenntal table structure synchronization
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DlmTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DLMJobParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
Labels: type-feature

#2399 docs: fix errors in international translation
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
Labels: type-docs

#2404 builds: support build rpm and docker image in aarch64
  .github/workflows/build_artifact.yaml
  .github/workflows/build_daily.yaml
  .github/workflows/build_dev.yaml
  .github/workflows/build_release.yaml
Labels: type-build

#2413 chore: use OBE error code
  distribution/docker/odc/Dockerfile
  server/integration-test/src/test/resources/parser/packages/dbms/dbms_utility.sql
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/OracleDateFormat.java
Labels: enhancement

#2405 fix(ticket): failed to set download log file url
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/TaskType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
Labels: type-bug

#2408 fix(taskframework): daemon job be fired at one time in cluster model
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/JobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java
Labels: type-bug

#2297 fix(schema-plugin):fix table ddl do not show unique index when table is partitioned
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTableExtension.java
Labels: type-bug

#2298 fix(schema-plugin): remove the logic that automatically converts table names to lowercase when getTable
  server/plugins/schema-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/schema/mysql/MySQLTableExtension.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLTableExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleTableExtension.java
  server/plugins/schema-plugin-odp-sharding-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/odpsharding/obmysql/ODPShardingOBMySQLTableExtension.java
Labels: type-bug

#2417 fix(database-permission): could not call inside dbms package in SQL console
  server/integration-test/src/test/java/com/oceanbase/odc/service/permission/PermissionCheckWhitelistTest.java
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/common/PermissionCheckWhitelist.java
Labels: type-bug, priority-medium, module-Database Permission

#2431 fix(flow): optimize flow submitter about exception handler
  server/odc-core/src/main/java/com/oceanbase/odc/core/flow/BaseFlowableDelegate.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/flow/util/FlowUtil.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/flow/util/FlowableBoundaryEvent.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/listener/BaseStatusModifyListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/CustomDelegateExecution.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/ExecutionEntityFacade.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskCallBackApprovalService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskSubmitter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PartitionPlanRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/RollbackPlanRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AlterScheduleTask.java
Labels: type-bug, enhancement, type-refactor

#2467 fix(metadb): change systemConfigDao to systemConfigRepository.
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/config/SystemConfigRepositoryTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/ConfigEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/systemconfig/DbConfigChangeMatcher.java
Labels: type-refactor

#2474 fix(dlm): archiving specified partition failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DataArchivePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
Labels: type-bug

#2436 feat(object-search): individual space support global object search
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigKeys.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseSyncManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncScheduler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncTaskManager.java
  server/odc-service/src/main/resources/config-meta/user-config-meta.yml
Labels: type-feature

#2464 fix(project): optimize error message when update a project name to an existed project name
  server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
Labels: type-bug

#2489 fix(dlm): sync table structure failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveTableConfig.java
Labels: type-bug

#2485 feat(config):add creator_id to config entity
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigRepository.java
Labels: type-refactor

#2493 refactor(config): Add more fields to configEntity
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/ConfigEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/SystemConfigEntity.java
Labels: type-refactor

#2498 fix(dlm): optimize error message
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AbstractDlmJobPreprocessor.java
Labels: type-bug

#2442 feat(multipledatabase): add audit events for multiple databases
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventAction.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventType.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/init-config/default-audit-event-meta.yml
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/AuditEventMetaService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/util/AuditUtils.java
Labels: type-feature

#2468 enhancement(flow): add heartbeat for flow task
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/flow/ServiceTaskInstanceRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/task/TaskRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/tool/TestFlowableDelegateImpl.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/flow/BaseFlowableDelegate.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_0_6__add_flow_task_heartbeat.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/ServiceTaskInstanceRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/TaskEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/TaskRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowSchedules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowInstanceConfigurer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/OdcFlowInstanceConfigurer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/listener/ServiceTaskExecutingCompleteListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseRuntimeFlowableDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/CreateExternalApprovalTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskSubmitter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/MultipleDatabaseChangeRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/FlowTaskProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/TaskService.java
Labels: enhancement

#2501 fix(session): failed to set nls parameters for native oracle in sql-console
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/NlsFormatInterceptor.java
Labels: type-bug

#2220 enhancement(connection): optimize error message when testing the connection to an OceanBase backup instance
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionTestUtilTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionTestResult.java
  server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/ConnectionExtensionPoint.java
  server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/TestResult.java
  server/plugins/connect-plugin-doris/src/main/java/com/oceanbase/odc/plugin/connect/doris/DorisConnectionExtension.java
  server/plugins/connect-plugin-doris/src/test/java/com/oceanbase/odc/plugin/connect/doris/DorisExtensionTest.java
  server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLConnectionExtension.java
  server/plugins/connect-plugin-mysql/src/test/java/com/oceanbase/odc/plugin/connect/mysql/MySQLExtensionTest.java
  server/plugins/connect-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLConnectionExtension.java
  server/plugins/connect-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/connect/obmysql/OBMySQLExtensionTest.java
  server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleConnectionExtension.java
  server/plugins/connect-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleExtensionTest.java
  server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleConnectionExtension.java
  server/plugins/connect-plugin-oracle/src/test/java/com/oceanbase/odc/plugin/connect/oracle/OracleExtensionTest.java
Labels: enhancement

#2523 fix(database): database sync involved no-privilege databases in OBMySQL
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
Labels: type-bug

#2534 fix(flow): failed to create a ticket which manual strategy in individual space
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/ExecutionStrategyConfig.java
Labels: type-bug

#2497 fix(dlm): table structure synchronization failure when table names are inconsistent
  server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/obmysql/DBTableStructureComparatorTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/AbstractDBObjectStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableColumnStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableConstraintStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableIndexStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTablePartitionStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/comparedbobject/DBTableStructureComparator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
Labels: type-bug

#2579 fix(ticket): wrong i18n description for task
  server/odc-common/src/main/java/com/oceanbase/odc/common/i18n/Translatable.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java
Labels: type-bug

#2563 fix(object-search): failed to sync database metadata in individual space
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java
Labels: type-bug

#2590 fix(collaboration): vertical unauthorizing exists when editing database owners
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
Labels: type-bug

#2448 feat(projectService): adaption for organization、project、role service
  server/integration-test/src/test/java/com/oceanbase/odc/service/iam/RoleServiceTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-service/src/main/java/com/oceanbase/odc/config/BeanConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/collaboration/ProjectRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/UserOrganizationRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/UserPermissionRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/UserRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/automation/AbstractAutomationEventHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/model/SetArchivedReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/CloudMetadataClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/RoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserOrganizationService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/OrganizationAuthenticationInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/util/SecurityContextUtils.java
Labels: type-feature
