Repository oceanbase/odc, pull requests merged in 2024-09, with the labels that each got.

#3251 feat(dlm): update dlm sdk version to 1.1.4.bp1
  pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/DataArchiveTask.java
Labels: type-feature

#3250 enhancement(sql-console): sort the lists of data sources, databases, and database objects in ascending order by name
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataBaseController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/ConnectionConfigRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dbobject/DBObjectRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/TableService.java
Labels: enhancement

#3257 fix(statefulRoute): batchCompilations and getRecyclebinSettings will failed if statefulroute enabled
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBRecyclebinController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/PLController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLService.java
Labels: type-bug

#3138 feat(worksheet): add implementation for worksheet
  .gitignore
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/server/web/controller/v2/WorksheetControllerIntegrationTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/PreConditions.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/LimitMetric.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ResourceType.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_6__add_collaboration_worksheet.sql
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/WorksheetController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/objectstorage/ObjectMetadataRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudObjectStorage.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AlibabaCloudClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AmazonCloudClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/NullCloudClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/CloudObjectStorageConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/CopyObjectResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/util/CloudObjectStorageUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacade.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/constants/WorksheetConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/converter/WorksheetConverter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/domain/BatchCreateWorksheetsPreProcessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/domain/BatchOperateWorksheetsDivider.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/domain/Path.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/domain/WorkSheetsSearch.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/factory/WorksheetServiceFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/BatchOperateWorksheetsResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/BatchUploadWorksheetsReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/GenerateWorksheetUploadUrlResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/ListWorksheetsReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/UpdateWorksheetReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/WorksheetLocation.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/WorksheetMetaResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/WorksheetType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/DefaultWorksheetService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/RepoWorksheetService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/WorksheetService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/utils/WorksheetPathUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/utils/WorksheetUtil.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImplTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/domain/PathConstructorTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/domain/PathGetParentPathTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/domain/PathGetPathAtTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/domain/PathGetPathComparatorTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/domain/PathMoveWhenDestinationPathExistTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/domain/PathMoveWhenDestinationPathNotExistTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/service/DefaultWorksheetServiceTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/utils/WorkSheetPathUtilFindCommonParentPathTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/utils/WorksheetPathUtilTest.java
Labels: type-feature

#3147 feat(sqlcheck): SQL check supports affected rows
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/SqlAffectedRowsFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/SqlCheckRuleType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SqlCheckRules.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
Labels: type-feature

#3273 fix(sso): get state params may failed when use load banlance
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/Oauth2StateManager.java
Labels: type-bug

#3289 feat(dfa): add simple dfa for workflow cluster's status transfer
  server/odc-core/src/main/java/com/oceanbase/odc/core/dfa/AbstractDfa.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/dfa/DfaStateTransfer.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/dfa/DfaTest.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/dfa/K8sPodStatusDfa.java
  server/odc-core/src/test/java/com/oceanbase/odc/core/dfa/K8sPodStatusDfaTransfer.java
Labels: type-feature

#3190 feat(resourcehistory): add resource last access time
  server/integration-test/src/test/java/com/oceanbase/odc/service/resourcehistory/ResourceLastAccessServiceTest.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_6__add_history_resource_last_access.sql
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_7__add_collaboration_worksheet.sql
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/WorksheetController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/resourcehistory/ResourceLastAccessEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/resourcehistory/ResourceLastAccessRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resourcehistory/ResourceLastAccessService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/WorksheetMetaResp.java
Labels: type-feature

#3296 fix(web): add server restart alarm
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmEventNames.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java
Labels: enhancement

#3299 refactor(dfa): move it from odc-core to odc-common
  server/odc-common/src/main/java/com/oceanbase/odc/common/dfa/AbstractDfa.java
  server/odc-common/src/main/java/com/oceanbase/odc/common/dfa/DfaStateTransfer.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/dfa/DfaTest.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/dfa/K8sPodStatusDfa.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/dfa/K8sPodStatusDfaTransfer.java
Labels: type-refactor

#3302 fix(sql-plan): create sql-plan failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeParameters.java
Labels: type-bug

#3321 fix(sql-plan): detail sql-plan failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlplan/model/SqlPlanParameters.java
Labels: type-bug

#3320 fix(osc): osc manual swap table button not displayed
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/OnlineSchemaChangeTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
Labels: type-bug

#3323 fix(dlm): detail schedule task missing parameters
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
Labels: type-bug

#3325 feat(schedule): adaption for support obcloud operation event
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ChangeScheduleResp.java
Labels: type-feature

#3301 feat(worksheet): add implementation for flat list
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/server/web/controller/v2/WorksheetControllerIntegrationTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImplTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/LimitMetric.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_7__add_collaboration_worksheet.sql
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/WorksheetController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/constants/WorksheetConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/converter/WorksheetConverter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/domain/BatchCreateWorksheetsPreProcessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/BatchOperateWorksheetsResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/BatchUploadWorksheetsReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/DefaultWorksheetService.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/service/DefaultWorksheetServiceTest.java
Labels: type-feature

#3355 fix(dlm): create connection failed in oracle
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DataSourceInfoMapper.java
Labels: type-bug

#3371 fix(logicaldatabase): unexpection exception throwed when there is no SQL needs to run in some physical database
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/sql/SqlExecutionHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/LogicalDatabaseChangeTask.java
Labels: type-bug

#3392 fix(mock-data): failed to mock data at mysql 5.7
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/Symbols.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/FlowTaskUtil.java
Labels: type-bug

#3361 fix(permission): failed to execute sql of renaming table
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
Labels: module- SQL window

#3345 feat(worksheet): add organizationId and workspaceId to worksheet
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImplTest.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_7__add_collaboration_worksheet.sql
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/WorksheetController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacade.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/constants/WorksheetConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/DefaultWorksheetService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/RepoWorksheetService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/WorksheetService.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImplTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/service/DefaultWorksheetServiceTest.java
Labels: type-feature

#3399 fix(logicaldatabase): wrong generated ddl of creating and altering logical tables
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
Labels: type-bug

#3409 feat(worksheet): move worksheet to odc-cloud
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImplTest.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_7__add_collaboration_worksheet.sql
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/WorksheetController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/worksheet/CollaborationWorksheetRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacade.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/constants/WorksheetConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/converter/WorksheetConverter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/domain/BatchCreateWorksheetsPreProcessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/domain/BatchOperateWorksheetsDivider.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/domain/Path.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/domain/WorkSheetsSearch.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/factory/WorksheetServiceFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/BatchOperateWorksheetsResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/BatchUploadWorksheetsReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/GenerateWorksheetUploadUrlReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/GenerateWorksheetUploadUrlResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/ListWorksheetsReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/UpdateWorksheetReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/WorksheetLocation.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/WorksheetMetaResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/WorksheetResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/model/WorksheetType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/DefaultWorksheetService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/RepoWorksheetService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/service/WorksheetService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/utils/WorksheetPathUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/utils/WorksheetUtil.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImplTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/domain/PathConstructorTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/domain/PathGetParentPathTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/domain/PathGetPathAtTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/domain/PathGetPathComparatorTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/domain/PathMoveWhenDestinationPathExistTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/domain/PathMoveWhenDestinationPathNotExistTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/service/DefaultWorksheetServiceTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/utils/WorkSheetPathUtilFindCommonParentPathTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/worksheet/utils/WorksheetPathUtilTest.java
Labels: type-feature

#3411 refactor(resourcehistory): shorten the length of index index names in history_resource_last_access
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_6__add_history_resource_last_access.sql
Labels: type-refactor

#3408 fix(logicaldatabase): logical database last sync time not shown
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java
Labels: type-bug

#3372 fix(logicaldatabase): submit a extract logical table task after logical database change task done
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
Labels: type-bug

#3402 fix(table permission): partition name shouldn't display in the table permission check window
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
Labels: module- SQL window

#3377 fix(schedule): several bugfix
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleChangeLogRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleChangeLogService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/alarm/DefaultScheduleAlarmClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AlterScheduleParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AlterScheduleTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/ApprovalFlowClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DefaultApprovalFlowClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleChangeParams.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/DataArchivePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/SqlPlanPreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/utils/ScheduleTaskUtil.java
Labels: type-bug

#3396 fix(migrate): alter column `value_json` size in `regulation_riskdetect_rule` table
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_11__alter_regulation_riskdetect_rule.sql
Labels: type-bug

#3335 feat(schedule): support download full log for running task
  script/build_jar.sh
  script/build_libs.sh
  script/build_rpm_without_sqlconsole.sh
  script/functions.sh
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/LogUtilsTest.java
  server/odc-common/src/main/java/com/oceanbase/odc/common/json/JsonUtils.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleControllerHist.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceLoggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleLogProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduledTaskLoggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleTaskOverview.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/TaskLoggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/TaskService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/server/ExecutorRequestHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/TaskExecutorClient.java
Labels: type-feature

#3401 fix(table permission): index name displays as table name in sql windows check
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
Labels: module- SQL window

#3424 fix(script): local build libs failure
  script/build_rpm_without_sqlconsole.sh
  script/functions.sh
Labels: type-bug

#3419 fix(structure-compare): show incorrect precision of tinyint datatype in mysql mode
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLNoGreaterThan1479SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/test/resources/table/mysql/testTableColumnDDL.sql
  server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/mysql/DefaultDBStructureComparatorTest.java
  server/integration-test/src/test/resources/structurecompare/mysql/source_drop.sql
  server/integration-test/src/test/resources/structurecompare/mysql/source_schema_ddl.sql
  server/integration-test/src/test/resources/structurecompare/mysql/target_drop.sql
  server/integration-test/src/test/resources/structurecompare/mysql/target_schema_ddl.sql
Labels: type-bug

#3431 fix(response): error dependency for Error in ResourceOperationResult
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/response/batch/BatchOperationResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/response/batch/ResourceOperationResult.java
Labels: type-bug

#3435 fix(logicaldatabase): apply logicla database permission caused to NPE
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/ApplyDatabasePermissionPreprocessor.java
Labels: type-bug

#3410 fix(logicaldatabase): project info not shown and schedule description shows 'null'
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
Labels: type-bug

#3454 fix(schedule): get schedule detail may cause NPE in logical database job
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
Labels: type-bug

#3452 fix(logicaldatabase): adapt logical database/table permission apply
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableFinderTest.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_9__add_logical_database_change_task.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/logicaldatabase/DatabaseMappingRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/logicaldatabase/TableMappingEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/logicaldatabase/TableMappingRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseSyncManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/LogicalTableFinder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/model/DataNode.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/TableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/ApplyDatabaseFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/ApplyDatabasePermissionPreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/DatabasePermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/ApplyDatabaseParameter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/ApplyTableFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/ApplyTablePermissionPreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/TablePermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/model/ApplyTableParameter.java
Labels: type-bug

#3474 fix(logicaldatabase): incorrect status transform logic of logical database change subtasks
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseChangeService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/execution/ExecutionResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/execution/ExecutionStatus.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/execution/ExecutionSubGroupUnit.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/LogicalDatabaseChangeTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/LogicalDBChangeResultProcessor.java
Labels: type-bug

#3482 fix(datasource): fail to access the MySQL data source via a proxy
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
Labels: type-bug

#3492 fix(logicaldatabase): physical databases who have already belonged to a logical database should not be able to configure again
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/logicaldatabase/DatabaseMappingRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java
Labels: type-bug

#3495 fix(logicaldatabase): generate wrong table topologies when logical expression is like db.tb_[00-10]
  server/integration-test/src/test/resources/connection/logicaldatabase/valid_logical_table_expression_resolve.yaml
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/parser/LogicalTableExpressionParseUtils.java
Labels: type-bug

#3494 feat(shared): add WORKSPACE_COUNT_IN_PROJECT in LimitMetric
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/LimitMetric.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
Labels: type-feature

#3496 fix(logicaldatabase): generate wrong ddl when alter table
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
Labels: type-bug

#3490 fix(permission): logical database/table permission not shown
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_12__alter_list_user_table_permission_view.sql
Labels: type-bug

#3493 fix(multiple database): all database type must be same in multiple databases task
  server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/MultipleDatabaseChangePreprocessor.java
Labels: type-bug

#3499 fix(database): the databases list should be ordered by type and name by default
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataBaseController.java
Labels: type-bug

#3500 fix(logicaldatabase): add max physical database count limit in one logical database
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java
Labels: type-bug

#3501 fix(logicaldatabase): failed to recognize the wrong expression like db.tb.xxx
  server/integration-test/src/test/resources/connection/logicaldatabase/invalid_logical_table_expression_resolve.yaml
  server/odc-service/src/main/resources/antlr/logicaldatabase/LogicalTableExpression.g4
Labels: type-bug

#3491 fix(dlm): task status is wrong
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/DLMResultProcessor.java
Labels: type-bug

#3515 fix(logicaldatabase): when sql contains physical databases that does not belong to the logical database, the front-end crashes
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/LogicalDatabaseChangeJob.java
Labels: type-bug

#3520 fix(logicaldatabase): terminal sub-tasks failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/execution/ExecutionSubGroupUnit.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/LogicalDatabaseChangeTask.java
Labels: type-bug

#3465 doc: init 4.3.2 changelog
  CHANGELOG-zh-CN.md
  CHANGELOG.md
  CHANGELOG.rst
Labels: documentation, type-docs

#3529 fix(schedule): risk level mismatch when operating a schedule
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/util/DescriptionGenerator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/DefaultApprovalFlowClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/CreateScheduleReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleChangeParams.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java
Labels: type-bug

#3329 fix(sqlcheck): affected rows for the native MySQL INSERT statement cannot take effect
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/Unable2JudgeAffectedRowsFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/SqlCheckRuleType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/BaseAffectedRowsExceedLimit.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/SqlCheckRules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/Unable2JudgeAffectedRows.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
Labels: type-bug

#3535 fix(sqlplan): generate task failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java
Labels: type-bug

#3528 fix(logicaldatabase): no logical database extract task is submitted after the logical change task is completed
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseSyncManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/execution/ExecutionSubGroupUnit.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/execution/GroupExecutionEngine.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/executor/sql/SqlExecutionHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/model/DataNode.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/LogicalDatabaseChangeJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/PublishLogicalDatabaseChangeReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/LogicalDatabaseChangeTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#3539 fix(resource): the status will be 'UNKNOWN' when resource is not created immediately
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_8__add_resource.sql
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_2_8__add_task_resource.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceOperatorBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/DefaultResourceOperatorBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/BaseNativeK8sResourceOperatorBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/NativeK8sConfigMapOperatorBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/NativeK8sDeploymentOperatorBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/NativeK8sPodOperatorBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/builder/NativeK8sServiceOperatorBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sConfigMapStatusDfa.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sDeploymentMatcher.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sDeploymentStatusDfa.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sPodStatusDfa.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sServiceStatusDfa.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/resource/k8s/K8sDeploymentStatusDfaTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/resource/k8s/K8sPodStatusDfaTest.java
Labels: type-bug

#3545 fix(task-framework): starting task fails when environment variables exceed 2MB in Process Mode
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCallerBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobEnvironmentEncryptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobEnvironmentFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobEnvKeyConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskApplication.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/context/JobContextProviderFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/context/K8sJobContextProvider.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/context/ProcessJobContextProvider.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobUtils.java
Labels: type-bug

#3557 fix(task-framework): remove useless saving results in case of updating status failure
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#3560 fix(logicaldatabase): generated create logical table ddl is wrong
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/model/DataNode.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseUtilsTest.java
Labels: type-bug

#3566 fix(schedule): cherry pick from 4.3.x
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java
Labels: type-bug

#3565 fix(flow): filter out all ALTER_SCHEDULE flow instances in 'all tickets', 'created by me' and 'approving by me'
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug

#3583 feat(schedule): cherry-pick the new read log code to obcloud
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/FlowInstanceController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScheduleController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceLoggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleLogProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduledTaskLoggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/logger/LogUtils.java
Labels: type-feature

#3567 fix(dlm): check datasource cloud provider and region
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/AbstractDlmPreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/DataArchivePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/DataDeletePreprocessor.java
Labels: type-bug

#3580 security: some method lacks permission check
  server/modules/sample-module/src/main/java/com/oceanbase/odc/service/sample/SampleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseChangeService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleChangeLogService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/worksheet/WorksheetServiceFacadeImpl.java
Labels: security bug

#3575 fix(logicaldatabase): several bugfixes when extacting logical databases and showing the databases
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dbobject/DBObjectRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalDatabaseChangeService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/LogicalTableFinder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/ApplyDatabasePermissionPreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/ApplyDatabaseParameter.java
Labels: type-bug

#3516 feat(osc): let osc task resumable
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/config/SystemConfigRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/task/JobRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/flow/FlowResponseMapperFactoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeExpiredTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/resultset/DumperResultSetExportTaskManagerTest.java
  server/odc-common/src/main/java/com/oceanbase/odc/common/json/JsonUtils.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/FlowStatus.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/TaskStatus.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/OscController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/BeanInjectedClassDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseRuntimeFlowableDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/OmsRequestUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oms/client/BaseOmsClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/ActionScheduler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/OscActionFsmBase.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsCleanResourcesAction.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsModifyDataTaskAction.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsMonitorDataTaskAction.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsSwapTableAction.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleMapper.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/OnlineSchemaChangeFlowableTaskTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/oms/client/OmsClientTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/onlineschemachange/oscfms/OscActionFsmBaseTest.java
Labels: type-feature

#3590 security: add @SkipAuthorize annotation
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/ExecutorEndpointManager.java
Labels: security bug

#3592 fix(dlm): OOM occurs when a table's unique key contains nullable columns
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/AbstractDlmPreprocessor.java
Labels: type-bug

#3593 fix(schedule): wrong status when a schedule change is rejected
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/schedule/ScheduleChangeLogRepositoryTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleChangeLogRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleChangeLogService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java
Labels: type-bug

#3584 fix(schedule): multi-cloud oss config error when download log bases on obcloud
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduledTaskLoggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskFrameworkService.java
Labels: type-bug

#3597 fix(dlm): update rate limit failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java
Labels: type-bug

#3594 feat(vectordb): add a vectordb configuration for ai application
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/AbstractMetaDBMigrate.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/AbstractMigrate.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/VectorDBMigrate.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/vectordb/V2001PlaceholderMigrate.java
  server/odc-migrate/src/main/resources/migrate/vectordb/V_2_0_0__placeholder.sql
  server/odc-service/pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/config/BaseLockConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/MetaDBConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/MetaDBLockConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/VectorDBConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/VectorDBLockConfiguration.java
Labels: type-feature

#3608 fix(dlm): NPE when create task
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/AbstractDlmPreprocessor.java
Labels: type-bug

#3611 fix(sql-check): a specific sql will lead to npe
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLOfflineDdlExists.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleOfflineDdlExists.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
Labels: type-bug

#3614 refactor(schedule): add listByJobNames to ScheduleTaskService
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskService.java
Labels: type-refactor

#3607 feat(sql): add sql.execute.interceptor.enabled
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlExecuteInterceptorService.java
Labels: type-feature
