Repository oceanbase/odc, pull requests merged in 2024-04, with the labels that each got.

#2119 fix(taskframework): handle all preparing and running task to failed when task-framework be set disabled
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/JobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkEnabledProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/DefaultTaskFrameworkDisabledHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/TaskFrameworkDisabledHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskFrameworkService.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/dispatch/WebTaskDispatchChecker.java
Labels: enhancement, module-Task framework

#2090 feat(tag): add tag service
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/tag/DefaultTagService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/tag/DefaultTagServiceFacadeImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/tag/TagConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/tag/TagNames.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/tag/TagService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/tag/TagServiceFacade.java
Labels: type-feature

#2129 fix(taskframework): fix decrypt meta db password
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/EncryptorTest.java
  server/odc-service/pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCallerBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobEnvironmentEncryptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultTaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/JobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobEnvKeyConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskApplication.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/jasypt/AccessEnvironmentJasyptEncryptorConfigProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/jasypt/DefaultJasyptEncryptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/jasypt/DefaultJasyptEncryptorConfigProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/jasypt/JasyptEncryptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/jasypt/JasyptEncryptorConfigProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobProcessUpdateListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobUtils.java
Labels: type-bug, module-Task framework

#2135 fix(dlm):interrupt job failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
Labels: type-bug

#2137 fix(alter-schedule): correct the log routing path
  server/odc-server/src/main/resources/log4j2.xml
Labels: type-bug

#2142 fix(partition-plan): migrate useless partition plan table config
  server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V42417HistoricalPartitionPlanMigrateTest.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V42417HistoricalPartitionPlanMigrate.java
Labels: type-bug

#2141 fix(taskframework): refresh entity from database after update destroy time
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_4_12__update_system_config.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultTaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/DefaultTaskFrameworkDisabledHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#2148 fix(log): correct the log routing path
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/AlterScheduleTask.java
Labels: type-bug

#2152 build: delete useless github workflow configuration file
  .github/workflows/build_image_for_test.yaml
Labels: type-build

#2154 docs: fix v4.2.4 changelog for english language
  CHANGELOG.md
Labels: documentation

#2153 fix(taskframework): load log configuration NPE in task pod
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCallerBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskApplication.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobUtils.java
Labels: type-bug

#2158 fix(partition-plan): failed to migrate historical partition plan data
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V42417HistoricalPartitionPlanMigrate.java
Labels: type-bug

#2159 builds: upgrade odc version
  .gitmodules
  distribution/odc-server-VER.txt
  pom.xml
  server/3rd-party/Libinjection/pom.xml
  server/integration-test/pom.xml
  server/odc-common/pom.xml
  server/odc-core/pom.xml
  server/odc-migrate/pom.xml
  server/odc-server/pom.xml
  server/odc-service/pom.xml
  server/odc-test/pom.xml
  server/plugins/connect-plugin-api/pom.xml
  server/plugins/connect-plugin-doris/pom.xml
  server/plugins/connect-plugin-mysql/pom.xml
  server/plugins/connect-plugin-ob-mysql/pom.xml
  server/plugins/connect-plugin-ob-oracle/pom.xml
  server/plugins/connect-plugin-oracle/pom.xml
  server/plugins/pom.xml
  server/plugins/sample-plugin-api/pom.xml
  server/plugins/sample-plugin/pom.xml
  server/plugins/schema-plugin-api/pom.xml
  server/plugins/schema-plugin-doris/pom.xml
  server/plugins/schema-plugin-mysql/pom.xml
  server/plugins/schema-plugin-ob-mysql/pom.xml
  server/plugins/schema-plugin-ob-oracle/pom.xml
  server/plugins/schema-plugin-odp-sharding-ob-mysql/pom.xml
  server/plugins/schema-plugin-oracle/pom.xml
  server/plugins/task-plugin-api/pom.xml
  server/plugins/task-plugin-doris/pom.xml
  server/plugins/task-plugin-mysql/pom.xml
  server/plugins/task-plugin-ob-mysql/pom.xml
  server/plugins/task-plugin-ob-oracle/pom.xml
  server/plugins/task-plugin-oracle/pom.xml
  server/starters/desktop-starter/pom.xml
  server/starters/pom.xml
  server/starters/web-starter/pom.xml
Labels: type-build

#2160 fix(web-framework): swagger-ui.html page 404 notfound
  server/odc-server/pom.xml
Labels: type-docs

#2169 fix(taskframework): dlm task show log not exists
  server/odc-server/src/main/resources/log4j2-task.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/logger/LoggerService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/task/BaseTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/DefaultTaskFrameworkDisabledHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/HttpUtil.java
Labels: type-bug

#2179 fix(pl-debug): make timeout settings can be overwritten by session init script
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggeeSession.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/DebuggerSession.java
Labels: type-bug

#2184 fix(db-browser): failed to listTables when lack mysql schema permissions
  libs/db-browser/pom.xml
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  pom.xml
Labels: type-bug

#2194 fix(security):horizontal privilege escalation issue of getDatabase interface
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
Labels: type-bug, security bug

#2198 fix(configuration): add Configuration Consumer for UserConfigService
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionTestingTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
Labels: type-bug

#2166 feat(logicaldatabase): supports automatic recognition of logical tables and logical table expression generation
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableFinderTest.java
  server/integration-test/src/test/resources/connection/obmysql/create.sql
  server/integration-test/src/test/resources/connection/obmysql/drop.sql
  server/integration-test/src/test/resources/connection/obmysql/verify.yml
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableFinder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableRecognitionUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/model/DataNode.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/model/LogicalDatabase.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/model/LogicalTable.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableRecognitionUtilsTest.java
  server/odc-service/src/test/resources/logicaldatabase/logical_table_identification.yaml
Labels: type-feature

#2192 feat(connect): support connect backup instance
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DefaultConnectionAdapter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/CloudConnectionConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstanceRoleType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBTenant.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/TestConnectionReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/DruidDataSourceFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/initializer/BackupInstanceInitializer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/initializer/DataSourceInitScriptInitializer.java
Labels: type-feature

#2214 fix(connection): add version check before set weak read consistency
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/initializer/BackupInstanceInitializer.java
Labels: type-bug

#2217 fix(tag): can‘t find tagServiceFacade
  server/odc-service/src/main/java/com/oceanbase/odc/config/TagConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/tag/DefaultTagServiceFacadeImpl.java
Labels: type-bug

#2187 fix(taskframework): pending pod timeout after exceed one hour
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/NativeK8sClientTest.java
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/DefaultK8sJobResponse.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobResponse.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/NativeK8sJobClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/PodConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/PodStatus.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/K8sProperties.java
Labels: type-bug

#2155 feat(object-search): persistence and service layer implementation
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/dbobject/DBColumnRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/dbobject/DBObjectRepositoryTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/ConnectionConfigServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/DatabaseServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/db/DBSchemaIndexServiceTest.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_0_2__add_object_search.sql
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBObjectIndexController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseSpecs.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dbobject/DBColumnEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dbobject/DBColumnRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dbobject/DBObjectEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dbobject/DBObjectRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/model/Project.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/Database.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/model/DBObjectSyncStatus.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/model/OdcDBColumn.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/model/OdcDBObject.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/model/QueryDBObjectParams.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/model/QueryDBObjectResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/model/SyncDBObjectReq.java
Labels: type-feature, priority-medium, module-Database object

#2209 fix(security): horizontal privilege escalation issue of getOscDatabaseInfo interface
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
Labels: type-bug

#2225 fix(tag): change default tag key
  server/odc-service/src/main/java/com/oceanbase/odc/service/tag/DefaultTagServiceFacadeImpl.java
Labels: type-bug

#2124 feat(ob-sql-parser): upgrade antlr g4 for oceanbase v4.3.0
  libs/ob-sql-parser/pom.xml
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLCreateIndexFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLCreateTableFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLExpressionFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLIndexOptionsFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLPartitionFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleCreateIndexFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleCreateTableFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OraclePartitionFactory.java
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBLexer.g4
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBParser.g4
  libs/ob-sql-parser/src/main/resources/oboracle/sql/OBLexer.g4
  libs/ob-sql-parser/src/main/resources/oboracle/sql/OBParser.g4
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/OBMySQLParserTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLCreateTableFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLExpressionFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLPartitionFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/OraclePartitionFactoryTest.java
  pom.xml
Labels: type-feature

#2221 refactor(osc): modify i18n messages for white list
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
Labels: type-refactor

#2227 fix(permission): permission error message is not readable
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ConnectionPermission.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/DatabasePermission.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/PrivateConnectionPermission.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ResourcePermission.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ResourceRoleBasedPermission.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
Labels: type-bug

#2216 feat(resultset): support gis datatype for ob oracle mode
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/DefaultJdbcRowMapper.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/execute/mapper/OBOracleGeometryMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dml/converter/DataConverters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dml/converter/OBOracleGeometryConverter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/rollbackplan/RollBackPlanJdbcRowMapper.java
Labels: type-feature

#2224 enhancement(connection): stop synchronizing databases whose cluster no longer exists
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
Labels: enhancement

#2232 feat(datatype): update odc_version_diff_config for ob oracle SDO_GEOMETRY datatype
  server/odc-migrate/src/main/resources/migrate/common/R_2_0_0__initialize_version_diff_config.sql
Labels: type-feature

#2199 enhancement(log):opt scheduled task log
  server/odc-server/src/main/resources/log4j2.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/ScheduleTaskContextHolder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/PartitionPlanJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java
Labels: enhancement

#2242 fix(taskframework): alarm notification is not effective
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyExecutorJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#2248 builds: fix failed to install pnpm
  .github/workflows/build_artifact.yaml
  .github/workflows/build_daily.yaml
  .github/workflows/build_release.yaml
  distribution/docker/odc-build/create_node_env.sh
  script/functions.sh
Labels: type-build

#2233 enhancement(schedule): terminate the schedule if the database does not exist.
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcTriggerListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: enhancement

#1848 feat(multiple databases changes): add new feature for multiple database changes
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_0_3__add_databasechange_changingorder_template.sql
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ConnectSessionController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DatabaseChangeController.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/TaskController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/databasechange/DatabaseChangeChangingOrderTemplateEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/databasechange/DatabaseChangeChangingOrderTemplateRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/DatabaseChangeChangingOrderTemplateService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/model/CreateDatabaseChangeChangingOrderReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/databasechange/model/QueryDatabaseChangeChangingOrderResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/MultipleSqlCheckReq.java
Labels: type-feature

#2210 enhancement(task):increase the number of concurrent tasks from 10 to 30
  server/odc-server/src/main/resources/data.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/config/QuartzConfiguration.java
Labels: enhancement

#2253 fix(bastion): could not access SQL console when using OAuth for account integration
  server/integration-test/src/test/java/com/oceanbase/odc/service/collaboration/ProjectServiceTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/iam/UserServiceTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ProjectController.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/HookConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/UserEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/model/QueryProjectParams.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/CustomAuthenticationSuccessHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/User.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/SsoUserDetailService.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/bastion/BastionUserDetailService.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/play/PlaysiteUserDetailService.java
Labels: type-bug, priority-high, module-Bastion integration

#2255 fix(taskframework): optimize flowable transaction manager
  server/odc-service/src/main/java/com/oceanbase/odc/config/BaseFlowableConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/DefaultFlowableConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/ForeignKeyChecksFilter.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/MetaDBConfiguration.java
  server/starters/desktop-starter/src/main/java/com/oceanbase/odc/config/DesktopFlowableConfiguration.java
Labels: type-bug, enhancement

#2211 enhancement(jpa): add json type
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/jpa/JsonExampleEntity.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/jpa/JsonExampleRepository.java
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/jpa/JsonTypeTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/jpa/type/JsonType.java
Labels: enhancement

#2271 security: test masking using rounding algorithm may cause denial of service (DoS) risk
  server/odc-common/src/main/java/com/oceanbase/odc/common/security/OdcBigDecimalChecker.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/MaskingAlgorithmService.java
Labels: priority-high, security bug

#2269 fix(dlm): custom target table names invalid in non-task framework mode
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DlmTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
Labels: type-bug

#2272 fix(flow): cancel pending task cause "Some tasks is not found"
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowInstanceConfigurer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowTaskInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/FlowTaskCallBackApprovalService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/RuntimeTaskConstants.java
Labels: type-bug

#2279 fix(dlm): rollback task failed when customizing target table names.
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
Labels: type-bug

#2281 feat(dlm):upgrade dlm sdk to 1.1.1
  pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
Labels: type-feature

#2268 fix(taskframework): running task log is not found when close task-framework && send mistake alarm
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/task/JobRepositoryTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/JobRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/exception/JobException.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/DefaultTaskFrameworkDisabledHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyExecutorJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug, enhancement

#2287 fix(partition-plan): failed to start up a partition plan on oceanbase before 3.x
  libs/db-browser/pom.xml
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/BaseOBMySQLLessThan2277SchemaAccessor.java
  libs/db-browser/src/main/resources/schema/sql/mysql/mysql_5_6_x.yaml
  libs/db-browser/src/main/resources/schema/sql/mysql/mysql_5_7_x.yaml
  libs/db-browser/src/main/resources/schema/sql/obmysql/obmysql_1_4_79.yaml
  libs/db-browser/src/main/resources/schema/sql/obmysql/obmysql_2_2_5x.yaml
  libs/db-browser/src/main/resources/schema/sql/obmysql/obmysql_2_2_76.yaml
  libs/db-browser/src/main/resources/schema/sql/obmysql/obmysql_3_x.yaml
  libs/db-browser/src/main/resources/schema/sql/obmysql/obmysql_4_0_x.yaml
  libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_3_x.yaml
  pom.xml
Labels: type-bug

#2288 fix(ticket): access denied when approve a ticket
  server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java
Labels: type-bug

#2289 fix(objectstorage): wrong log/database change/rollback plan download URLs if cloud storage is enabled
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/RollbackPlanRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/util/DatabaseChangeOssUrlCache.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/util/TaskDownloadUrlsProvider.java
Labels: type-bug

#2292 fix(taskframework): column 'job_id' cannot be null
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#2296 fix(dlm):get table ddl failed in oracle mode
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
Labels: type-bug

#2299 fix(taskframework): optimize log
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/DefaultTaskFrameworkDisabledHandler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DestroyExecutorJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/StartPreparingJob.java
Labels: enhancement

#2246 refactor(sql-execute): refactor SQL async execute api into streaming return
  server/integration-test/src/test/java/com/oceanbase/odc/service/session/NlsFormatInterceptorTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionConstants.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/session/ConnectionSessionUtil.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/OBUtils.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ConnectSessionController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/util/ConnectionInfoUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/DataMaskingInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/ExternalSqlInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/OBExecutionListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/OdcStatementCallBack.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/SqlExecutionListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/BaseTimeConsumingInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/DatabasePermissionInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/NlsFormatInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlExecuteInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlExecuteInterceptorService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SwitchDatabaseInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/AsyncExecuteContext.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/AsyncExecuteResultResp.java
Labels: type-feature, module-sql execution, module-Monitoring and diagnosis

#2274 feat(logicaldatabase): logical table expression parser
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/SyntaxErrorException.java
  pom.xml
  server/integration-test/src/test/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableServiceTest.java
  server/integration-test/src/test/resources/connection/logicaldatabase/invalid_logical_table_expression_resolve.yaml
  server/integration-test/src/test/resources/connection/logicaldatabase/valid_logical_table_expression_resolve.yaml
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
  server/odc-service/pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/model/DataNode.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/BadExpressionException.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/BaseLogicalTableExpression.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/BaseRangeExpression.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/ConsecutiveSliceRange.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/DefaultLogicalTableExpressionParser.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/EnumRange.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/LogicalTableExpression.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/LogicalTableExpressionParseUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/LogicalTableExpressionVisitor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/LogicalTableExpressions.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/LogicalTableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/SchemaExpression.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/SteppedRange.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/parser/TableExpression.java
  server/odc-service/src/main/resources/antlr/logicaldatabase/LogicalTableExpression.g4
Labels: type-feature
