Repository oceanbase/odc, pull requests merged in 2025-03, with the labels that each got.

#4238 feat(configarchive): support acvhive shchedule config
  server/odc-common/src/main/java/com/oceanbase/odc/common/security/EncryptAlgorithm.java
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/FileZipper.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/common/util/OdcFileUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/ExportConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/Exporter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/Extractor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/impl/JsonExtractor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/impl/LocalJsonExporter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/model/Encryptable.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/model/ExportConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/model/ExportProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/model/ExportRowDataAppender.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/model/ExportRowDataMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/model/ExportRowDataReader.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/model/ExportedData.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/model/ExportedFile.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/model/ExportedZipFileBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/OrganizationAuthenticationInterceptor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/model/OssConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleExportFacade.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/ScheduleTaskExporter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/ArchiveDataSource.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/ArchiveDatabase.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/BaseScheduleRowData.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/DataArchiveScheduleRowData.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/DataDeleteScheduleRowData.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/exporter/LocalJsonExporterTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/objectstorage/EncryptAlgorithmTest.java
Labels: type-feature

#4254 fix(sync-table): throw NPE when target table is not exist
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
Labels: type-bug

#4236 feat(database): Sync current user database objects when grouping databases
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBObjectIndexController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java
Labels: type-feature

#4232 feat(database): supports query database by tenantName、clusterNam and dataSourceName
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/Verify.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataBaseController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseSpecs.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/QueryDatabaseParams.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/InnerQueryConnectionParams.java
Labels: type-feature

#4259 feat(export):schedule export support sqlPlain and PartitionPlan
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/impl/LocalJsonExporter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/exporter/model/ExportRowDataMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/ScheduleTaskExporter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/DataArchiveScheduleRowData.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/DataDeleteScheduleRowData.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/ExportedDataSource.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/ExportedDatabase.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/PartitionPlanScheduleRowData.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/archiverist/model/SqlPlanScheduleRowData.java
Labels: type-feature

#4266 fix(task): doStopV2 scheduler not in transaction exception
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/enums/JobStatus.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/DoStopJobV2.java
Labels: type-bug

#4269 fix(table permission): When executing sql in an sql window, a permission check on a table involves a database that does not exist
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java
Labels: type-bug

#4252 feat(partition-plan): optimized character types partition for automatic partitioning
  server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/partitionplan/invoker/create/TimeStringIncreasePartitionExprGenerator.java
  server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/partitionplan/model/FieldType.java
  server/plugins/task-plugin-api/src/main/java/com/oceanbase/odc/plugin/task/api/partitionplan/model/TimeStringIncreaseGeneratorConfig.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/OBMySQLAutoPartitionExtensionPoint.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/invoker/create/OBMysqlTimeStringPartitionExprGenerator.java
  server/plugins/task-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/OBOracleAutoPartitionExtensionPoint.java
  server/plugins/task-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/task/oboracle/partitionplan/invoker/create/OBOracleTimeStringPartitionExprGenerator.java
Labels: type-feature

#4276 feat(schedule): add schedule task import api
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ImportController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ImportDatabaseView.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ImportScheduleTaskView.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ImportTaskResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ScheduleNonImportableType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/model/ScheduleTaskImportRequest.java
Labels: type-feature

#4278 feat(task): let task v2 force start executor in pull mode
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/StartPreparingJobV2.java
Labels: type-feature

#4275 feat(config): add ddl 4 create table and load meta data
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_4_5__config_organization_configuration.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/OrganizationConfigKeys.java
  server/odc-service/src/main/resources/config-meta/organization-config-meta.yml
Labels: type-feature

#4279 fix(task): taskResult event not send before task finished
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/PullTaskResultJobV2.java
Labels: type-bug

#4282 fix(task): cancel task may not wait log meta uploaded
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/enums/JobStatus.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/StdJobScheduler.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/PullTaskResultJobV2.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#4286 fix(task): correct executorIdenfifier port to odc server port for process mode
  server/odc-server/src/main/java/com/oceanbase/odc/supervisor/runtime/SupervisorApplication.java
  server/odc-server/src/test/java/com/oceanbase/odc/supervisor/SupervisorApplicationTest.java
  server/odc-server/src/test/java/com/oceanbase/odc/supervisor/runtime/TaskSupervisorServerTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ExecutorIdentifier.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ExecutorInfo.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCallerBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/dummy/LocalMockK8sJobClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/resource/LocalProcessResource.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/DoFinishJobV2.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/supervisor/DefaultJobEventListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/supervisor/TaskSupervisor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/supervisor/endpoint/ExecutorEndpoint.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/supervisor/proxy/LocalTaskSupervisorProxy.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobUtils.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/task/schedule/daemon/v2/DaemonV2TestBase.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/task/schedule/daemon/v2/StartPreparingJobV2Test.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/task/supervisor/TaskSupervisorTest.java
Labels: type-bug

#4284 feat(script): add batch download scripts method
  server/integration-test/src/test/java/com/oceanbase/odc/service/script/ScriptServiceWithLocalTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/ScriptController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/script/ScriptService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/script/util/ScriptUtils.java
Labels: type-feature

#4292 feat(dlm): supports setting a CPU limit
  pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataDeleteParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataDeleteJob.java
Labels: type-feature

#4294 fix(Script): only one script download when select many same name scripts
  server/integration-test/src/test/java/com/oceanbase/odc/service/script/ScriptServiceWithLocalTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/script/ScriptService.java
Labels: type-bug

#4295 fix(import): schedule import not have default name and lack of migrate sql
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_10__add_file_import_history.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/ScheduleTaskImporter.java
Labels: type-bug

#4300 fix(migrate): fix script
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_10__add_file_import_history.sql
Labels: type-bug

#4297 feat(task): adjust http server netty thread pool to fix size
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/net/HttpServer.java
Labels: type-feature

#4305 security: upgrade tomcat version to 9.0.98
  pom.xml
Labels: security bug

#4302 feat(materialized view): add implement of materialized view for ob oracle
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBMaterializedViewRefreshMethod.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBMaterializedViewRefreshSchedule.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessorFactory.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleBetween410And432SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleBetween432And4351SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/template/BaseMViewTemplate.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/template/mysql/MysqlMViewTemplate.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/template/oracle/OracleMViewTemplate.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/util/AbstractOracleDataDictTableNames.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/util/OracleDataDictTableNames.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBOracleSchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/template/MysqlMViewTemplateTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/template/OracleMViewTemplateTest.java
  libs/db-browser/src/test/resources/table/oboracle/dropMV.sql
  libs/db-browser/src/test/resources/table/oboracle/testMVDDL.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBMaterializedViewService.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLMViewExtension.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParser.java
  server/plugins/schema-plugin-ob-mysql/src/test/java/com/oceanbase/odc/plugin/schema/obmysql/parser/OBMySQLGetDBTableByParserTest.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/OBOracleMViewExtension.java
  server/plugins/schema-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParser.java
  server/plugins/schema-plugin-ob-oracle/src/test/java/com/oceanbase/odc/plugin/schema/oboracle/parser/OBOracleGetDBTableByParserTest.java
  server/plugins/schema-plugin-ob-oracle/src/test/resources/parser/dropMV.sql
  server/plugins/schema-plugin-ob-oracle/src/test/resources/parser/testGetPartitionInMViewByParser.sql
Labels: type-feature

#4308 fix(database): listing interface did not display datasource attributes
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
Labels: type-bug

#4309 fix(export): Incorrect check export permission
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/export/ScheduleTaskExporter.java
Labels: type-bug

#4307 fix(tripartite): Improve the query efficiency of precheck
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_9__add_index.sql
Labels: type-bug

#4311 fix(obcloud):filter obcloud tenants when status is not connected
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBTenantStatus.java
Labels: type-bug

#4312 fix(task): force update job last_heart_time once when job started
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/JobRepository.java
Labels: type-bug

#4314 fix(task): find execute timeout task to destroy
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
Labels: type-bug

#4319 fix(permission): authentication will wrongly fail when resource ids are the same but resource types are different
  server/integration-test/src/test/java/com/oceanbase/odc/service/iam/ResourceRoleBasedPermissionExtractorTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleBasedPermissionExtractor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
Labels: type-bug

#4317 feat(materialized view): materialized view adapt to existing functions in odc
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/MysqlModeSqlParserListener.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/parser/listener/OracleModeSqlParserListener.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLBetween400And432SchemaAccessor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/ParserUtilTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/parser/SqlParserTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/template/MysqlMViewTemplateTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/template/OracleMViewTemplateTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBIdentitiesService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/feature/VersionDiffConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/ApplyTablePermissionPreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/SqlExecuteResult.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java
  server/odc-service/src/test/resources/session/test_db_schema_extractor.yaml
Labels: type-feature

#4320 fix(alarm): Listener may not load
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmService.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmUtils.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java
Labels: type-bug

#4324 fix(alarm): Listener may not load
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmService.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/alarm/AlarmUtils.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/OdcServer.java
Labels: type-bug

#4323 feat(materialized view):data desensitization supports materialized views
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/constant/Statements.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLBetween432And4351SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/postgre/PostgresSchemaAccessor.java
  libs/db-browser/src/main/resources/schema/sql/obmysql/obmysql_4_3_2_x.yaml
  libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_3_2_x.yaml
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBOracleSchemaAccessorTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/OdcConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/SensitiveColumnService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/DatabaseWithAllColumns.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/syncer/column/DBTableAndViewColumnSyncer.java
  server/plugins/schema-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/obmysql/OBMySQLTableExtension.java
Labels: type-feature

#4326 fix(schedule): support delete when datasource invalid
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java
Labels: type-bug
