Repository oceanbase/odc, pull requests merged in 2025-02, with the labels that each got.

#4201 fix(build): specify maven and jvm version fro aci
  .github/workflows/build_dev.yaml
Labels: type-build

#4190 fix(task): change DefaultResourceOperatorBuilder default resource match type
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/dlm/DlmTableUnitRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/task/JobRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/model/DetailLogicalTableResp.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/BaseJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ExecutorInfo.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/JobCallerBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/K8sJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ResourceIDUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/dispatch/ImmediateJobDispatcher.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/dummy/LocalMockK8sJobClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/resource/AbstractK8sResourceOperatorBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/resource/DefaultNativeK8sOperatorBuilder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/resource/K8sResourceOperator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/CheckRunningJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/ResourceManagerUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/ExecutorEndpointManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/TaskFrameworkService.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/resource/k8s/K8sResourceOperatorTest.java
Labels: type-bug

#4202 feat(taskframework): customized task submission
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleTaskConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractOdcJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/submitter/DefaultJobSubmitter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/submitter/JobSubmitter.java
Labels: type-feature

#4165 feat(dlm): response the comments on #4151
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ConnectType.java
  server/odc-server/src/main/resources/log4j2-task.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionEventPublisher.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionValidator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DefaultConnectionAdapter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/listener/UpsertFileSystemListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncTaskManager.java
Labels: type-feature

#4199 security: remove useless sshd-common dependence
  server/odc-server/pom.xml
Labels: enhancement

#4209 build: merge dev/4.3.3 into main
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ConnectType.java
  server/odc-server/pom.xml
  server/odc-server/src/main/resources/log4j2-task.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionEventPublisher.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionValidator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/DefaultConnectionAdapter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/listener/UpsertFileSystemListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaSyncTaskManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/executor/TaskDescription.java
Labels: type-build

#4213 fix(permission): 'AccessDenied' happens when project owners try swapping tables in an osc task
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
Labels: type-bug

#4214 fix(task): process mode not invoke destroy action when job is canceled
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/DoCancelingJob.java
Labels: type-bug

#4212 fix(schedule): unreasonable parameter validation
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionTesting.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/utils/DataArchiveConditionUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#4217 fix(task): sync report taskResult call
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskMonitor.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskReporter.java
Labels: type-bug

#4219 fix(dlm): correct status when task is terminated
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/dataarchive/DataArchiveTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/terminate/DLMTerminateProcessor.java
Labels: type-bug

#4216 refactor(git): remove the unused git module
  server/integration-test/src/test/java/com/oceanbase/odc/service/git/GitIntegrationServiceTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/GitIntegrationController.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/git/GitRepoRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/git/GitRepoStageRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/git/GitRepositoryEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/git/GitRepositoryStageEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/GitClientOperator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/GitIntegrationService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/FileChangeType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/GitDiff.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/GitIntegrationProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/GitProvider.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/GitRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/GitRepositoryMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/GitStatus.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/QueryGitRepositoryParams.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/RepoState.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/model/VcsProvider.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/repo/GitRepositoryManager.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/vcs/GithubEFacadeImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/vcs/GithubFacadeImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/vcs/GitlabEFacadeImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/vcs/GitlabFacadeImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/vcs/VcsFacade.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/vcs/VcsFacadeMapper.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/git/GitClientOperatorTest.java
Labels: type-feature

#4220 fix(osc): updateRateLimiterConfig npe issue
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/OscService.java
Labels: type-bug

#4222 fix(config): add task enabled configurations
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_7__update_system_config.sql
Labels: type-bug

#4221 fix(flowable): flowable task may be blocked
  server/odc-service/src/main/java/com/oceanbase/odc/config/ScheduleConfiguration.java
Labels: type-bug

#4211 adaption(obcloud): deploy new independent ODC 433 cluster for OBCloud
  server/integration-test/src/test/java/com/oceanbase/odc/AuthorityTestEnv.java
  server/integration-test/src/test/java/com/oceanbase/odc/authority/SingleOrganizationResourceValueProviderTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/authority/BaseValueFilterSecurityManager.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/MultiOrganizationResource.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/OrganizationResource.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/SingleOrganizationResource.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/CloudMetadataController.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/BeanConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/OrganizationRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/UserOrganizationRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/automation/model/AutomationRule.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/environment/model/Environment.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/model/Project.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/CloudMetadataClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/model/Database.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/CloudConnectionConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/ConnectionConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstanceType.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBTenant.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBTenantStatus.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/TestConnectionReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/model/Table.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/MaskingAlgorithm.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/SensitiveColumn.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/datasecurity/model/SensitiveRule.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/BaseFlowNodeInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/instance/FlowInstance.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/HorizontalDataPermissionValidator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/OrganizationIsolatedValueProvider.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/Organization.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/Role.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/User.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/model/IntegrationConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/approval/model/ApprovalFlowConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/model/Rule.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/model/Ruleset.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/resourcegroup/ResourceGroup.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleDetailRespHist.java
  server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/datatransfer/factory/BaseParameterFactory.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/saml/DefaultSamlUserService.java
Labels: type-refactor

#4224 fix(osc): add uid for oms updateConfigRequest
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsModifyDataTaskAction.java
Labels: type-bug

#4218 feat(sql-plan): sync schedule description to subtask
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java
Labels: type-feature

#4225 fix(dlm): upgrade sdk to 1.2.1
  pom.xml
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_8__alter_task_generator.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/AbstractDlmJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/DlmTableUnitStatistic.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/dataarchive/DataArchiveTask.java
Labels: type-bug

#4203 fix(sql-execute): nls_format invalidation
  server/integration-test/src/test/java/com/oceanbase/odc/service/session/NlsFormatInterceptorTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/NlsFormatInterceptor.java
Labels: type-bug

#4231 build: fail to build artifact
  libs/db-browser/pom.xml
  libs/ob-sql-parser/pom.xml
  pom.xml
Labels: type-build

#4235 feat(osc): support drop column sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/model/OnlineSchemaChangeScheduleTaskParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/CreateGhostTableAction.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/OmsCreateDataTaskAction.java
Labels: type-feature

#4240 fix(pl debug):the username configured for new odp connections does not contain cluster names.
  server/odc-service/src/main/java/com/oceanbase/odc/service/pldebug/session/AbstractDebugSession.java
Labels: type-bug

#4243 feat(dlm): create temporary tables when data is archived to file system
  pom.xml
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/TaskStatus.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskContainer.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskMonitor.java
  server/odc-server/src/main/resources/data.sql
  server/odc-server/src/main/resources/log4j2-task.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DataArchiveTableConfig.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/model/DlmTableUnitParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DLMJobReq.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/DataArchivePreprocessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/dataarchive/DataArchiveTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/enums/JobStatus.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/state/JobStatusFsm.java
Labels: type-feature

#4245 fix(ob-sql-parser): adapt some syntax rules of ob435
  libs/db-browser/pom.xml
  libs/ob-sql-parser/pom.xml
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/mysql/MySQLTableOptionsFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/adapter/oracle/OracleTableOptionsFactory.java
  libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/createtable/TableOptions.java
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBLexer.g4
  libs/ob-sql-parser/src/main/resources/obmysql/sql/OBParser.g4
  libs/ob-sql-parser/src/main/resources/oboracle/sql/OBLexer.g4
  libs/ob-sql-parser/src/main/resources/oboracle/sql/OBParser.g4
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/MySQLCreateTableFactoryTest.java
  libs/ob-sql-parser/src/test/java/com/oceanbase/tools/sqlparser/adapter/OracleCreateTableFactoryTest.java
  pom.xml
Labels: type-bug

#4247 fix(sync-table): the default value is considered missing when it is whitespace
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/StringUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
Labels: type-bug
