Repository oceanbase/odc, pull requests merged in 2025-04, with the labels that each got.

#4327 feat(task): correct task timeout to endtime
  server/integration-test/src/test/java/com/oceanbase/odc/service/task/ProcessModeTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskMonitor.java
  server/odc-server/src/test/java/com/oceanbase/odc/agent/runtime/TaskMonitorTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/RollbackPlanRuntimeFlowableTaskCopied.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/LogicalDatabaseChangeJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/submitter/DefaultJobSubmitter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobParametersKeyConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/service/StdTaskFrameworkService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/state/JobStatusFsm.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/task/status/JobStatusFsmTest.java
Labels: type-feature

#4332 fix(schedule): the partition plan statistics are incorrect
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/InnerQueryFlowInstanceParams.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#4329 fix(partition-plan): partition plan invaild when delete table
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanService.java
Labels: type-bug

#4335 feat(session): support client session
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_4_9__remove_kill_sessesion_max_support_version.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
Labels: type-feature

#4322 feat(flow): Merges apply database or table permission flow instance
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/flow/MergeFlowInstanceTest.java
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/ObjectUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/PreCheckRuntimeFlowableTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/ApplyDatabaseParameter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/table/model/ApplyTableParameter.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/approval/ApprovalFlowConfigSelector.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/RiskDetectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/model/RiskLevelDescriber.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/precheck/PreCheckRiskLevel.java
Labels: type-feature

#4340 fix(flow): fix the partition plan subtask database change execution failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/OrganizationConfigUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeThread.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/DatabaseChangeParameters.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/SqlPlanJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/databasechange/DatabaseChangeTask.java
Labels: type-bug

#4337 feat(materialized view):mask container table and materialized view log display in 'listAllBases' controller
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBMaterializedViewController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBMaterializedViewService.java
Labels: type-feature

#4336 fix(sql check):There are no ob oracle and oracle options for sql check rule that unable to Judge affected rows
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java
Labels: type-bug

#4338 fix(schedule): landing page displayed number of partition plans enabled is incorrect
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleStat.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleTaskStat.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleTaskType.java
Labels: type-bug

#4351 fix(metadb): close save point if datasource is not odc metadb
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java
Labels: type-bug

#4350 security: upgrade tomcat from 9.0.98 to 9.0.99
  pom.xml
Labels: security bug

#4347 security: lack permission check when listing another user's resources
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
Labels: security bug

#4346 security: return error details when login failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/CustomAuthenticationFailureHandler.java
Labels: security bug

#4339 fix(audit): add intsance migrate audit meta data
  server/integration-test/src/test/java/com/oceanbase/odc/service/audit/AuditEventMapperTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/audit/AuditEventMetaMapperTest.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventAction.java
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventType.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/init-config/default-audit-event-meta.yml
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/AuditEventService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/model/AuditEventMeta.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/util/AuditEventMapper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/util/AuditEventMetaMapper.java
Labels: type-bug

#4349 fix(database): Supports synchronization of individual space to all current organization databases
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/connection/DatabaseRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java
Labels: type-bug

#4342 fix(sql check ): Getting the number of sql affected rows does not support the old ob version
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/AffectedRowCalculator.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/SqlCheckUtil.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/SqlAffectedRowsFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/Unable2JudgeAffectedRowsFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/BaseAffectedRowsExceedLimit.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/OracleAffectedRowsExceedLimit.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/MySQLCheckerTest.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java
Labels: type-bug

#4362 fix(db-browser):the ddl of produce has two semicolons
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
Labels: type-bug

#4356 enhancement(dlm): sort table by id
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/dataarchive/DataArchiveTask.java
Labels: enhancement

#4358 fix(Script): add duplicated filename tag before suffix of filename
  server/integration-test/src/test/java/com/oceanbase/odc/service/script/ScriptServiceWithLocalTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/script/ScriptService.java
Labels: type-bug

#4344 fix(riskLevel): the riskLevelDescriber under the two databases can be distinguished
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/flow/MergeFlowInstanceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/approval/ApprovalFlowConfigSelector.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/RiskDetectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/model/RiskLevelDescriberIdentifier.java
Labels: type-bug

#4354 enhancement(regulation): rename 'max-return-rows' rule-meta name and description
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml
  server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml
  server/odc-migrate/src/main/resources/migrate/common/V_4_2_3_10__adjust_sql_console_rules.sql
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/RuleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/ruleset/model/SqlConsoleRules.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/SessionSettingsService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlConsoleInterceptor.java
Labels: enhancement

#4370 fix(resource): let resource destroy concurrent safe
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceManager.java
Labels: type-bug

#4372 fix(flow): can view project when locate at applyDatabasePermission or applyTablePermission
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
Labels: type-bug

#4367 fix(flow): fix multiple database change task parameter incompleteness
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/MultipleDatabaseChangeParameters.java
Labels: type-bug

#4341 feat(config): Add a data source key configuration item in the organization configuration.
  server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V42013OAuth2ConfigMetaMigrateTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V4349OrganizationSecretMigrateTest.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V42013OAuth2ConfigMetaMigrate.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V4349OrganizationSecretMigrate.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/OrganizationConfigDAO.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/OrganizationRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/OrganizationConfigKeys.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/OrganizationConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/OrganizationConfigUtils.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/model/Configuration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionEncryption.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/encryption/EncryptionFacadeImpl.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/OrganizationService.java
  server/odc-service/src/main/resources/config-meta/organization-config-meta.yml
  server/odc-service/src/test/java/com/oceanbase/odc/service/config/OrganizationConfigMetaServiceTest.java
Labels: type-feature

#4374 enhancement(odc):update version of db-browser and ob-sql-parser
  libs/db-browser/pom.xml
  libs/ob-sql-parser/pom.xml
  pom.xml
Labels: enhancement

#4375 fix(objectstorage): response InvalidArgument error when download file from download presigned url of aws s3
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AmazonCloudClient.java
Labels: type-bug

#4373 fix(session): Supports fuzzy matching of table names and view names
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBMetadataController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBIdentitiesService.java
Labels: type-bug

#4379 fix(migrate): rename duplicate migrate file
  server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V43410OrganizationSecretMigrateTest.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V43410OrganizationSecretMigrate.java
Labels: type-bug

#4382 feat(materialized view):adapt to the latest ob4352 changes
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBOracleSchemaAccessorTest.java
Labels: type-feature

#4389 fix(objectstorage): response InvalidArgument error when download file from download presigned url of aws s3
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/client/AmazonCloudClient.java
Labels: type-feature

#4388 feat(ErrorCodes): add error code: GitPushRejectedNonFastForward for conflict occurred while pushing code to remote repository
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java
  server/odc-core/src/main/resources/i18n/ErrorMessages.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/ErrorMessages_zh_TW.properties
Labels: type-feature

#4386 fix(db browser):desc view without schema
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
Labels: type-bug

#4369 fix(riskLevel): add default detect rule condition that is task type equals APPLY_TABLE_PERMISSION
  server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V43411RectifyDetectRuleOfTaskTypeMigrateTest.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V42415AddDefaultRiskDetectRules.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V43411RectifyDetectRuleOfTaskTypeMigrate.java
Labels: type-bug

#4371 fix(flow): flow mapper not skip auth
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
Labels: type-bug

#4391 documentation(pom):add developer in db-browser and ob-sql-parser
  libs/db-browser/pom.xml
  libs/ob-sql-parser/pom.xml
Labels: documentation

#4395 fix(config): fix organization config record information is incomplete
  server/integration-test/src/test/java/com/oceanbase/odc/metadb/config/OrganizationConfigDAOTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/config/OrganizationConfigDAO.java
Labels: type-bug

#4401 fix(db-browser): Add '%' when to like table name
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleBetween410And432SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
Labels: type-bug

#4402 fix(schedule): Return the triggerStrategy of schedule
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleOverviewHist.java
Labels: type-bug

#4407 fix(flow): apply project tickets not shown when it's under approval
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/core/LogicalTableFinder.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
Labels: type-bug

#4412 fix(task): k8s parse resource identifier failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/resource/K8sPodResource.java
  server/odc-service/src/test/java/com/oceanbase/odc/service/task/resource/K8sPodResourceTest.java
Labels: type-bug

#4406 enhancement(materialized view):Display all the databases when creating materialized views or views
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBMaterializedViewService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBViewService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/model/DatabaseAndMVs.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/model/DatabaseAndViews.java
Labels: enhancement

#4411 fix(security): Approving flowInstance can over step authority
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/flow/UserTaskInstanceRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/ApprovalPermissionService.java
Labels: security bug

#4394 enhancement(config): organization configuration adaptive external integration
  server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V42013OAuth2ConfigMetaMigrateTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/migrate/jdbc/common/V43412OrganizationSecretMigrateTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/git/GitIntegrationServiceTest.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V42013OAuth2ConfigMetaMigrate.java
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/V43412OrganizationSecretMigrate.java
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_4_10__alter_iam_organization_add_column.sql
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/git/GitRepoRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/OrganizationEntity.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/integration/IntegrationRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/OrganizationConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/GitIntegrationService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/OrganizationService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/IntegrationService.java
Labels: enhancement

#4409 fix(db-browser): Support search table or view by identityNameLike
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/ODPOBMySQLSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleBetween410And432SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/postgre/PostgresSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/util/MySQLSqlBuilder.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/util/OracleSqlBuilder.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/util/SqlBuilder.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/MySQLNoLessThan5700SchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OracleSchemaAccessorTest.java
  server/integration-test/src/test/java/com/oceanbase/odc/service/db/DBIdentitiesServiceTest.java
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DBMetadataController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBIdentitiesService.java
Labels: type-bug

#4413 enhancement(config): adaptive multi cloud
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/OrganizationConfigService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/git/GitIntegrationService.java
Labels: enhancement

#4414 fix(audit): Fix the database operation type in the audit event that does not record database info
  server/odc-service/src/main/java/com/oceanbase/odc/service/audit/AuditEventAspect.java
Labels: type-bug
