Repository oceanbase/odc, pull requests merged in 2025-05, with the labels that each got.

#4415 fix(db browser): fix the syntax error of fuzzy query
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/doris/DorisSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLBetween432And4352SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/OBMySQLSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleBetween432And4352SchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OracleSchemaAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/postgre/PostgresSchemaAccessor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/MySQLNoLessThan5700SchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBMySQLSchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OBOracleSchemaAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/OracleSchemaAccessorTest.java
Labels: type-bug

#4420 fix(db browser):failed to get table in doris
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTableColumn.java
Labels: type-bug

#4416 fix(session): fix SQL execute generate result failed caused by material view
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/model/SqlExecuteResult.java
Labels: type-bug, enhancement

#4418 fix(schedule): To stat the count of all state schedule for each scheduleType type
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/schedule/ScheduleRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/model/InnerQueryFlowInstanceParams.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/QueryScheduleStatParams.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/model/ScheduleStat.java
Labels: type-bug

#4423 doc: 4.3.4 changelog init
  CHANGELOG-zh-CN.md
  CHANGELOG.md
  CHANGELOG.rst
Labels: type-docs

#4426 fix(dlm): upgrade sdk version to 1.2.5
  pom.xml
Labels: type-bug

#4429 fix(dlm): upgrade sdk version to 1.2.3.1
  pom.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMJobStore.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/executor/AbstractQuartzJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveDeleteJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/job/DataArchiveRollbackJob.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/listener/DefaultJobTerminateListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/processor/terminate/DLMTerminateProcessor.java
Labels: type-bug

#4430 fix(object): support awscn
  server/odc-service/src/main/java/com/oceanbase/odc/service/objectstorage/cloud/CloudResourceConfigurations.java
Labels: type-feature

#4432 fix(objects): support awscn
  server/odc-service/src/main/java/com/oceanbase/odc/service/loaddata/model/ObjectStorageConfig.java
Labels: type-feature

#4438 fix(scheudle): fix cycle dependence
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#4417 fix(task): correct supervisor start job with wrong mode
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskMonitor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobEnvKeyConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/DoFinishJobV2.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/StartPreparingJobV2.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobUtils.java
Labels: type-bug

#4410 feat(task): let supervisor pod release back time configureable
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultTaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/resource/manager/strategy/k8s/K8SResourceManageStrategy.java
Labels: type-feature

#4435 fix(flow): flow mapper not skip auth
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
Labels: type-bug

#4359 feat(config): metadb jdbc url support configure
  server/odc-server/src/main/resources/config/application.yml
  server/odc-server/src/main/resources/config/bootstrap.yml
Labels: type-feature

#4442 fix(obcloud): add method listInstancesByProjectId for CloudMetadataClient
  server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/CloudMetadataController.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/CloudMetadataClient.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstance.java
Labels: type-bug

#4441 fix(connection): The Oracle datasource's connect/socket timeout is not set correctly which may cause to connection leak.
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
Labels: type-bug

#4443 fix(config): add user default configurations consumers
  server/integration-test/src/test/java/com/oceanbase/odc/service/config/UserConfigServiceTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/config/UserConfigService.java
Labels: type-bug

#4444 fix(obcloud): add 'scenario' field in OBInstance class
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/model/OBInstance.java
Labels: type-bug

#4449 fix(osc): remove increment progress check
  server/odc-service/src/main/java/com/oceanbase/odc/service/onlineschemachange/oscfms/action/oms/ProjectStepResultChecker.java
Labels: type-bug

#4450 fix(flowable): fix circular dependency
  server/odc-service/src/main/java/com/oceanbase/odc/service/partitionplan/PartitionPlanScheduleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/util/BatchSchedulePermissionValidator.java
Labels: type-bug

#4452 fix(permissoin): add permission check when creating schedule tasks
  server/odc-service/src/main/java/com/oceanbase/odc/service/permission/DBResourcePermissionHelper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java
Labels: type-bug

#4458 merge: merge 4.3.x task fix to 4.3.4
  server/odc-server/src/main/java/com/oceanbase/odc/agent/runtime/TaskMonitor.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultSpringJobConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/DefaultTaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/config/TaskFrameworkProperties.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/constants/JobEnvKeyConstants.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/resource/manager/strategy/k8s/K8SResourceManageStrategy.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/DoFinishJobV2.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/schedule/daemon/v2/StartPreparingJobV2.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/util/JobUtils.java
Labels: type-bug
