Repository oceanbase/odc, pull requests merged in 2025-01, with the labels that each got.

#4113 fix(migrate): complete data for connect_database.connect_type
  server/odc-migrate/src/main/resources/migrate/common/V_4_3_3_6__complete_connect_database.sql
Labels: type-bug

#4116 fix(permission): global project role cannot see approvable tickets
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/model/Project.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/PermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
Labels: type-bug

#4115 fix(db):miss quote of pl name which contains @ causes pl edit failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBPLModifyHelper.java
Labels: type-bug

#4117 fix(permission): global project roles cannot view/execute/approve tickets
  server/odc-service/src/main/java/com/oceanbase/odc/config/BaseAuthConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/config/DefaultAuthConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/metadb/iam/PermissionRepository.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/ApprovalPermissionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowPermissionHelper.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowTaskInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/factory/FlowResponseMapperFactory.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/listener/ApprovalStatusNotifyListener.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/GlobalResourceRoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/DefaultAuthorizationFacade.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/auth/ResourceRoleAuthorizer.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/model/UserResourceRole.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/util/GlobalResourceRoleUtil.java
Labels: type-bug

#4122 fix(structure-compare):the structure synchronization task cannot be initiated when the structure comparison task is not created by yourself
  server/odc-service/src/main/java/com/oceanbase/odc/service/structurecompare/StructureComparisonService.java
Labels: type-bug

#4114 fix(session): kill session may lead npe
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
Labels: type-bug

#4125 fix(task): log4j set failed for task
  server/odc-server/src/main/resources/log4j2-task.xml
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/caller/ProcessJobCaller.java
Labels: type-bug

#4127 fix(db-browser):can not get the precision of year data type column
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/schema/MySQLNoLessThan5700SchemaAccessorTest.java
Labels: type-bug

#4129 fix(db-browser): remove @JsonProperty in DBTableStats.dataSizeInBytes
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBTableStats.java
Labels: type-bug

#4128 fix(permission): external approval integration doesn't take effect
  server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
Labels: type-bug

#4134 fix(session): oracle mode effected by kill-query-or-session.max-supported-ob-version
  server/odc-service/src/main/java/com/oceanbase/odc/service/feature/VersionDiffConfigService.java
Labels: type-bug

#4135 fix(datasource): set the proxy configuration for oracle
  server/odc-service/src/main/java/com/oceanbase/odc/service/session/factory/OBConsoleDataSourceFactory.java
Labels: type-bug

#4141 fix(audit): update i18n resources and add archive/delete projects audit events
  server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventAction.java
  server/odc-core/src/main/resources/i18n/BusinessMessages.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_CN.properties
  server/odc-core/src/main/resources/i18n/BusinessMessages_zh_TW.properties
  server/odc-migrate/src/main/resources/init-config/default-audit-event-meta.yml
Labels: type-bug

#4133 feat(resource): add double check when destroy resource
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/ResourceManager.java
Labels: type-feature

#4142 fix(sso): client mode exclude saml
  server/odc-server/src/main/resources/config/application-clientMode.yml
Labels: type-bug

#4146 fix(logicaldatabase): it may NPE when the logical database task starts
  server/odc-service/src/main/java/com/oceanbase/odc/service/task/base/logicdatabasechange/LogicalDatabaseChangeTask.java
Labels: type-bug

#4148 fix(session): kill oracle session may cause sockettimeout
  server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleSessionExtension.java
Labels: type-bug

#4149 fix(schedule): fail to operate schedule if database is invalid
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java
Labels: type-bug

#4150 fix(schedule): cherry pick describe database
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/processor/ScheduleChangePreprocessor.java
Labels: type-bug

#4144 fix(session): kill session may happen invalid server ip address
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
Labels: type-bug

#4153 security: add @SkipAuthorize in public method
  server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/ProjectService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/table/TableService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/GlobalResourceRoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/ResourceRoleService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/IntegrationService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/oauth2/TestLoginManager.java
  server/starters/web-starter/src/main/java/com/oceanbase/odc/service/iam/auth/saml/DefaultSamlUserService.java
Labels: security bug

#4156 build: merge dev/4.3.2 into main
  pom.xml
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/R4237DefaultRuleApplyingMigrate.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
Labels: type-build

#4160 security: add @SkipAuthorize for IntegrationService
  server/odc-service/src/main/java/com/oceanbase/odc/service/integration/IntegrationService.java
Labels: security bug

#4159 build: upgrade db-browser to 1.2.1
  libs/db-browser/pom.xml
  pom.xml
Labels: type-build

#4158 build: merge main to dev/4.3.3
  pom.xml
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/R4237DefaultRuleApplyingMigrate.java
Labels: type-build

#4161 fix(migrate): vectorydb only load on server mode
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/VectorDBMigrate.java
Labels: type-bug

#4166 fix(session): killing sessions failed in OSC tasks
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
Labels: type-bug

#4162 doc: init 4.3.3 changelog
  CHANGELOG-zh-CN.md
  CHANGELOG.md
Labels: documentation

#4167 feat(oss): exclusion aws-java-sdk-bundle
  pom.xml
Labels: enhancement

#4169 fix(session): killing session may fail due to a wrong regex
  server/odc-common/src/main/java/com/oceanbase/odc/common/util/HostUtils.java
  server/odc-common/src/test/java/com/oceanbase/odc/common/util/HostUtilsTest.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
Labels: type-bug

#4171 fix(session): get wrong server port
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/mysql/OBMySQLNoLessThan400StatsAccessor.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/oracle/OBOracleNoLessThan400StatsAccessor.java
Labels: type-bug

#4172 build: upgrade db-browser from 1.2.1 to 1.2.2
  libs/db-browser/pom.xml
  pom.xml
Labels: type-bug

#4174 fix(session): DBSession does not involve svrIp when OB version less than 4.0
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/model/DBMySQLProcess.java
  libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/stats/mysql/OBMySQLStatsAccessor.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/stats/OBMySQLStatsAccessorTest.java
  libs/db-browser/src/test/java/com/oceanbase/tools/dbbrowser/stats/OBOracleNoLessThan2270StatsAccessorTest.java
Labels: type-bug

#4175 fix(session): kill console query may failed cause session occupied
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
Labels: type-bug

#4176 fix(session): add retry logic when get session list
  server/odc-service/src/main/java/com/oceanbase/odc/service/db/session/DefaultDBSessionManage.java
Labels: type-bug

#4179 fix(migrate): 4331 migrate script may failed on ob1479
  server/integration-test/src/test/java/com/oceanbase/odc/service/integration/IntegrationServiceTest.java
  server/odc-migrate/src/main/resources/migrate/h2/V_4_3_3_1__alter_integration.sql
  server/odc-migrate/src/main/resources/migrate/oceanbase/V_4_3_3_1__alter_integration.sql
Labels: type-bug

#4184 fix(resource): delete redundant status transfer of k8s deployment
  server/odc-service/src/main/java/com/oceanbase/odc/service/resource/k8s/status/K8sDeploymentStatusDfa.java
Labels: type-bug

#4185 fix(dlm): failed to execute dlm task because of sync table structure failed
  server/odc-service/src/main/java/com/oceanbase/odc/service/dlm/DLMTableStructureSynchronizer.java
Labels: type-bug

#4189 fix(datatransfer): failed to re-import odc exported zip file
  server/odc-service/src/main/java/com/oceanbase/odc/service/datatransfer/task/DataTransferTask.java
Labels: type-bug

#4188 fix(schedule): detail schedule in the individual space may fail
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/factory/ScheduleResponseMapperFactory.java
Labels: type-bug

#4187 fix(sql-check): it may occur NPE when doing SQL check
  server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/TooLongCharLength.java
Labels: type-bug

#4186 fix(migrate): upgrade to 4.3.3 will fail if it exists custom environments before
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/R4237DefaultRuleApplyingMigrate.java
Labels: type-bug

#4191 fix(risklevel): delete user defined environments may cause NPE due to the detect rule could be null
  server/odc-service/src/main/java/com/oceanbase/odc/config/HookConfiguration.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/regulation/risklevel/model/RiskDetectRule.java
Labels: type-bug

#4192 fix(migrate): skip builtin ruleset migration when migrating rules
  server/odc-migrate/src/main/java/com/oceanbase/odc/migrate/jdbc/common/R4237DefaultRuleApplyingMigrate.java
Labels: type-bug

#4194 fix(schedule): check organization type failure
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#4196 fix(changelog): the status does not progress to 'Failed' when a change error occurs
  server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/QuartzJobService.java
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug

#4198 fix(changelog): cannot rollback update changelog status
  server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/ScheduleService.java
Labels: type-bug
